collectd/collectd

src/ceph.c, src/types.db
The ceph plugin uses libjson-c (https://github.com/json-c/json-c) for parsing JSON from ceph daemon admin sockets. This plugin collects all output from a ceph daemon admin socket "perf dump".
=> Add ceph plugin

src/collectd-perl.pod, src/collectd-python.pod
003c6e86b480 made this happen by default
=> Setting Globals to true is not needed anymore

AUTHORS, README, configure.ac, src/Makefile.am, src/collectd.conf.in, src/collectd.conf.pod, src/write_sensu.c
Plugin to send datapoints and notifications to sensu client's UDP socket. Inspired from write_riemann plugin.
=> write_sensu plugin implementation

src/collectd.conf.in, src/collectd.conf.pod, src/write_http.c
This continues the work initiated in #752, implementing @octo's recommendations when he reviewed the patchset. The goal stays the same (ie: resetting the connection when error conditions occur), how it's exposed to the user is a bit different.
@loginator17, @optimality, I'd love to have your feedback on this !
=> write_http timeout + low speed limit

src/amqp.c
See
* https://github.com/alanxz/rabbitmq-c/releases
* https://github.com/alanxz/rabbitmq-c/commit/9626dd5cd5f78894f1416a1afd2d624ddd4904ae
Just a trivial fix (but perhaps not the best)
=> fix build with librabbitmq 0.6.0

ChangeLog, contrib/redhat/collectd.spec
=> update changelog + bump release dates

src/collectd.conf.pod, src/daemon/configfile.c, src/daemon/plugin.c, src/daemon/plugin.h
It's the version of https://github.com/collectd/collectd/pull/1044 using the  plugin read callback.
=> Support for call the flush callback at regular intervals using the  plugin read callback.

src/collectd.conf.pod, src/openldap.c
This patch adds support for simple bind authentication, other SASL mechanisms are not supported now.
=> add support for simple bind authentication

src/apache.c, src/collectdmon.c, src/curl.c, src/curl_json.c, src/curl_xml.c, src/gmond.c, src/ipvs.c, src/java.c, src/memcachec.c, src/powerdns.c, src/rrdtool.c, src/utils_cache.c, src/utils_cmd_flush.c, src/utils_cmd_putval.c, src/utils_ignorelist.c, src/utils_rrdcreate.c
This fixes the memory leaks (or perceived memory leaks) found by clang's static code analysis in the *collectd-5.4* branch.
=> Fix memory leaks (collectd-5.4)

.travis.yml
This is not as featured as the collectd-ci infrastructure but can give a quick additional data point on commits.
What do you think @mfournier ?
=> Enable travis builds

configure.ac, src/Makefile.am, src/disk.c
I took the liberty to rebase what @delphij wrote on master and made the changes @octo suggested in #341
This could really do with some review and testing since I'm not entirely convinced I did it right ;)
=> FreeBSD disk plugin

src/powerdns.c
=> powerdns: update recursor stats to 3.7.3

src/collectd-tg.c
=> gettimeofday() needs <sys/time.h>

src/types.db, src/zfs_arc.c
This gives more ZFS information that is useful
=> Solaris zfs changes

configure.ac, src/Makefile.am, src/daemon/Makefile.am, src/libcollectdclient/Makefile.am
=> -Werror build flag handling + build options printout

src/python.c
=> python: Fix double-free bug.

configure.ac, src/utils_mount.c
=> utils_mount: use reentrant getmntent_r when we can

src/mqtt.c
Hello,
I have been testing subscribing to MQTT topics but was initially unable to get it to work. After some investigation, I found that it was checking that the MQTT payload was NULL-terminated. However it is not necessary, or typical, to NULL-terminate the payload because there is a length field instead.
Applying this patch fixes it for me.
nick.
=> Fix for subscribing to MQTT

.travis.yml
https://docs.travis-ci.com/user/trusty-ci-environment
=> Travis: switch to new Trusty environment

configure.ac
./configure --help now shows:
Report bugs to <https://github.com/collectd/collectd/issues>.
collectd home page: <https://collectd.org>.
=> Set bugreport url and homepage url

src/mqtt.c
=> mqtt: fix an out-of-bounds write

src/irq.c
=> irq plugin: close file descriptor on failure

src/perl.c
=> perl: unlock mutex on error

src/redis.c
=> redis plugin: make sure buffer is null-terminated

src/rrdtool.c
=> rrdtool: unlock mutex on error

src/curl_json.c
=> curl_json: remove dead code

src/write_kafka.c
It was all over the place.
I went with 4 spaces since that's what the majority
of code used.
=> write_kafka: fix indentation

src/varnish.c
Also paves the way for monitoring non-MAIN metrics, as well as dropping support for varnish 2.x (things that I'd like to see in collectd 5.6).
ping @rubenk
=> Varnish: support for 4.1

src/collectd.conf.in, src/collectd.conf.pod, src/statsd.c
CC: @jamtur01, @pyr, @duylong
Issues: #929, #1282, #1311
=> statsd plugin: Implement the "CounterSum" option.

src/ceph.c, src/ceph_test.c
See #1350 for a discussion of the bug.
=> ceph plugin: Fix another buffer overflow.

src/collectd.conf.pod, src/ping.c
Fixes: https://github.com/collectd/collectd/issues/168
=> ping plugin: Implement "Size" option to specify payload size

src/libcollectdclient/network.c
=> libcollectdclient: don't close socket twice

src/daemon/types_list.c
=> types_list.c: fix two resource leaks

src/processes.c
=> processes plugin: plug leak on error

src/write_kafka.c
=> write_kafka: fix two leaks on error

src/email.c
=> email plugin: fix check for result of malloc

src/write_kafka.c
=> write_kafka plugin: Use the user-provided key verbatim, not its CRC32.

contrib/systemd.collectd.service
Any comments @rubenk ? Thanks !
=> systemd.collectd.service: improve systemd & capabilities explanations

src/processes.c
I (personally) found this code to be repetitive and too long for what it does. We can improve readability
(IMO) by factoring it out into a subroutine. There is no change in semantics.
=> Factor out some common functionality

src/plugin.c, src/processes.c, src/python.c, src/tokyotyrant.c
Found with -Wstrict-prototypes and -Wold-style-definition
=> Fix a few more prototypes

src/powerdns.c
make some variables static while we're at it
=> powerdns: constify some stuff

src/collectd-exec.pod
=> added definition of N to collectd-exec

src/collectd.conf.pod, src/daemon/meta_data.c, src/daemon/meta_data.h, src/target_set.c
Address review from @rubenk for https://github.com/collectd/collectd/pull/1106
=> Added MetaDataSet to target_set

src/disk.c
For Linux systems, disk plugin send 'disk_octets', 'disk_ops', 'disk_time' data only then real data exist.
There is no similar check for 'disk_merged', 'disk_io_time', 'pending_operations' metrics and their data is collected independently of real data existence.
Because of this, collectd produces empty metrics for LVM ('disk_merged' always zero) and Linux RAID MD devices ('disk_merged', 'disk_io_time', 'pending_operations' always zero). In some configurations there is too much unneeded metrics. 
Proposed patch solves this issue.
=> disk plugin: send disk_merged,disk_io_time,pending_operations only when real data exists for device

src/disk.c
There is no need to call ignorelist_match() for each device many times (for each collected metric). One call per cycle is enough.
=>  * disk plugin: call ignorelist_match() once per device, not for each send metric

src/collectd.conf.pod, src/openldap.c
@marekbecka, maybe you'd like to have a look at this ? Thanks !
=> Openldap: persistent connection + sane default timeout

.gitignore, Makefile.am, README, configure.ac, proto/Makefile.am, proto/collectd.proto, proto/types.proto, src/Makefile.am, src/collectd.conf.in, src/collectd.conf.pod, src/daemon/collectd.h, src/daemon/utils_cache.c, src/daemon/utils_cache.h, src/grpc.cc
This new plugin embeds a gRPC server (http://grpc.io) into collectd. For now, it supports dispatching and querying values.
=> gRPC server plugin

configure.ac, src/Makefile.am, src/ceph_test.c, src/daemon/Makefile.am, src/testing.h, src/utils_mount_test.c, src/utils_vl_lookup.c, testwrapper.sh
Also, fix all problems identified that way.
=> unit tests: Run all tests through Valgrind's memcheck, if available.

src/apcups.c
=> apcups: ignore result of swrite in net_shutdown

src/mysql.c, src/types.db
Add slow queries statistics to mysql module
=> Add slow queries statistics to mysql module

configure.ac
This way, it will show up in config.log as well.
=> configure: Use AC_MSG_RESULT to print the config summary.

src/Makefile.am, src/collectd.conf.pod, src/utils_format_kairosdb.c, src/utils_format_kairosdb.h, src/write_http.c
Adds KairosDB format for write_http collectd plugin.
see  collectd/collectd#1537
=> Add KAIROSDB format to write_http plugin

src/match_empty_counter.c
=> empty_counter match: Add support for the DERIVE data source type.

src/grpc.cc
Make control flow more straight forward and handle all cleanup in one place.
=> grpc plugin: Simplify error handling a bit.

configure.ac, src/Makefile.am
=> Protobuf autoconf adjustments

src/write_riemann.c
The code has become a mix of tabs and spaces due to various
merges over the years. I tossed a coint and went with 4 spaces here.
The diff is easier to review if you add &w=1 to the url on github.
=> write_riemann plugin: reindent

.clang-format
To use it, use `clang-format --style=file`
=> Add a config file for clang-format

configure.ac, src/write_sensu.c
asprint is only available from Solaris 10 update 11.
Fixes #1798
=> write_sensu: Re-add substitute for asprintf

.gitignore, src/collectd.conf.in, src/collectd.conf.pod, src/mysql.c
Hoping this one is for good now !
thanks to @XANi for helping me fixing
=> mysql plugin: add support for Galera statistics

src/python.c
Return an error when something goes wrong during config.
We still loop through all specified modules so all errors are logged.
Fixes #926
=> python plugin: return error on config failure

src/daemon/configfile.c, src/daemon/utils_avltree.h, src/daemon/utils_heap.h, src/rrdtool.c
=> Spelling: it's -> its

configure.ac
pkg-config is not optional anymore.
=> configure.ac: remove checks for pkg-config

src/mysql.c
This is a rebased version of #1111
=> Mysql plugin: remove double reported metrics

proto/collectd.proto, proto/types.proto, src/collectd.conf.in, src/collectd.conf.pod, src/grpc.cc
This PR implements (most of) the changes discussed in #1819, please see that issue for details. Also, comments regarding the *design* should go in that issue while comments regarding the *implementation* should go here.
=> grpc plugin: Refactor plugin.

src/collectd.conf.pod, src/cpu.c
Change-Id: Ia305b74139352f16f71b1f747875d6c7a0c376a4
=> implement reporting of ncpu

.github/ISSUE_TEMPLATE, .github/issue_template.md, CONTRIBUTING.md, README
Everything in the file is a suggestion; I'm hoping for a discussion around how we want to handle contributions.
=> CONTRIBUTING.md: Give more concrete advice on writing bugs and PRs.

src/python.c
None of these commits actually fixes #1645 but they're all necessary in order to get a fix.
=> python plugin: Various shutdown fixes.

src/collectd.conf.pod, src/target_set.c
=> target_set.c: rename 'MetaDataSet' option

src/Makefile.am, src/collectd.conf.pod, src/write_log.c
=> Change Plugin:WriteLog to also write JSON; add optional configuration.

src/battery_statefs.c, src/conntrack.c, src/cpufreq.c, src/daemon/common.c, src/daemon/common.h, src/entropy.c, src/thermal.c, src/turbostat.c
This implements the function proposed in #1914 and updates the plugins mentioned there.
=> Implement parse_value_file().

src/daemon/utils_time.c
@octo, apologies for rushing #1918 in and missing this.
=> Bug fix: invalid strcpy position in utils_time.

src/daemon/plugin.c, src/daemon/plugin.h
=> src/daemons/plugin.c: Don't modify user_data_t* in plugin_register_flush().

src/processes.c
Processes IO and context switch values are not used when only summary is submitted.
Added new function `ps_fill_details()` as part of prepare for #836 / #1041 implementation.
=> processes plugin: Do not gather processes IO and context switch data when unneeded

src/powerdns.c
Show socket path in log messages.
Example:
```
[2016-10-20 20:22:37] powerdns plugin: Socket `/var/run/pdns.controlsocket` connect failed: No such file or directory
[2016-10-20 20:22:37] powerdns plugin: Socket `/opt/collectd/var/run/collectd-powerdns` connect failed: No such file or directory
[2016-10-20 20:22:37] powerdns plugin: powerdns_get_data failed.
```
Superseedes: #1995
=> powerdns plugin: Improved error reporting

src/write_http.c
=> write_http: Fixed DS type check

src/write_kafka.c
=> write_kafka plugin: Reintroduce the "Key Random" setting.

src/apcups.c
=> apcups plugin: Skip metrics not reported by the UPS.

src/write_prometheus.c
=> write_prometheus plugin: Escape label values.

configure.ac, src/amqp.c, src/daemon/plugin.c, src/daemon/plugin.h, src/dns.c, src/email.c, src/exec.c, src/gmond.c, src/gps.c, src/ipmi.c, src/mqtt.c, src/network.c, src/pinba.c, src/ping.c, src/python.c, src/rrdtool.c, src/sigrok.c, src/unixsock.c
This is a rebased & updated version of #547.
I've been using this patchset for a few months now (on Linux only though), and haven't encountered any problem with it.
Thanks a lot @manuelluis !
=> Naming threads

src/Makefile.am, src/utils_format_graphite_test.c
First step towards fixing issue #419.
=> src/utils_format_graphite.[ch]: Add unit test.

src/amqp.c, src/collectd.conf.in, src/collectd.conf.pod, src/utils_format_graphite.c, src/utils_format_graphite.h, src/utils_format_graphite_test.c, src/write_graphite.c, src/write_kafka.c
=> amqp, write_graphite and write_kafka plugins: Implement the "[Graphite]PreserveSeparator" option.

src/Makefile.am, src/utils_cmd_flush.c, src/utils_cmd_flush.h, src/utils_cmd_putval.c, src/utils_cmd_putval.h
=> src/Makefile.am: Fix linking with libcmds.la.

README, configure.ac, src/Makefile.am, src/uuid.c
HAL has been deprecated for a long time.
=> uuid plugin: remove support for HAL

src/smart.c
=> smart plugin: Refactor, demote warnings to debug.

src/virt.c
Document the return value and fix the error path of
lv_domain_get_tag
=> virt plugin: fix error path in lv_domain_get_tag

src/write_prometheus.c
=> write_prometheus: plug a small leak

src/target_set.c
=> target_set: plug leak on error

src/target_set.c
=> set target: Avoid casting negative int to size_t.

src/dpdkstat.c
=> Dpdk: double close

src/netapp.c
=> netapp plugin: Fix complation problems.

src/mcelog.c
This series of patches introduces following changes:
- Increase delay between socket re-initialization from 1ms to 1000ms
- Check if location (plugin instance) was correctly parsed
- Dispatch notification on successful connection to mcelog server
- Free notification metadata
- Other minor changes
=> mcelog: Bug fixes and code style changes

src/intel_rdt.c
Fix the configuration to stop collectd bombing out and deal with configuration
errors gracefully. Otherwise collectd will fail at the configuration phase
with: "Error: Reading the config file failed!".
Signed-off-by: Tahhan, Maryam <maryam.tahhan@intel.com>
=> intel_rdt: bugfix configuration

AUTHORS, configure.ac, src/collectd.conf.in, src/collectd.conf.pod, src/nut.c
See issue #1760 for full write up of changes and dev/implementation decisions, as well as link to tested scenarios using the new code.
=> SSL Certificate Verification For collectd-nut Plugin

src/virt.c
This patch fixes collecting disk/iface metrics from paused domains and prevents failures in virDomainBlockStats()/virDomainInterfaceStats() with timeout error:
```
libvirtd: Timed out during operation: cannot acquire state change lock
collectd: libvirt: QEMU Driver error : Timed out during operation: cannot acquire state change lock
```
Signed-off-by: Igor Pavlikevich <ipavlikevich@gmail.com>
=> virt plugin: fix skipping inactive domains

src/daemon/utils_match.c
Added missing regex resource release
=> fix for memory leak in utils_match.c

src/intel_rdt.c
Fix logic of validating core ids provided in configuration.
=> intel_rdt: fix validation of configured core id values

src/daemon/common.c, src/oracle.c, src/virt.c, src/write_mongodb.c, src/write_sensu.c
sizeof(char) is 1 by definition.
=> Tree-wide: remove last remnants of sizeof(char)

src/sensors.c
Add support for current sensor data collection and add ifdefs for old lm-sensors versions.
=> sensors: support current values

src/bind.c
=> fix BIND timezone parsing issue

src/apcups.c
Implementation was broken, it doesn't reconnects as was planned.
=> apcups: Fix reconnect implementation

src/daemon/collectd.c
One possible implementation of collectd/collectd#2421
=> Add daemon option to avoid making BaseDir

src/collectd.conf.in, src/collectd.conf.pod, src/table.c
Be consistent with other 'generic' plugins.
=> Table plugin: Allow custom plugin name to be reported

src/collectd.conf.in, src/collectd.conf.pod, src/mqtt.c
=> mqtt plugin: Add support for TLS in Subscriber blocks.

src/write_redis.c
This change introduces max_set_duration, the duration for the value
as max_set_size. max_set_size can keep the db size, however, sometime
max_set_size allows to contain old data. max_set_duration can keep
the latest data.
=> write_redis plugin: Add max_set_duration to set duration for value

src/daemon/common.c, src/memcached.c
Implemented persistent connections. It is a must-have feature for statistics daemon.
=> memcached: Persistent connections with IO timeouts

src/collectd.conf.in, src/collectd.conf.pod, src/types.db, src/varnish.c
Hi guys, please give me some feedback on how to reach your merge criteria.
=> Varnish plugin update

src/utils_match.c
was: NaN
CC: @rpv-tomsk
Fixes: #2448
=> src/utils_match.c: Reset UTILS_MATCH_CF_GAUGE_INC matches to zero

src/snmp.c
Collectd does not check for `res->errstat` value after
`snmp_sess_synch_response()` call. In case of error, there is no any data in
`res->variables` actually, but variables are tried to be processed as usual.
Suffix calculation will fail, so all subtrees will be marked as failed, not
only one subtree which caused an error.
The csnmp_instance_list_add() call will fail too, and, as result,
`csnmp_read_table` will finish it's work without any data submission.
The log message like
"snmp plugin: host HOSTNAME: csnmp_instance_list_add failed",
which is put into logs in this case, also has no enough diagnostic data.
Added code to proper check for `res->errstat` and to try to get available data.
Issue: #2291
=>  snmp plugin: Added res->errstat check

src/collectd.conf.in, src/collectd.conf.pod, src/dbi.c, src/oracle.c, src/postgresql.c
Like added in  #1558,  #1563 and #1681, added option 'PluginName' to dbi-related plugins: 'dbi', 'oracle' and 'postgresql'.
=> Allowed custom plugin name in 'dbi', 'oracle' and 'postgresql' plugins.

src/dbi.c
Partially stolen from #1707.
CC: @rpv-tomsk
=> dbi plugin: Fix memory leaks.

src/collectd.conf.in, src/collectd.conf.pod, src/ipmi.c
Listen for ipmi sensor threshold and discrete events. Send notification in case event is received. Fix typos.
=> ipmi: add support for system event log (SEL).

src/collectd.conf.in, src/collectd.conf.pod, src/varnish.c
extending the varnish plugin with varnish-plus counters (mainly the MSE storage engine)
i don't think we neither need separate plugin for this, extra macros (HAVE_VARNISH_V4_PLUS) nor updating the autotools
=> Varnish plus plugin upgrade

src/write_prometheus.c
I hope that this makes debugging issues such as #2475 easier.
=> write_prometheus plugin: Implement logging callback.

src/collectd.conf.pod
=> processes: Improved documentation

src/collectd-snmp.pod, src/collectd.conf.in, src/snmp.c
Test details: https://gist.github.com/cvicente/b309f9130a50381e11e5140cd97b1dd8
=> Add timeout and retry config options for SNMP plugin (#1472)

src/rrdtool.c
Primarily to test the clang-format bot.
=> rrdtool plugin: Small code cleanup.

Makefile.am, src/daemon/collectd.c, src/daemon/collectd.h, src/daemon/configfile.c, src/daemon/globals.c, src/daemon/globals.h, src/daemon/plugin.h, src/daemon/plugin_mock.c, src/perl.c
A bit of refactoring so that reading the config file is done outside of main and global variables are separated into their own files.
=> Library refactor

src/lvm.c
=> lvm update: Check for the CAP_SYS_ADMIN capability.

src/daemon/plugin.c
Primarily to test the clang-format bot.
=> src/daemon/plugin.c: Fix some coding style.

src/memcached.c, src/types.db
=> memcached plugin: Report "listen_disabled_num" as "operations".

docs/maintainer_guide.md
Hi guys,
I was going to send something like this to Pavel, and then thought it might make sense to document it more openly. My intention is more to document the status quo then to come up with new or stricter rules. If you disagree with anything or would like to see something added, please let me know!
Best regards,
—octo
=> docs/maintainer_guide.md: First draft.

src/daemon/collectd.c
=> Fix hostname_g initialization from gethostname()

contrib/redhat/collectd.spec, src/netlink.c
This adds the changes requested in #2461 and fixes a small merged conflict introduced by 41b1a6627.
=> Fix collectd 5.8 build

configure.ac, src/varnish.c
This is a duplicate of #2525, against the collectd-5.8 branch.
=> Varnish 5.2 compat on collectd 5.8

src/daemon/meta_data.c
=> src/daemon/meta_data.c: Fix double unlock.

src/ovs_events.c
=> ovs_events plugin: Replace strncpy() with sstrncpy().

src/ovs_stats.c
br_name would leak when jumping to cleanup_fail.
CID: 179229
=> ovs_stats plugin: Fix a memory leak.

src/snmp.c
=> snmp plugin: Ensure that index is within bounds.

src/zfs_arc.c
=> zfs_arc plugin: Allocate ksp later to avoid memory leak.

src/ovs_stats.c
=> ovs_stats plugin: Add missing unlock.

src/processes.c
=> processes plugin: Fix check for context switch counters.

src/utils_format_json.c
=> src/utils_format_json.c: Check return values of yajl_gen_* functions.

src/write_sensu.c
=> write_sensu plugin: Unlock mutex before destroying it.

src/target_set.c
=> set target: Ensure that int being cast to size_t is positive or zero.

src/target_set.c
=> set target: Fix memory leak.

src/aggregation.c
=> aggregation plugin: Check return value of config functions.

configure.ac, src/collectd.conf.in, src/collectd.conf.pod, src/grpc.cc
The client-side SSL options don't have an equivalent field.
=> grpc plugin: Implement the VerifyPeer option for servers.

src/turbostat.c
Change-Id: Icb57cf5ab116069b1e4d9580e248af1207e3282b
=> turbostat: Add support of reporting GPU power on SKL in turbostat

src/intel_pmu.c
Null pointer dereference could occur for invalid first hardware event.
In pmu_add_hw_events if the first event was not resolved, on the second
iteration the eventlist_last could be dereferenced to mark previous
event as group leader.
It fixes the bug described in #2675 .
=> intel_pmu: fix for possible null pointer dereference

contrib/sles10.1/collectd.spec, contrib/snmp-probe-host.px, docs/README.virt.md
=> Propose fix some typos

src/perl.c
=> perl plugin: Fix compile fail with message "void function cannot return value"

src/uuid.c
Closes: #2723
References: #2467
=> uuid plugin: Fixed hostname setting

src/disk.c
This fixes a bug which makes it so the disk plugin can't use UDEV support.
https://github.com/collectd/collectd/issues/2651
=> change HAVE_UDEV_H to HAVE_LIBUDEV_H for bug 2651

src/daemon/common.h
This one include was missing from PR #2711
=> Include kstat.h when available

src/collectd.conf.pod
=> docs: Fix typo in collectd.conf.pod

src/collectd.conf.in, src/collectd.conf.pod, src/ping.c
=> ping plugin: support specifying the address family

src/stdendian.h
Please try this to resolve issue #2758
=> Add endianness checks for AIX

src/email.c, src/exec.c, src/liboconfig/parser.y, src/table.c
I'm unable to do this in generic way, so will try this one.
```
Username for 'https://github.com':
Password for 'https://github.com':
Counting objects: 22, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.26 KiB, done.
Total 8 (delta 7), reused 0 (delta 0)
remote: Resolving deltas: 100% (7/7), completed with 7 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/collectd-5.8.
remote: error: Required status check "pull-requests-github_trigger-aggregation" is expected.
To https://github.com/collectd/collectd.git
! [remote rejected] collectd-collectd-5.8 -> collectd-5.8 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/collectd/collectd.git'
```
=> Merge collectd-5.7 to collectd-5.8

Makefile.am, configure.ac, src/barometer.c
=> Added support for libi2c-4.0

src/utils_ovs.c
Fixes #2800
Signed-off-by: Ciara Loftus <ciara.loftus@intel.com>
=> utils_ovs: Avoid potential access of freed memory

src/daemon/configfile.c
Some functions could return error code without any messages.
=> config parser: Improved error reporting on global options

src/daemon/common.c, src/rrdtool.c
=> rrdtool plugin: Added more error reporting

src/filecount.c, src/gmond.c, src/memcachec.c, src/netapp.c, src/table.c, src/threshold.c, src/utils_db_query.c, src/utils_format_graphite.c, src/utils_rrdcreate.c, src/write_riemann.c, src/write_sensu.c
Closes: #2011 (superseedes)
Issue: #1949
Issue: #2799
Issue: #2821
=> cleanup: cf_util_get* instead of local copy in plugins, prefixed error reporting

src/snmp_agent.c
Change-Id: Icb74f9978833191a390c952a09695ccb60ff8452
Signed-off-by: Mozejko, MarcinX <marcinx.mozejko@intel.com>
=> SNMP Agent plugin: Fix coverity scan issues #2814

src/collectd.conf.in, src/collectd.conf.pod, src/routeros.c
=> routeros: Add support for temperature and voltage data 

src/daemon/plugin.c
=> daemon: make plugin_dispatch_multivalue() obey write queue limits

src/nfs.c
=> nfs: Fix number of fields for NFSv4

src/exec.c
Dynamically allocate grname buffer in increments of `_SC_GETGR_R_SIZE_MAX/_SC_PAGESIZE`
Fixes: #2696
=> exec plugin: dynamically allocate grname buffer for getgrnam_r

src/collectd.conf.pod
Change-Id: I321d320885c780f88ffe9f4d9538dad4c6c57e74
=> add some useful info to libvirt manpage

src/ntpd.c
=> ntpd: plug potential leak on error

src/virt.c
This pull request fixes [issue](https://github.com/collectd/collectd/issues/2956) by updating the static text in log messages.
=> virt plugin: Fix typo in error messages.

src/collectd.conf.pod, src/write_prometheus.c
This allows to set specific address to listen on.
Closes: #2173
Closes: #2288
=> write_prometheus: Added 'Host' option.

src/swap.c
=> swap plugin: Drop support for Linux 2.4.

src/collectd-python.pod
add Import configuration option to python documentation
=> add Import configuration option to collectd-python documentation

src/collectd.conf.pod
Documented implementation from 452324c4a5b6ec07575cfc5d5d339852b040509b
=> virt plugin: Document Instances option

src/ovs_stats.c
Signed-off-by: Matteo Croce <mcroce@redhat.com>
Signed-off-by: Ryan McCabe <rmccabe@redhat.com>
=> Add ovs-dpdk extended metrics

contrib/collection3/etc/collection.conf
collection3: Add Type for smart_temperature
=> collection3: Add Type for smart_temperature

src/libcollectdclient/network_parse.c
Changelog: libcollectdclient: fix stringop compiler warning
=> Libcollectdclient fix stringop warning

src/rrdcached.c
Changelog: cleanup rrdcached plugin a bit
=> Rrdcached cleanup

src/collectd-lua.pod, src/collectd.conf.pod
Changelog: fix rendering of collectd-lua(5) manpage
=> Fix syntax in collectd lua manpage

src/collectd.conf.pod
Changelog: fix typo in collectd.conf(5)
=> collectd.conf(5): fix a typo

configure.ac
All these flags can be found in config.log if needed.
=> Reduce the amount of output from ./configure

configure.ac, src/collectd.conf.pod, src/cpufreq.c
ChangeLog: cpufreq plugin: Added support for FreeBSD
=> cpufreq plugin: Add FreeBSD support

src/mysql.c, src/types.db
ChangeLog: mysql plugin: added uptime metric
=> mysql: [impr] enable uptime metric

src/memcached.c
Changelog: memcached plugin: Report uptime metric
Issue: #2852
=> memcached plugin: Report uptime metric

src/match_regex.c
ChangeLog: regex match: Fix unexpected match with empty meta data
If a user set
MetaData "foo" "bar"
and a metric does not have meta data (vl->meta == NULL), it causes
unexpected match.
Existance of MetaData config should be checked before meta data in
a metric.
See also: #1930
Signed-off-by: Takuro Ashie <ashie@clear-code.com>
=> regex match: Fix unexpected match with empty meta data

src/syslog.c
Change-Id: I0972f74f3fff05cf29fa9b0be383f0b0df1e6d03
Fixes: #3200
ChangeLog: fix syslog config callback
=> Fix return code introduced by #3182

src/daemon/plugin.c, src/intel_rdt.c
ChangeLog: Build System: fix compile time issues
This resolves #3242 and should also resolve #3179.
Signed-off-by: Matthias Runge <mrunge@redhat.com>
=> Fix compile time issues

bindings/perl/lib/Collectd/Plugins/OpenVZ.pm
Changelog: perl module Collectd::Plugins::Openvz: Fix indentation of some closing curlies
=> Fix indentation of some closing curlies

contrib/collectd_network.py, contrib/collection3/share/navigate.js, contrib/php-collection/browser.js, src/daemon/utils_random.h, src/netlink.c, src/utils/common/common.c, src/utils/latency/latency.h, src/utils/proc_pids/proc_pids.h, src/utils_tail_match.h
Changelog: fix a few issues found with LGTM
=> Fix a few issues found with LGTM

src/daemon/plugin.c, src/intel_rdt.c, src/syslog.c, src/utils/common/common.c
Merge back fixes to be able to release 5.9.2
=> Collectd 5.9

src/collectd.conf.pod
ChangeLog: mysql plugin: Minor documentation improvements
=> Tweak docs for mysql plugin

Makefile.am, configure.ac
This fixes issue #3220.
ChangeLog: Build System: test_plugin_network link to libnsl.so if needed for inet_ntop()
=> Link to libnsl.so if needed for inet_ntop()

src/daemon/common_test.c
ChangeLog: Fix `make check`
Fixes #3284
=> Fix make check

ChangeLog, contrib/redhat/collectd.spec, version-gen.sh
This patch provides the changelog and the change to version-gen.
=> Changelog and preparation for collectd 5.10

contrib/redhat/collectd.spec
ChangeLog: contrib: this fixes package does not exist in rpmbuild
```
Package does not exist: %files write_syslog
```
Change-Id: Ic4bbe3ffa60be0f0c2ca78487119ec029a9a4ce0
=> fix missing package in specfile

Makefile.am
=> gpu_nvidia plugin: fix build

src/turbostat.c
Fix warnings generated by the turbostat plugin due to trailing
characters while picking out the first number in a range.
ChangeLog: turbostat plugin: Fix parsing warnings.
PR: #2365
Signed-off-by: Ryan McCabe <rmccabe@redhat.com>
=> turbostat: Fix parsing warnings

configure.ac, src/nfs.c
ChangeLog: NFS plugin: An implementation for NetBSD (using sysctl) has been added.
=> Fix of "Implement the NFS plugin for NetBSD #3333"

AUTHORS, Makefile.am, README, configure.ac, src/buddyinfo.c, src/collectd.conf.in, src/collectd.conf.pod, src/types.db
ChangeLog: buddyinfo plugin: New plugin for memory fragmentation info.
Signed-off-by: Asaf Kahlon <asafka7@gmail.com>
=> buddyinfo plugin: new plugin for memory fragmentation info

src/nfs.c
ChangeLog: plugin nfs: Fix condition on existence of libkstat
=> Fix condition on libkstat existence

src/daemon/filter_chain.c
ChangeLog: Auto load matches and targers if AutoLoadPlugin option is set
=> Autoload matches and targets in the same way of plugins.

src/apache.c
Apache http mod_status added a second set of `BusyWorkers`, `IdleWorkers` in https://github.com/apache/httpd/commit/6befc1893bea72320388b84fd879a4533e29b244
E.g.
```
...
DurationPerReq: 8.53412
BusyWorkers: 1
IdleWorkers: 49
Processes: 2
Stopping: 0
BusyWorkers: 1
IdleWorkers: 49
ConnsTotal: 2
...
```
This will result in an attempt to submit those twice in the same interval which errors with
- apache_connections.rrd: illegal attempt to update
- apache_idle_workers.rrd: illegal attempt to update
This patch adds a guard to only submit one value per update.
ChangeLog: apache plugin: BusyWorkers/IdleWorkers update has been fixed.
=> Fix apache plugin BusyWorkers/IdleWorkers update

src/daemon/plugin.c
ChangeLog: plugin core: Fix error/warning messages to contain more information.
This closes #3279
=> Yellowpattern error warning messages

src/collectd-exec.pod, src/collectd-unixsock.pod, src/utils/cmds/cmds_test.c, src/utils/cmds/putval.c, src/utils/common/common.c, src/utils/common/common.h
ChangeLog: text protocol: Add support for meta_data in PUTVAL
=> Forward-port and rebase to master of "text protocol: Add support for meta_data in PUTVAL #2726"

src/collectd.conf.in, src/collectd.conf.pod, src/intel_pmu.c
ChangeLog: intel_pmu plugin: support for uncore multi pmu
Add support for new libjevents features to handle uncore and multi PMU events.
=> intel_pmu plugin: support for uncore multi pmu

Makefile.am, README, configure.ac, src/capabilities.c, src/capabilities_test.c, src/collectd.conf.in, src/collectd.conf.pod, src/utils/dmi/dmi.c, src/utils/dmi/dmi.h
ChangeLog: capabilities plugin: New plugin to read static platform data
=> Forward-port and rebase of "New Capabilities plugin #3292"

src/exec.c
ChangeLog: exec plugin: replace select with poll
Replace select with poll to allow big File Descriptors values on systems which allow more than 1024 open FDs. Other than that there is no any change in functionality.
This fixes issue #3322.
=> exec plugin: replace select with poll

bindings/java/org/collectd/java/GenericJMXConfValue.java
ChangeLog: GenericJMX plugin: Support boolean input.
=> GenericJMX plugin: Support boolean input

src/amqp.c, src/collectd.conf.in, src/collectd.conf.pod
ChangeLog: AMQP plugin: Add TLS support.
Note: this supersedes https://github.com/collectd/collectd/pull/1108/
=> amqp: add tls support

contrib/collection.cgi
Propose to reverts collectd/collectd#1339 and replace it by hardcoded `value` string.
Changelog: Revert #1339 and use hardcoded `value` string.
=> Revert "collection.cgi: parse types.db to discover DS names"

src/utils/ignorelist/ignorelist.c
ChangeLog: plugin df: Coding style fixes
=> Fix coding style

CODE_OF_CONDUCT.md
Add the "Contributor Covenant" as collectd's code of conduct, as discussed at the collectd meetup in Munich.
ChangeLog: collectd: A Code of Conduct has been added.
=> Add Code of Conduct.

configure.ac, src/collectd.conf.in, src/collectd.conf.pod, src/varnish.c
ChangeLog: This reverts "Support for Varnish 6 and remove Varnish 2, 3 and 5"
=> Collectd 5.11 revert 3360

AUTHORS, ChangeLog, contrib/redhat/collectd.spec, version-gen.sh
Add a changelog entry for collectd-5.11 and also update version-gen.sh
=> Prepare collectd-5.11 release

AUTHORS, ChangeLog, contrib/redhat/collectd.spec, version-gen.sh
Merge collectd-5.11 back to master
=> Update master with 5.11 changelog

src/collectd.conf.in, src/collectd.conf.pod, src/write_sensu.c
ChangeLog: write_sensu: add the IncludeSource option
It might make sense to enable the new option by default because it's probably what most users expect the plugin to do.
=> write_sensu: add the IncludeSource option

src/intel_rdt.c, src/intel_rdt_test.c
ChangeLog: intel_rtd plugin: Fixed nan values in csv output.
=> intel_rdt: correct value metrics reported by the plugin

src/write_prometheus.c
ChangeLog: write_prometheus: fix libmicrohttpd api change
Closes #3511
=> w_prometheus: fix libmicrohttpd api change

src/daemon/metric.c, src/daemon/metric.h
Reverts collectd/collectd#3523
=> Revert "Integrate distribution metrics into collectd core"

src/daemon/metric_test.c
ChangeLog: Changed the initialization of a metric_t in the metric_label_set test.
=> Fixed unit test to work with adjusted metric_reset function

src/daemon/distribution.c, src/daemon/distribution.h, src/daemon/distribution_test.c, src/daemon/metric_test.c
ChangeLog: Distribution data structure: Add getters
Add getter (i.e. total sum, total counter, squared deviation sum) functions for distribution_t data structure. 
Add unit tests for getters.
=> Add squares

ChangeLog, version-gen.sh
Update of changelog for release 5.12.
@octo , @mrunge I hope this is the right approach to update the changelog and version number. Is there a plan to add anything more to the release?
=> Update changelog and version number for release 5.12.

src/write_http.c
Fix memory leaks in write_http plugin
ChangeLog: fix memory leaks in write_http plugin
=> Fix memory leaks in write_http plugin

src/daemon/metric.c, src/daemon/metric.h, src/daemon/plugin.c, src/daemon/utils_cache.c, src/daemon/utils_cache.h, src/daemon/utils_cache_test.c
ChangeLog: Utils Cache: Fix memory leaks by adding new uc_destroy function
=> Utils cache destroy

src/utils/common/common.c
Fix seg fault in format_name function in case when hostname is equal to NULL.
ChangeLog: Fix seg fault in format_name function
=> Fix seg fault in format_name function

src/daemon/distribution.c
ChangeLog: Distribution data structure: Avoid deadlocks.
- Introduce `distribution_lock` for locking two distribution_t objects.
- Introduce `distribution_unlock` for unlocking two distribution_t objects.
- Fix the lock order in `distribution_equal`.
- Fix the lock order in `distribution_sub`.
=> Avoid deadlocks.

src/interface.c
ChangeLog: interface plugin: Updated to the v6 API.
Fixes: #3641
=> interface plugin: Convert to the v6 API.

src/memory.c
This also migrates the new NetBSD code to using metric_family_t.
ChangeLog: memory plugin: The plugin has been migrated to metric labels.
Fixes: #3667
=> memory plugin: Implement absolute/percentage reporting.

src/uptime.c
ChangeLog: uptime plugin: migration to v6.0
=> [collectd 6] uptime: migration to v6.0

src/users.c
ChangeLog: users plugin: migration to v6.0
=> [collectd 6] users: migration to v6.0

src/buddyinfo.c
ChangeLog: buddyinfo plugin: migration to v6.0
=> [collectd 6] buddyinfo: migration to v6.0

src/protocols.c
ChangeLog: protocols plugin: migration to v6.0
=> [collectd 6] protocols: migration to v6.0

src/protocols.c
ChangeLog: protocols plugin: Initialize metric_family to zero
=> [collectd 6]  protocols: Initialize metric_family to zero

src/ping.c
ChangeLog: ping plugin: migration to v6.0
=> [collectd 6] ping: migration to v6.0

.cirrus.yml, .travis.yml, solaris-ci.flags, src/write_influxdb_udp.c
Initial version for v6.0. 
Issue #3746
Changelog: write_influxdb_udp.c: migration to v6.0
=> [collectd 6] write_influxdb_udp: migration to v6.0

.cirrus.yml
ChangeLog: CI: drop el6 from testing
=> Drop el6 from testing

src/python.c
ChangeLog: python: Fix compile-time errors about deprecation via ifdefs.
=> ChangeLog: python: Fix compile-time errors about deprecation via ifdefs.

contrib/redhat/collectd.spec
ChangeLog: update SPEC file for RPM based distributions
* Remove netstat_udp
* Add infiniband and mdevents
Change-Id: Ib9afd72f37e3bee4e5a7cba216ff11708ba5988f
=> Update RedHat specfile to 5.12.0

configure.ac
ChangeLog: Correct LD flags for some custom library paths
See #3472 for the original issue
=> Fix #3472 - Correct LD flags for various libs

src/ipc.c
ChangeLog: ipc plugin: migration to v6.0
also fix the  number of message queues, change `msginfo.msgmni` by `msginfo.msgpool`
=> [collectd 6] ipc: migration to v6.0

Makefile.am, src/collectd.conf.in, src/collectd.conf.pod, src/ethstat.c, src/ethstat_test.c
ChangeLog: ethstat: ethstat plugin expose ethtool and NIC statistics from sysfs
=> [collectd-6.0] ethstat plugin

src/virt.c
ChangeLog: virt plugin: Add hugetlb_ metrics
Resolves #3932
Co-authored-by: Matthias Runge <mrunge@redhat.com>
=> virt plugin: Add hugetlb_ metrics

.github/workflows/build.yml
* Add "silent" + "keep going" options to MAKEFLAGS
* Add $MAKEFLAGS to all make invocations
* Update "name"s
* Remove ``continue-on-error`` that was temporarily managing some failures
=> [ci][gha] Miscellaneous improvements and sync with cirrus

src/virt.c
ChangeLog: virt plugin: Add hugetlb_ metrics
Resolves #3932
Co-authored-by: Matthias Runge <mrunge@redhat.com>
(cherry picked from commit 8c781279e9c4789936323670b729f9a979c976db)
=> virt: Add hugetlb_ metrics

build.sh
ChangeLog: In ./build.sh: fixed the --datarootdir duplicate in ./config section.
=> Fixed duplicate datarootdir in build.sh

src/write_prometheus.c
ChangeLog: write_prometheus: log which socket creation function failed
To ease debugging of users' listen socket creation failures, see: https://github.com/collectd/collectd/issues/4010
After the change, log message looks like this:
`write_prometheus plugin: Opening a listening socket for [::]:777 failed in bind().`
=> [collectd 6.0] write_prometheus: log which socket creation function failed

src/mmc.c
ChangeLog: mmc plugin: cache file descriptors to reduce udev events generated as side-effect
Hi,
there is a slight annoyance when using the eMMC health info support for Micron and Sandisk chips introduced by me in #4006: an udev event is generated on every call to the read callback.
This is due to to the `watch` option that can be used in udev rules, which is described in the man page as:
>  Watch the device node with inotify; when the node is closed after being opened for writing, a change uevent is synthesized.
This watch option is [enabled by default](https://github.com/systemd/systemd/blob/ef2ad30aee9fa99b0fdb8fe7efda397513cec6af/rules.d/60-block.rules) for all block devices. The intention behind this is to be notified about changes to the partition table. The mmc plugin does however …
=> mmc: cache open file descriptors to block devices

src/write_graphite.c
ChangeLog: write_graphite connection closed message always zero fixed
=> ChangeLog: v5.12 milestone: Fix issue #3127

contrib/README, contrib/exec-borg
ChangeLog: contrib/exec-borg: Add a new exec-plugin script for collecting information about [Borg Backup](https://www.borgbackup.org/) repositories
=> Add new exec-borg script to contrib/

src/daemon/plugin.c
The changes in commit 55efb56a.
wrongly assume that the references passed in to `plugin_register_write()` somehow outlive the spawned write thread.
While this is true for some plugins that pass statically allocated strings and global `user_data_t` structs to `plugin_register_write()` it is not correct for all plugins.
See #4098 for an example of a plugin (`write_http`) mis-behaving due to this.
Store owned versions of the passed values instead. For `user_data` this means the content of the struct and for the name it means a `strdup()`ed version of the string.
This should fix the `write_http` plugin crashing in #4098.
=> src/daemon/plugin.c: don't store references to stack allocated values

src/daemon/plugin.c
ChangeLog: fix uc_update: Value too old errors on metric dispatch
The changes in commit 55efb56a changed the order in which the time and interval on a to-be-dispatched metric family were set and `uc_update()` was called on the metric family.
The time and interval inside a metric family have to be set before calling `uc_update()` on it, otherwise warnings [like these][1] will be generated en masse:
uc_update: Value too old: … value time = 0.000; last cache update = 0.000;
And the "missing" handlers for the metric family will be called resulting in plugins like `write_prometheus` dropping the value, resulting in it not showing up when queried, as mentioned in #4098.
[1]: https://github.com/collectd/collectd/pull/4026#issuecomment-1463884930
=> [collectd 6] src/daemon/plugin.c: init fam.{time,interval} before uc_update(fam) on dispatch

src/mysql.c, src/types.db
mysql plugin: add "questions" metric
ChangeLog: mysql plugin: add "questions" metric
=> add questions metric for mysql plugin

src/collectd.conf.in, src/collectd.conf.pod, src/intel_rdt.c
=> [intel_rdt] Added support for LLC references event

src/swap.c
swap plugin: remove extra call to swap_submit_usage.
ChangeLog: swap plugin: remove extra call to swap_submit_usage.
=> swap plugin: Removed extra call to swap_submit_usage.

Makefile.am, contrib/redhat/collectd.spec
ChangeLog: Update rpm specfile for post collectd-5.12
=> post-5.12.0 redhat specfile fixes

src/utils/curl_stats/curl_stats.c
Use integer based keys for metrics if available.
cURL ≥ 7.55.0 provides additional keys that allow getting certain metrics as integers rather than doubles, e.g. content length. In some newer versions of cURL, the original keys (using doubles) are marked as deprecated.
ChangeLog: cURL, cURL-JSON, cURL-XML, Write HTTP plugins: fix compatibility with new versions of cURL.
=> curl_stats: fix compatibility with new versions of cURL.

.github/workflows/build.yml, .github/workflows/distcheck.yml
This speeds up PR checks significantly.
=> Add new GitHub action for running `make distcheck`.

src/python.c
`PySys_SetArgv` has been deprecated in Python 3.11.
ChangeLog: Python plugin: The initialization logic has been updated to work with Python ≥3.11.
=> Python plugin: use `PyConfig` to set argv.

src/collectd.conf.pod, src/df.c
ChangeLog: df plugin: migration to v6.0
=> [collectd 6] df: migration to v6.0

.cirrus.yml, .github/workflows/build.yml, .github/workflows/distcheck.yml, configure.ac, src/capabilities.c, src/cpu.c, src/gmond.c, src/intel_rdt.c, src/mdevents_test.c, src/netlink_test.c, src/nut.c, src/procevent.c, src/smart.c, src/utils/curl_stats/curl_stats.c, src/valgrind.suppress
*   Disable all unsupported plugins in the `configure` script. They can still be force-enabled with `--enable-foo`.
*   Remove the lists of unsupported plugins from the CI definitions (Cirrus CI and GitHub Actions).
*   Cherry-picks the following fixes from `main`:
*   #4155
*   #4156
*   #4161
*   #4165
*   #4167
*   #4169
*   #4172
*   Fix minor issues in the Capabilities and CPU plugins.
=> [collectd 6.0] Fix the build

src/collectd.conf.in, src/collectd.conf.pod, src/write_log.c
* Remove blank lines from the logging output.
* Add an example config block to `collectd.conf`.
ChangeLog: Write Log plugin: Remove blank lines from output.
=> write_log plugin: Remove empty lines, add example config

src/irq.c, src/utils/common/common.c
ChangeLog: IRQ plugin: Migrated to collectd 6 data structures.
Fixes: #3647
=>  [collectd 6] IRQ plugin: Migrate to collectd 6 data structures. 

src/daemon/metric.h, src/load.c
ChangeLog: Load plugin: Migrated to collectd 6 data structures.
=> [collectd 6] Load plugin: Migrate to collectd 6 data structures.

Makefile.am, README.md, configure.ac, src/collectd.conf.in, src/collectd.conf.pod, src/epics.c
This is initial implementation for EPICS plugin. EPICS is Experimental Physics and Industrial Control System. It is widely used in particle physics and looks like message bus. In order to monitor and record the data distributed over the bus, the plugin is introduced.
Testing considerations:
There is package for debian sid with EPICS https://packages.debian.org/source/sid/epics-base so collectd images can be updated to test building of this plugin.
ChangeLog: Introduce EPICS plugin
Reference: https://epics-controls.org/
=> EPICS plugin

src/lua.c
ChangeLog:  Since vanilla Lua isn't multi-thread-safe, a global lock should be used
when calling their functions. The previous code causes unstable behavior
especially on loading Lua's C modules with both read & write threads.
```
e.g.)
collectd.register_read(function()
require('cqueues')
return 0
end)
collectd.register_write(function()
return 0
end)
```
Note that you need to add the following config to your collectd.conf to
load C modules:
```
<LoadPlugin lua>
Globals true
</LoadPlugin>
```
=> lua: Use a global lock to call Lua's API

src/bind.c, src/collectd-nagios.c, src/cpufreq.c, src/hugepages.c, src/intel_pmu.c, src/mysql.c, src/nginx.c, src/ovs_stats.c, src/processes.c, src/smart_test.c, src/swap.c, src/ubi.c, src/virt.c, src/vmem.c
This imports all changes done to plugins in `main` into the `collectd-6.0` branch. Only plugins that have no changes in the `collectd-6.0` branch are imported. For more information, please see #4186.
=> [collectd 6] Import plugin changes from `main`.

src/daemon/plugin.c, src/daemon/utils_cache.c, src/utils/metadata/meta_data.c
Continuation for PR https://github.com/collectd/collectd/pull/4243, fixing more warnings from ticket https://github.com/collectd/collectd/issues/4241.
(Related also to v5 branch PR https://github.com/collectd/collectd/pull/3970.)
=> [collectd 6]: Fix some GCC "-Wextra" warnings in collectd core

.cirrus.yml
I'm hoping that this helps to debug a task failure in #4238.
=> [collectd 6] ci: .cirrus.yml: Upload `.log` files as artifacts.

src/interface.c
ChangeLog: Interface plugin: Prefer `kstat` over `getifaddrs` to fix the plugin on Solaris.
Fixes: #4240
=> interface plugin: Reorder implementations to put kstat above getifaddrs.

src/memory.c
ChangeLog: memory plugin: The `system.linux.memory.available` metric has been added.
=> [collectd 6] memory plugin: Report the `system.linux.memory.available` metric.

src/swap.c
ChangeLog: swap plugin: The `system.paging.faults` metric has been added.
=> [collectd 6] swap plugin: Add the `system.paging.faults` metric.

src/epics.c
ChangeLog: epics plugin: Fix potential deadlock in the plugin
=> epics: Fix potential deadlock in handle_label_event

src/memory.c
This PR is trying to fix issue #4237 by splitting "available" off from counting the "sum". 
We use flags with names to set all metrics with a `plugin_instance`, the logic is to let only metrics with the same `plugin_instance` should aggregate to count sum by `MEMORY_SUBMIT`.  Except for metrics `plugin_instance` is "OTHERS" (we add a function `memory_submit_single ` to deal with this situation).
With this commit, we can add new metrics easily. For instance, if we want to add a single metric like "Dirty", we can treat it the same way as "available" in this commit. And if we want to add a subset of metrics like "Vmalloc\*", we can add a new flag in `plugin_instance_flags` and then use `MEMORY_SUBMIT(plugin_instance_names[NEW_FLAG], ...`, it is also convenient.
Tests:
```
$cat log …
```
=> memory.c: workaround to let ValuesPercentage works again without "available"

configure.ac, src/processes.c
ChangeLog: processes plugin: The metric schema has been aligned with OpenTelemetry semantic conventions.
=> [collectd 6] processes plugin: Migrate to collectd 6 data structures.

src/daemon/utils_cache.c
ChangeLog: utils_cache: Fix history accumulating
=> [collectd 6] Fix history accumulating in utils_cache

.github/workflows/build.yml
ChangeLog: GitHub Actions: Fix deprecated actions/upload-artifact@v3
=> Fix deprecated actions/upload-artifact@v3 in GitHub Actions

docs/BUILD.dpdkstat.md
ChangeLog: Update DPDK docs link
=> Update DPDK docs link
