- src/bind.c
Seems like it was created due to the copy-paste. Similar loop and check is in the `bind_xml_stats_handle_view`
> bind-plugin: fix zones iteratation upper limit

- src/daemon/plugin.c
- src/daemon/plugin.h
- src/memory.c
- src/swap.c
Currently, `plugin_dispatch_multivalue` works only with 
`gauge_t` metric type. 
Although this function is extremely useful for other other data types.
This commit changes it to accept a "store_type" (one of `DS_TYPE_{GAUGE|COUTNTER|ABSOLUTE|DERIVE}`).
> Change "plugin_dispatch_multivalue" to accept any metric type.

- README
- configure.ac
- src/Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/write_log.c
I find this to be useful when developping new input plugins,
it allows creating a very simple configuration and combined
with `-f` can be used for a very simple workflow.
I'm proposing this, since I think it could be useful for
people wanting to debug their config on local agents as well.
> Add a write_log output plugin which logs values.

- contrib/redhat/collectd.spec
Favor using systemd when installing on EL7, and upstart on EL6. No
changes for EL5. Uses the upstart & systemd config files from
the contrib/ directory.
The sysv initscript used on EL5 is still available in the
collectd-contrib package, for those who prefer using the traditional
init system.
> RPM specfile: switch to using upstart/systemd

- src/ipmi.c
Java uses SIGUSR2 to suspend/resume threads. The OpenIPMI plugins also
need a signal to resume its event loop when setting a timer. They can't
both use the same signal. We ask OpenIPMI to use SIGIO instead.
This should fix #114.
> ipmi: use SIGIO instead of SIGUSR2 to avoid conflict with JVM

- src/write_http.c
This allows multiple destinations to work again (fixes #821), using the
same logic as other write plugins.
The callback name would now be something like:
`write_http/http://example.com/endpoint`
which is not very nice.
The next step would be to change this plugin to use `<Node>` blocks
like many others, and pass the URL as a parameter inside each instance
block. So I see this patch as the minimum required to let 5.3 and 5.4
users use this plugin with multiple destinations.
> write_http: make callback names context-dependent

- src/collectd.conf.in
- src/collectd.conf.pod
- src/write_http.c
This makes the plugin use `<Node>` blocks like most other write plugins,
while maintaining backwards compatibility with `<URL>` blocks.
It's a follow up to #899, which was merely a fix for the release
branches.
It should also make using write_http with filter chains more convenient.
> write_http: deprecate <URL> blocks in favor of <Node>

- configure.ac
Ensure linking is done after compilation of the test program, otherwise
symbols cannot be found. `LDFLAGS` and `CFLAGS` are placed before the
test program on gcc command line while `LIBS` is placed after. Even if
in our case, `LDFLAGS` also contain the lib, being put before the
program while the linking phase is done with the same command leads to
`sg_init()` never found which is misinterpreted as requiring an
argument.
This has been tested with both libstatgrab 0.90 and 0.17.
> libstatgrab: fix detection of libstatgrab >= 0.90

- configure.ac
- src/Makefile.am
Without this configure fails compile its libperl test program because -lperl comes before the test program on the compiler command line.
> libperl's ldopts include libaries and therefore should go in LIBS not LDFLAGS

- src/collectd-python.pod
- src/python.c
PyUnicode_SetDefaultEncoding was removed from the Python source between 3.1 and 3.2. It was never a documented API so I guess I have only myself to blame for this breakage.
https://github.com/collectd/collectd/issues/505
> Fix compiler warnings with Python3.

- src/powerdns.c
Don't look past the end of the array but check the boundary first.
> Powerdns plugin: fix logging on failed lookup

- src/plugin.c
This makes collectd resistant against vulnerable copies of libltdl
(CVE-2009-3736). See <http://bugs.debian.org/559801#15> for further
details.
Thanks to @mahmoudimus for reporting this in #893
> plugin: Use strcasecmp rather than strncasecmp to find a plugin.

- src/utils_latency.c
Summary: statsd histogram to support more than 1 second
Problem: Collectd/Statsd supports configurable percentiles for timers but it limits the value to be 1 to 1000ms. If the timer value is more than 1000ms, it uses for min, max, average,... and drops it for percentile computation.
Solution: Added support for increasing bin width when the value is above histogram's range.
Test Plan: Tested by sending metrics within range and out-of-range (ie above 1000 ms)
Differential Revision: https://all.phab.dev.bloomberg.com/D156454
> statsd histogram to support more than 1 second

- src/ceph.c
As far as I can see it doesn't need any definitions
exposed by this define.
Fixes:
make[3]: Entering directory '/home/ruben/src/collectd/src'
CC       ceph_la-ceph.lo
In file included from /usr/include/stdio.h:27:0,
from ./daemon/collectd.h:34,
from ceph.c:26:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and
_SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
^
cc1: all warnings being treated as errors
Makefile:4120: recipe for target 'ceph_la-ceph.lo' failed
make[3]: *** [ceph_la-ceph.lo] Error 1
make[3]: Leaving directory '/home/ruben/src/collectd/src'
Makefile:5096: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/ruben/src/collectd/src'
Makefile:3142: recipe for target 'all' failed
make[1]: *** …
> Ceph: do not define _BSD_SOURCE

- src/apache.c
- src/ascent.c
- src/nginx.c
- src/write_http.c
CURLOPT_USERPWD chokes on colons inside usernames or passwords, so use
CURLOPT_USERNAME and CURLOPT_PASSWORD if curl 7.19.1 or newer is found.
Follow-up to 0af75dc13 for the rest of the plugins based on libcurl.
> avoid using CURLOPT_USERPWD when possible

- src/apache.c
- src/collectd.conf.pod
Libcurl and curl itself have disabled by default some ciphers by example RC4 from libcurl > 7.34 as you can see  in the following link.
http://curl.haxx.se/mail/tracker-2014-11/0046.html
"curl" tool client can force ciphers with --ciphers option.
With this new option  "SSLCiphers" you can force also any cipher suite from the apache plugin configuration.
take as example:
````
LoadPlugin apache
<Plugin apache>
<Instance "test_0">
URL "https://localhost:440/server-status?auto"
CACert "/opt/collectd/etc/ca-bundle.crt"
SSLCiphers "RC4-SHA"
VerifyPeer false
VerifyHost false
</Instance>
</Plugin apache>
````
> Added SSLCiphers into Instance section to select ciphers from client

- src/apache.c
- src/ascent.c
- src/bind.c
- src/collectd.conf.pod
- src/curl.c
- src/curl_json.c
- src/curl_xml.c
- src/nginx.c
This is a followup to #983. It changes/improves 2 things:
- the default timeout is the effective plugin/plugin instance interval, not the global configured default.
- it accepts `Timeout 0` which disables the timeout completely.
> Curl plugins connection timeout

- src/battery.c
Some battery plugin backends report current, but this was not done yet for the sysfs one. This patch adds support for current reporting through sysfs.
In case the current is not available, it is is possible that ENODEV is reported. For that reason, do not report that situation.
> Report current for Linux battery plugin

- src/write_sensu.c
This allows building with gcc's `-Werror=format-security` flag, which is
enforced when building debian packages.
See https://wiki.debian.org/Hardening
> write_sensu: pass literal string to ERROR() macro

- configure.in
This should make building the java plugin work out of the box at least on current linux distros.
Hopefully this sort of workarounds won't be necessary anymore:
* https://github.com/collectd/pkg-debian/blob/master/debian/rules#L41-L52
* http://pkgs.fedoraproject.org/cgit/collectd.git/tree/collectd.spec#n457
/cc @rubenk as this fishes up one old patch of yours.
> improve java detection/defaults in configure script

- src/write_kafka.c
This is a potential fix for issue 996. Added a new function : kafka_handle() which is called by kafka_write() which invokes rd_kafka_new() and rd_kafka_topic_new(). Access to kafka_handle() is controlled by a mutex. 
This patch also fixes the double-free error mentioned @mfournier in the patch posted in 996 yesterday.
> write_kafka plugin : Create kafka handles from kafka_write callback rather than the config callback

- src/write_sensu.c
Casting counters, derives and abolutes to int64_t was incorrect, as they
are respectively `unsigned long long`, `int64_t` and `uint64_t`.
Apart from potentially loosing precision, the `%ld` format-string made
clang choke on the 32bit architecture (follow-up to 78340212).
> write_sensu: fix format-string portability problem

- version-gen.sh
This breaks PACKAGEVERSION since the -n is left verbatim in the string.
Use the more portable printf instead
> /bin/sh on OSX doesn't understand -n

- src/java.c
- src/liboconfig/oconfig.c
The recursive nature of this function made it difficult to free the root
node of the config tree. Splitting it in 2 allows to work around this
problem.
> oconfig: fix oconfig_free to free all elements

- configure.ac
- src/Makefile.am
Building write_kafka plugin  - bugfix : the path passed via the --with-librdkafka arg was not assigned to CPPFLAGS or LDFLAGS.
> when --with-librdkafka arg is not a path searched by linker

- configure.ac
- src/processes.c
- src/zfs_arc.c
- zfs_arc: Silence errors about failure to read the "l2_size" value from the zfs:0:arcstats kstat. This value is missing on several versions of Solaris.
- processes: Several fixes to make the plugin work on Solaris in 32-bit and 64-bit builds. Enable the plugin by default.
> Fixes for zfs_arc and processes plugins on Solaris

- configure.ac
- contrib/redhat/collectd.spec
- src/Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/turbostat.c
This plugin is based on https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/tools/power/x86/turbostat/turbostat.c
It reads CPU frequency and C-state residency on modern Intel turbo-capable processors.
Here are examples of produced data (using CGP, see https://github.com/Feandil/collectd-turbostat/tree/master/CGP-plugin for the CGP plugin).
Example 1 (Small load):
Example 2 (Big compilation near the end):
> New plugin: turbostat (CPU frequency and C-state residency)

- AUTHORS
- README
- configure.ac
- contrib/redhat/collectd.spec
- src/Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/fhcount.c
- src/types.db
This patch is adding a new plugin called `fhcount` which provides statistics about used, unused and total number of file handles.
> Adding fhcount plugin

- src/processes.c
In Linux read the number of threads from  /proc/pid/status instead of counter the number of files in
/proc/pid/task/*.
> Plugin process: in Linux read the number of threads from   /proc/pid/status

- src/collectd.conf.pod
- src/processes.c
- src/types.db
I added the option ``CollectContextSwitch`` because this it's expensive, we need to open all ``/proc/pid/task/*/status`` of the process to count the context switches.
> Plugin process: collect voluntary  and involuntary context switches.

- src/processes.c
This commit partially revert 30eeeee996124de666f907877f8196e5580101ed
which solved incorrectly the merge conflict
Signed-off-by: Arthur Gautier <baloo@gandi.net>
> processes: revert re-introduction of ps_read_tasks

- src/disk.c
**Robert Viduya** writes:
> Here’s a fixed version of the disk plugin that makes it work under Mac OSX 10.10, and hopefully previous releases.  The original version was looking for the disk name in one dictionary, but it was actually in another.  I suspect at some point, Apple moved the disk name property, but I don’t have any previous releases to check.
> 
> I changed the code to look for the disk name in both dictionaries, so hopefully it’s backward compatible.  I also reorganized the code to try to keep the `CFRelease`s and `IOObjectRelease`s a little more manageable.
> Disk plugin: Fixes for Mac OS X 10.10.

- src/mysql.c
The number of buffer pool page-flush requests is provided as a counter.
> use counter type for Innodb_buffer_pool_pages_flushed

- src/liboconfig/oconfig.c
- src/liboconfig/scanner.l
This should fix / evade errors created by yacc in liboconfig. For the most part, this is switching off unused function checking, because yacc / bison will generate a bunch of functions and not all of them are used. Ignoring those problems in that particular case should be quite harmless I hope.
> Clang fixes

- src/amqp.c
- src/curl_json.c
- src/email.c
- src/filter_chain.c
- src/gmond.c
- src/libcollectdclient/client.c
- src/modbus.c
- src/network.c
- src/ntpd.c
- src/onewire.c
- src/openvpn.c
- src/ping.c
- src/powerdns.c
- src/snmp.c
- src/tail.c
- src/tail_csv.c
- src/ted.c
- src/threshold.c
Fixes all "Dead assignment" errors found by clang's *scan-build* static code analysis in the *collectd-5.4* branch.
> Fix "Dead assignment" warnings (collectd-5.4).

- src/battery.c
- src/nfs.c
- src/onewire.c
Fixes all "Dead assignment" errors found by clang's *scan-build* static code analysis in the *collectd-5.5* branch.
>   Fix "Dead assignment" warnings (collectd-5.5).

- src/collectd.conf.pod
- src/write_redis.c
At the moment it is not possible to add further prefixes to the key when you use write_redis plugin. I've added an option "Prefix" so you can add custom prefixes if you need them.
> Added Prefix Parameter to write_redis plugin

- src/collectd.conf.pod
Also correct the maximum length of the node name.
The callback name is "write_redis/%s" so the maximum
length of a node name is DATA_MAX_NAME_LEN - strlen("write_redis") -1.
> write_redis: fix a few typos in manpage

- contrib/systemd.collectd.service
This may help in migrating from sysvinit to systemd
FWIW We use it to set `PYTHONDONTWRITEBYTECODE 1` so python plugins won't write `.pyc` files after puppet removes them
> Use environmental variables from /etc/sysconfig/collectd

- bindings/perl/lib/Collectd/Unixsock.pm
- bindings/perl/t/01_methods.t
I just noticed a small problem with the Unixsock code I wrote a few months ago:
[On Perls older than 5.14](http://search.cpan.org/~rjbs/perl-5.22.0/pod/perlsub.pod#Localization_of_special_variables), if you called `getval()` while having `$_` aliased to a variable marked Readonly (using Readonly.pm that does some tie magic behind the scenes), `_escape_argument()` would error out with "modification of read-only value attempted". This was due to `local $_` not being thorough enough in stripping the magic off `$_` so the readonly-ness would stay while the variable was localized. The fix is trivial and just makes the little helper sub a bit more verbose.
While I was at it, I also fixed an autoderef in one of the tests that should never have been there in the first place; it causes warnings on …
> Fix Unixsock.pm

- src/Makefile.am
- src/daemon/common_test.c
- src/daemon/utils_subst_test.c
- src/utils_mount_test.c
- src/utils_vl_lookup.c
Without these an undefined `*kc` is reported and kstat symbols are missing.
> Add missing kstat definitions

- configure.ac
Current versions of libganglia don't ship the ganglia-config utility
anymore. Change the configure script to not expect it to be in $PATH and
provide sensible defaults instead.
Fix #1129
> gmond: fix linking against libganglia at build time

- src/daemon/utils_time.h
Add ULL suffix to constant to ensure we get a 64-bit unsigned multiply.
Currently, on 32-bit x86 at least we get incorrect results from cdtime() resulting in an infinite loop, calling the read plugins over and over with no delay inbetween.
> Fix TIMESPEC_TO_CDTIME_T() on 32-bit arch.

- src/statsd.c
When not using StoreRates false, this allows statsd aggregators
to hold on to the absolute count, if needed. This provides a way of dealing with use-cases such as #1282
> statsd: provide a gauge for counters, holding the absolute count.

- src/apache.c
mod_status recently started reporting more statistics. According to
http://www.apache.org/dist/httpd/CHANGES_2.4 `mod_proxy, mod_ssl,
mod_cache_socache, mod_socache_*: Support machine readable server-status
produced when using the "?auto" query string.` for version 2.4.13 onwards.
As we can't assume everything we need will be included in the first 16
lines of output anymore, we now simply scan through the whole output.
> apache: parse whole response, not only the first 16 lines

- src/collectd.conf.pod
- src/mqtt.c
This patch adds TLS support for newer libMosquitto. The following plugin configuration settings are supported:
```
CAfile "ca.pem"                   Enables TLS if set
Certfile "client-cert.pem"                optional
Keyfile "client-key.pem"          optional
TLSversion "tlsv1.2"              optional
Ciphers    "" optional
```	
If `CAfile` is set it must point to a PEM-encoded CA certificate used by the broker. This enables TLS so the `Port` number must be a TLS port on the broker. Optionally, both `Certfile` and `Keyfile` may be set to the paths of a client certificate and password-less PEM-encoded key files respectively. `TLSversion` may be set to specify a specific TLS version (e.g. `tlsv1.2`), but this defaults to whatever the broker uses. Also, optionally, `Ciphers` can be …
> MQTT plugin: Add TLS support

- version-gen.sh
This fixes an issue I see when extracting a collectd
tarball into another git repo (the Fedora collectd rpm one).
In that case version-gen.sh picked up the last tag from the Fedora
repo, which is the wrong one.
> Only run git describe when we're in a git repo

- src/amqp.c
buffer is a char *, not an array, so size_of returns the size
of the pointer.
> amqp: use the right buffer size for sstrncpy

- configure.ac
After all the effort to detect GCRYPT_CPPFLAGS and GCRYPT_LIBS
in previous checks, this check blindly overwrites them, even
if the AM_PATH_LIBGCRYPT macro isn't found.
Also, I think it's better to check for specific functionality in a library
than an explicit minimum version, which we already did.
> configure.ac: remove wrong gcrypt check

- src/processes.c
This is a follow-up to e61f047e.
> processes: initialize cswitch counters on unsupported platforms

- configure.ac
- src/Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/notify_nagios.c
This new plugin sends notifications to *Nagios* as a [Passive Check](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/passivechecks.html).
> notify_nagios plugin: New plugin for writing Nagios passive check results.

- src/daemon/plugin.c
- src/snmp.c
Basically, warn when read threads take a long time reading.
> Read threads timing

- src/varnish.c
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
It might improve code understanding, maintainability and error-proneness.
> Cleaning conditional directives that break statements.

- bindings/java/org/collectd/java/GenericJMXConfConnection.java
- call close() on JMXConnector if JMX connection fails; fixes memory leak
- fix indentation errors
- fix "unchecked" compile warnings
- some refactoring
The memory leak was observed when a previously established org.jboss.remotingjmx connection fails. jstack shows a lot of threads not being cleaned-up. Calling close() on the JMXConnector solves this.
> GenericJMX plugin: memory leak, indent and compile warn fixes

- src/snmp.c
Some interesting MIB are indexed with an IP address (for example,
BGP4-MIB). Make collectd able to use those indexes as instances. Format
the IP as string. IPv6 are usually encoded as Octet String, so, they
should be already supported.
Is the use of dot problematic? When used with graphite, it is a separator. Should I replace with a special dot (unicode) or a dash?
> snmp: accept to use IpAddress for instances

- src/snmp.c
if the first snmp_pdu_create inside the loop returns an error,
we exit the loop with res uninitialized and then call snmp_free_pdu on it.
CID #38037
> snmp plugin: don't read from uninitialized pointer

- .gitignore
Add src/daemon/test_utils_time to .gitignore.
Probably forgotten when introducing db1391aaa66b8b8fad82219494f61f3452441f62
> git ignore src/daemon/test_utils_time

- .gitignore
I did not noticed it in my previous #1403 since i do not always compile the whole collectd source tree, but it sounds like ``test_plugin_ceph``should be added to .gitignore too.
Cheers,
CH
> .gitignore: ignore test_plugin_ceph

- src/daemon/common_test.c
- src/daemon/meta_data_test.c
- src/daemon/utils_avltree_test.c
- src/daemon/utils_heap_test.c
- src/daemon/utils_subst_test.c
- src/daemon/utils_time_test.c
- src/utils_latency_test.c
- src/utils_mount_test.c
- src/utils_vl_lookup_test.c
We need the defines from config.h before
we include <testing.h>, or we get the following error on OmniOS:
make  test_common test_meta_data  test_utils_avltree test_utils_heap  test_utils_time test_utils_subst
gcc -DHAVE_CONFIG_H -I. -I../../src  -I../../src -DPREFIX='"/opt/collectd"'  -DCONFIGFILE='"/opt/collectd/etc/collectd.conf"'  -DLOCALSTATEDIR='"/opt/collectd/var"'  -DPKGLOCALSTATEDIR='"/opt/collectd/var/lib/collectd"'  -DPIDFILE='"/opt/collectd/var/run/collectd.pid"' -DPLUGINDIR='"/opt/collectd/lib/collectd"'  -DPKGDATADIR='"/opt/collectd/share/collectd"'   -Wall -Werror -g -O2 -c -o common_test.o common_test.c
In file included from collectd.h:31:0,
from common.h:31,
from common_test.c:28:
../../src/config.h:1631:0: error: "_FILE_OFFSET_BITS" redefined [-Werror]
#define …
> Fix make check on OmniOS

- configure.ac
The output is quite a long line:
kern.cp_times: 10336 0 9848 499639 7613098 18834 0 11963 115 8101970 16444 0 14368 1672 8100398 17584 0 14149 1358 8099791
And we have no use for the result, we just want to know if the sysctl exists.
> configure.ac: send output of check to /dev/null

- configure.ac
The errors pkg-config returns are not very helpful and they
break our nicely formatted list of found and absent libraries.
Just say that the package can't be found, like we do for the rest
of the packages we need.
> libnotify: Don't output multiple lines of errors

- configure.ac
- src/utils_dns.c
Solaris needed this at one point but since
a621ced we check for ip6_ext without including this
header and that seems to succeed to.
> Remove check for ip_compat.h

- src/redis.c
Making all in daemon
CC       redis_la-redis.lo
redis.c: In function 'redis_handle_info':
redis.c:307:5: error: array subscript has type 'char' [-Werror=char-subscripts]
for(i=0;(*str && (isdigit(*str) || *str == '.'));i++,str++)
^
cc1: all warnings being treated as errors
*** Error code 1
Stop.
make[3]: stopped in /home/ruben/src/collectd/src
*** Error code 1
Stop.
make[2]: stopped in /home/ruben/src/collectd/src
*** Error code 1
Stop.
make[1]: stopped in /home/ruben/src/collectd/src
*** Error code 1
Stop.
make: stopped in /home/ruben/src/collectd
> redis plugin: fix build error on NetBSD

- src/write_riemann_threshold.c
Fixes build on NetBSD:
Making all in daemon
CC       write_riemann_threshold.lo
write_riemann_threshold.c:36:18: fatal error: ltdl.h: No such file or directory
#include <ltdl.h>
^
compilation terminated.
*** Error code 1
Stop.
make[3]: stopped in /home/ruben/src/collectd/src
*** Error code 1
Stop.
make[2]: stopped in /home/ruben/src/collectd/src
*** Error code 1
Stop.
make[1]: stopped in /home/ruben/src/collectd/src
*** Error code 1
Stop.
make: stopped in /home/ruben/src/collectd
> write_riemann: remove unneeded include

- src/write_sensu.c
This fixes a segfault when no `Tag` option is set.
> write_sensu: avoid calling strlen() on variable set to NULL

- src/modbus.c
Having this enabled makes collectd's stdout and stderr very noisy. From
now on, only activate this flag when collectd is built with
--enable-debug.
Thanks to Eric Sandeen for mentioning this problem on IRC.
> modbus: avoid enabling libmodbus's debug flag by default

- src/apache.c
When the server doesn't return `Content-Type: text-plain`, it's a strong
hint that we're not querying the right URL.
Fixes #1170
> apache: warn about possible misconfiguration

- configure.ac
We use some bison-specific extensions so we really need bison, not yacc.
This has bitten a few people before, so make it easier for them.
Bison is only needed when compiling from git, since we ship the generated file
in the tarball. We take this into account by checking for the generated file first.
> configure.ac: detect bison

- src/interface.c
Add `if_dropped` to the metrics reported by the interface plugin.
> Report packets dropped in interface plugin

- src/processes.c
Up to now, we had a mix of `int`, `long` and `pid_t` to represent the
variable part of `/proc/<PID>/status` and friends. This patch
standardizes on `long` on the Linux and Solaris platforms.
The max size of `int` is smaller than the maximum number of processes
current kernels support. `pid_t` is used to ensure portability of
functions such as `getpid()`, which aren't used in this plugin, and
apparently resolves to an `int` on Solaris.
This is a follow up to bb978c1, which triggered a format string issue on
solaris 64 bit.
/cc @coreykosak @dago
> processes: use long for pids on linux and solaris

- src/utils_avltree.c
make[3]: Entering directory '/home/ruben/src/collectd/src/daemon'
CC       utils_avltree.lo
utils_avltree.c: In function ‘rebalance’:
utils_avltree.c:248:20: warning: logical ‘or’ of collectively exhaustive
tests is always true [-Wlogical-op]
assert ((b_bottom >= -1) || (b_bottom <= 1));
^~
utils_avltree.c:258:20: warning: logical ‘or’ of collectively exhaustive
tests is always true [-Wlogical-op]
assert ((b_bottom >= -1) || (b_bottom <= 1));
^~
> utils_avltree.c: fix compiler warning

- src/turbostat.c
turbostat.c: In function ‘delta_thread’:
turbostat.c:460:26: error: declaration of ‘core_delta’ shadows a global
declaration [-Werror=shadow]
const struct core_data *core_delta)
^~~~~~~~~~
turbostat.c:163:4: note: shadowed declaration is here
} *core_delta, *core_even, *core_odd;
^~~~~~~~~~
> Turbostat: fix shadowing issue

- src/zfs_arc.c
> zfs_arc: 'stolen' was removed after FreeBSD 10.2

- src/utils_mount.c
DragonFlyBSD has both vfsstat and fsstat apis.
It lacks ST_NOWAIT however.
The easiest fix is to swap the checks and use getfsstat first.
> Fix build on DragonFlyBSD

- src/write_http.c
slist of http headers require cleanup to avoid
memory leak. See libcurl example:
https://curl.haxx.se/libcurl/c/httpcustomheader.html
> write_http: in cleanup handler free http headers

- src/mysql.c
- src/types.db
The 'mysql_sort' type needs to be splitted.
As documented in http://dev.mysql.com/doc/refman/5.6/en/server-status-variables.html#statvar_Sort_range , 'Sort_*' keys are:
* The number of sorts:    Sort_range, Sort_scan
* The number of sorted rows: Sort_rows
* The number of merge passes: Sort_merge_passes
These are cannot be mixed together into one type 'mysql_sort'. 
Proposed patch solves this problem.
https://github.com/collectd/collectd/commit/7d1ee33e6e2250ab6c52be935c897ad8141fdea4
> mysql plugin: Split 'mysql_sort' type into several types.

- contrib/collection3/lib/Collectd/Graph/Common.pm
At present graph.cgi is extremely slowly on servers with large numbers of
RRD files.  This is because it issues an unnecessary stat() call to _every_
RRD file on the local system before loading and rendering graph data.
Patch originally from:
http://mailman.verplant.org/pipermail/collectd/2011-May/004519.html
The patch was improved so that it correctly handles multiple hostnames.
I'm seeing a 5x improvement in speed, the original patch creator
had a 24x speedup.
> Collection3: Graphing speed improvements with many hosts

- src/disk.c
@delphij I believe these values are roughly equivalent to the values collectd submits for Linux.  *io_time* is mapped to FreeBSD's **sb** and *weighted_io_time* FreeBSD's **tsvc_t** from `iostat -x -I`.
They are interesting because they are effectively monotonic counters from boot.
> Submit FreeBSD disk IO time

- src/collectd.conf.pod
- src/daemon/meta_data.c
- src/daemon/meta_data.h
- src/target_set.c
Hello,
This patch allows to set metadata with filters and `target_set` target.
It adds a new keyword `MetaDataSet`.
Example : 
```
<Target "set">
MetaDataSet "key1" "value1"
MetaDataSet "key2" "value2"
</Target>
```
Note : this patch adds some functions to the daemon/meta_data.c in order to clone_and_merge meta data. I prefered to share my new functions instead of implementing them in target_set.c.
Regards,
Yves
> Added MetaDataSet to target_set

- src/utils_cmd_putval.c
Suppress putval responses when output is STDOUT, which in the past had been expected to be /dev/null. Addresses debug messages of #664.
This appears to be working on my system for the past day---the only place fh is set to stdout is in exec.c, where we want this message suppressed. I admit I do not understand what is going on in amqp.c, but this patch will not affect the behavior there, since fh is set to STDERR instead.
> Suppress spammy debug messages of #664

- src/collectd.conf.pod
fb67910d documented the new syntax.
The old syntax does no longer work, remove it.
> Remove broken filter syntax from collectd.conf(5)

- src/network.c
https://gcc.gnu.org/onlinedocs/gcc/Pointer-Arith.html
gcc will assume sizeof(void) == 1 when doing pointer arithmetic on
void*s, but other compilers may not.
> Fix void* arithmetic warning (-Wpointer-arith)

- src/collectd.conf.in
- src/collectd.conf.pod
- src/write_http.c
This commit allows the addition of arbitrary headers into the POST requests.  The code is taken (and adapted) from the curl plugin.
> add http headers functionality to write_http plugin

- src/write_kafka.c
This is in preparation for allowing compiling/running against recent rdkafka releases found in recent distros.
> write_kafka: do not call depreciated functions unless necessary

- configure.ac
- src/Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/xencpu.c
Hi,
I wrote a new simple plugin that collects statistics about physical CPU load under XEN.
Tested on Centos5  with Xen-3.4, Debian 7 with Xen-4.1.
> xencpu plugin: RFC release

- src/collectd.conf.pod
- src/sensors.c
Adds an option UseLabels to configure how sensor readings are reported. The default reports readings using the sensor name (e.g. "in0"). With this option set to true, the readings are reported using the label (e.g. "VCore").
A similar patch has been sent to the mailing list ([by Jakob Haufe sur5r@sur5r.net in 02/2010](http://mailman.verplant.org/pipermail/collectd/2010-February/003588.html)) but never got merged.
This version adds the UseLabels configuration option as suggested in the review.
> sensors: Report sensor readings by descriptive labels

- bindings/perl/lib/Collectd/Unixsock.pm
Collection3 scripts generates commands of huge length when many files needs to be flushed.
This causes errors in web-server logs like this:
index.cgi: FLUSH failed: Parsing options failed. at ../lib/Collectd/Graph/Common.pm
And errors from collectd like this:
collectd[1243]: unixsock plugin: failed to write to socket #8: Broken pipe
Proposed patch splits FLUSH to separate commands. We have used this in production for a long time, and I think it will be useful for others too.
> * Collectd::Unixsock: Split messages sent by flush() to 1024 byte chunks to not overflow buffer in unixsock.c us_handle_client().

- src/collectd.conf.pod
- src/processes.c
Fixes #1284. Rebased version of #1508.
This emits this warning once at startup time:
```
[2016-01-12 22:25:10] [warning] processes plugin: this platform has a 15 character limit to process names. The `Process "a very very long process name"' option will not work as expected.
```
> processes: warn about process names above OS limit

- src/daemon/collectd.c
- src/daemon/configfile.c
- src/daemon/plugin.c
- src/daemon/plugin.h
I have really come to appreciate the -T command line option for testing to see if my collectd is working as configured. However, I noticed that, as written, the only errors that get propagated to the exit status of collectd are errors from the ```read``` callback of the configured plugins. In my opinion it would be more valuable if it reported errors that happened in other stages as well. In this way it would be a more faithful end-to-end test.
After this change, the following kinds of errors will cause ```collectd -T``` to exit with an abnormal status:
1. errors reading the config file
2. errors reading ```types.db```
3. errors on ```plugin_init```
4. errors on ```plugin_read``` (as now)
5. errors on ```plugin_shutdown```
**Note:** this PR causes collectd to do more error checking than …
> Modify the -T command line option so it watches for more errors.

- src/write_kafka.c
Ensure that we don't break when no key is provided.
> write_kafka: reliability when no key provided

- src/apcups.c
- src/collectd.conf.pod
This PR fixes core problem of #617 and reverts fb075e15e3400afdb691b88f1e1a4a38578aaba9 which causes problem, described in #1607.
> apcups plugin: Change "PersistentConnection" option default value depending on poll Interval.

- src/disk.c
disk plugin: Initialize udev context only once, not per each read
disk plugin: Call disk_udev_attr_name() only when UdevNameAttr configured
> Disk plugin: UdevNameAttr feature improvements

- configure.ac
With libatasmart  but w/o libudev:
```
./configure
...
smart . . . . . . . . no 
...
./configure --enable-smart
...
smart . . . . . . . . no (dependency error)
...
```
> Fix for #1688 The SMART plugin does not build/load, v.5.5.0

- src/collectd.conf.pod
- src/utils_db_query.c
Hi!
Proposed patches adds ability to set plugin instance from query.
This feature is useful for generic plugins.
Example:
````
<Query instance_summary>
Statement "SELECT 'summary' as instance,\
sum(numbackends) as numbackends, \
sum(xact_commit) as xact_commit, \
sum(xact_rollback) as xact_rollback, \
sum(blks_read) as blks_read, \
sum(blks_hit) as blks_hit, \
sum(tup_returned) as tup_returned, \
sum(tup_fetched) as tup_fetched, \
sum(tup_inserted) as tup_inserted, \
sum(tup_updated) as tup_updated, \
sum(tup_deleted) as tup_deleted \
FROM pg_stat_database"
PluginInstanceFrom "instance"
#TODO: types should have '_summary' suffix
<Result>
Type "pg_numbackends"
ValuesFrom "numbackends"
</Result>
#
<Result>
Type "pg_xact"
InstancePrefix "commit"
ValuesFrom "xact_commit"
</Result>
<Result> …
```
> Postgresql plugin: set plugin instance from query results.

- src/perl.c
* lock base thread interpreter in perl_init() too, to avoid race conditions with c_ithread_create() called from threads of already-initialized plugins. (with deadlock when perl_log() called from perl_init() detection)
* Fix coredump due to destroying interpreter on thread running perl.
See #1706 for comments.
> Perl plugin fixes for #1706

- src/disk.c
Introduced by bdbc066 so no need to backport.
CID 116311
> Plug a memory leak in disk plugin

- src/valgrind.FreeBSD.suppress
- testwrapper.sh
Valgrind reports an invalid read in common.c:parse_value. The error is
supposed to happen in strlen() on a just previously strdup()ed string.
Possibly, this is some sort of alignment issue. The read size is reported to
be 4 on a buffer of size 3.
https://bugzilla.redhat.com/show_bug.cgi?id=678518 may also be related.
> Valgrind: Suppress a bogus invalid read on FreeBSD.

- src/daemon/collectd.c
- src/daemon/collectd.h
- src/daemon/configfile.c
- src/daemon/configfile.h
This replaces 09fb81e130ad70bf0547cec3d3c349ce8cb092cf which provided a specific solution for the `PIDFile` option. The new solution is generic and more nicely abstracted without the need for global variables across multiple modules.
Fixes #366
> daemon: Let all command line options override global options from the config.

- src/daemon/utils_cache.c
- src/daemon/utils_cache.h
In file included from common.c:37:0:
utils_cache.h:76:1: warning: function declaration isn’t a prototype
[-Wstrict-prototypes]
uc_iter_t *uc_get_iterator ();
^
> uc_get_iterator: use ansi function declaration

- contrib/redhat/collectd.spec
The [spec file for
librdkafka](https://github.com/edenhill/librdkafka/blob/master/packaging/rpm/librdkafka.spec)
calls its package 'librdkafka-devel', not 'rdkafka-devel'. Searching the
web for 'rdkafka-devel RPM' turns up nothing, all the RPMs are named
'librdkafka-devel'.
> rdkafka is called librdkafka

- src/collectd.conf.pod
- src/smart.c
This option enables the smart plugin to use disks that libatasmart mistakenly
reports as asleep.  This happens because libatasmart has not been updated to
incorporate support for newer idle states in the ATA spec.
> smart plugin: add IgnoreSleepMode option to ignore sleeping disks

- src/write_riemann.c
- src/write_riemann_threshold.c
Fixes #1782
CC       write_riemann_la-write_riemann.lo
In file included from ./daemon/collectd.h:31:0,
from write_riemann.c:34:
./config.h:1664:0: error: "_FILE_OFFSET_BITS" redefined [-Werror]
#define _FILE_OFFSET_BITS 64
^
In file included from /usr/include/limits.h:17:0,
from
/opt/csw/lib/gcc/i386-pc-solaris2.10/5.2.0/include-fixed/limits.h:168,
from
/opt/csw/lib/gcc/i386-pc-solaris2.10/5.2.0/include-fixed/syslimits.h:7,
from
/opt/csw/lib/gcc/i386-pc-solaris2.10/5.2.0/include-fixed/limits.h:34,
from /opt/csw/include/protobuf-c/protobuf-c.h:200,
from /opt/csw/include/riemann/proto/riemann.pb-c.h:7,
from /opt/csw/include/riemann/attribute.h:21,
from /opt/csw/include/riemann/riemann-client.h:23,
from write_riemann.c:31:
/opt/csw/lib/gcc/i386-pc-solaris2.10/5.2.0/include-fixed/sys/feature_t …
> Fix write_riemann plugin build on 32-bit Solaris

- src/ntpd.c
When STA_NANO is set in ik->status, then results are
expressed in nanoseconds (instead of microseconds by default).
Signed-off-by: Matwey V. Kornilov <matwey.kornilov@gmail.com>
> ntpd: Check STA_NANO in the server status

- src/collectd.conf.pod
- src/smart.c
Since a device name (e.g., /dev/sda) can change, allow using the serial number
to store SMART data as this will ensure the data for a given drive is always
kept together.
> smart plugin: add option to store data using serial number

- src/disk.c
Fixes a core dump induced by freeing a wrong pointer when UDEV alt_name was not allocated (for some reason) earlier
> disk plugin: release udev-based name. Fixes #1781

- src/write_kafka.c
Otherwise, partition is selected solely on the first letter of the
key. If all your hosts are starting with the same letter, everything
ends up in a single partition.
cc @pyr
> write_kafka: ensure key is properly hashed to select partition

- src/redis.c
- src/types.db
Added the following metric:
```
instantaneous_ops_per_sec: Number of commands processed per second
```
with key `operations_per_second`, type `gauge`.
> Added 'operations_per_second' (redis) type

- src/network.c
Instead, report an error and let plugin initialization fail.
> network plugin: Don't abort() if gcrypt initialization failed.

- src/network.c
Emilien Gaspar has identified a heap overflow in parse_packet(), the
function used by the network plugin to parse incoming network packets.
This is a vulnerability in collectd, though the scope is not clear at
this point. At the very least specially crafted network packets can be
used to crash the daemon. We can't rule out a potential remote code
execution though.
Fixes: CVE-2016-6254
(cherry picked from commit b589096f907052b3a4da2b9ccc9b0e2e888dfc18)
> network plugin: Fix heap overflow in parse_packet().

- src/varnish.c
Not all config options are valid for all versions of Varnish. Rather
than removing the if-clause altogether, which results in a "Ignoring
unknown configuration option" warning, print a user-friendly warning
instead.
Fixes: #1790
> varnish plugin: Add informative warnings to the config handling.

- contrib/redhat/collectd.spec
On very minimal build centos machines the yum-builddep should install
all it needs to succesfully build on centos, but this misses which and
so python cant be found.
> collectd.spec: el7 fails to find python without which

- src/collectd.conf.in
- src/collectd.conf.pod
- src/interface.c
This PR adds ActiveInterfaceOnly to interface plugin. 
Rationale: In Sailfish devices there are very many network interfaces (28 in Nexus 4) out of which only 3 are actually used: one for cellular data, one for WIFI, and lo. Unfortunately, active interfaces on different devices could be different leading to inability to enable only the active ones using Interface option for all devices in default configuration. So, users would have to find out which interface is active for them and enable these interfaces manually.
By adding ActiveInterfaceOnly option, only interfaces with packet count larger than 0 would be reported. The implementation has been tested on Linux (Sailfish), but I hope that it works on other platforms as well.
> add ActiveInterfaceOnly option to interface plugin

- configure.ac
Upcoming changes will requires C99 support.
For newer compilers this is the default, but older
compilers needs a flag like -std=gnu99 or -std=c99.
> Require a compiler that understands C99

- configure.ac
This PR addresses the issue described in #1238 , #966, #872 and ( I think ) proposes a more flexible solution than #1120 
This makes the DATA_MAX_NAME_LEN a compile time tunable by exposing it in the ```./configurate``` script
Example usage:
```
./configure --with-data-max-name-len=1024
```
The default value remains 64 chars, but allows users that need larger sizes to easily change the value without the need of patching.
> make DATA_MAX_NAME_LEN a compile time tunable

- src/network.c
- src/plugin.c
I have hopes that this fixes #1110, but I'd welcome some testers because I'm not sure how reliably this can be reproduced.
> src/plugin.c: Stop write threads before calling shutdown callbacks.

- src/pyvalues.c
This affects data-sets with more than one data-source of different types.
Previously, the type of the first data-source would have been used to convert
all values.
> python plugin: Fix conversion of value-lists from Python to C.

- src/collectd-python.pod
This man page just describes the python plugin so it shouldn't contain
generic information for developers.
> collectd-python(5): remove NOTES section

- src/Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/utils_format_json.c
- src/utils_format_json.h
- src/utils_format_json_test.c
- src/write_http.c
This patch implements POSTing of notifications to a configurable URL.
It implements the alert format used by [prometheus/alertmanager](https://github.com/prometheus/alertmanager) (the *dev* branch) which looks like this:
```json
[{
"labels": {
"alertname": "collectd_cpu",
"instance":  "host.example.com",
"severity":  "FAILURE",
"service":   "collectd",
"cpu":       "0",
"type":      "wait"
},
"annotations": {
"summary": "..."
},
"startsAt": "2015-12-02T10:33:08.451491682+0100"
}]
```
> write_http plugin: Implement sending of notifications.

- configure.ac
CC       perl_la-perl.lo
In file included from /usr/include/stdio.h:27:0,
from ./daemon/collectd.h:34,
from perl.c:36:
/usr/include/features.h:331:4: error: #warning _FORTIFY_SOURCE requires
compiling with optimization (-O) [-Werror=cpp]
^~~~~~~
cc1: all warnings being treated as errors
Makefile:4439: recipe for target 'perl_la-perl.lo' failed
make[3]: *** [perl_la-perl.lo] Error 1
ccflags contains the flags used to compile libperl itself, not the ones
needed for compiling code that uses it. Switch to perl_inc which just
returns the neccesary include flags
Fixes #1858
> perl : fix build without compiler optimization

- configure.ac
- src/Makefile.am
While we're doing that, look for a version less than 0.4, since we don't support that yet (#1574)
> sigrok: use pkg-config to find library

- src/cpython.h
Fixes #1852
duplicate symbol _ValuesType in:
.libs/python_la-python.o
.libs/python_la-pyconfig.o
duplicate symbol _NotificationType in:
.libs/python_la-python.o
.libs/python_la-pyconfig.o
duplicate symbol _ConfigType in:
.libs/python_la-python.o
.libs/python_la-pyconfig.o
duplicate symbol _UnsignedType in:
.libs/python_la-python.o
.libs/python_la-pyconfig.o
duplicate symbol _SignedType in:
.libs/python_la-python.o
.libs/python_la-pyconfig.o
duplicate symbol _PluginDataType in:
.libs/python_la-python.o
.libs/python_la-pyconfig.o
duplicate symbol _ValuesType in:
.libs/python_la-python.o
.libs/python_la-pyvalues.o
duplicate symbol _NotificationType in:
.libs/python_la-python.o
.libs/python_la-pyvalues.o
duplicate symbol _ConfigType in:
.libs/python_la-python.o
.libs/python_la-pyvalues.o …
> python plugin: fix building on OSX

- src/snmp.c
If you have multiple Instance values that are empty string,
they all end up in the same rrd file, resulting in:
rrdc_update (/collectd/rrd/vc3/snmp/if_errors.rrd, [1352632188:0:0], 1) failed with status -1
Fixes #176
> snmp : don't send values for empty type_instance

- configure.ac
- src/Makefile.am
The old way of detecting libpython was unreliable and did not work on
OS X.
Instead use python-config which was introduced in python 2.6.
For older versions of python you can still set PYTHON_CPPFLAGS and
PYTHON_LDFLAGS on the ./configure command line.
By default we look for python3-config, python2-config and last
python-config. The path to python-config can be overriden by setting
PYTHON_CONFIG.
Fixes #888 and #27
> Switch to python-config for libpython detection

- src/daemon/common.c
- src/daemon/common.h
- src/write_graphite.c
- src/write_riemann.c
- src/write_sensu.c
- src/write_tsdb.c
Up to now, collectd fails to notice when a remote server dies without properly closing the network connection, leading to more and more memory getting allocated as the values pile up in the write queue. This patch serie aims to help collectd identify this scenario and let the error handling code paths kick in.
I split this up to be able to cherry-pick bits to the release branches (I do consider collectd triggering the OOM killer as a bug :wink:)
The function name has no explicit reference to keepalive because I'd also like to add a global configure option to enable & tweak the socket close lingering (giving control on if and how collectd drops unflushed data at shutdown time). This part would be targetted to the next feature release.
TODO: check if plugins which have their network socket …
> Enable TCP socket keepalive on write plugins

- src/utils_latency.c
Currently, utils_latency.c code allows only to increase hystogram bin width.
When any spike arrives, bin_width can raise too high and it never decreases later, unless collectd restarted.
Proposed patch allows bin width to be reduced to required level.
Submitting @octo as author of utils_latency.c code.
> statsd, utils_latency: allow to reduce bin width

- src/ceph.c
- src/daemon/common.c
- src/daemon/common.h
- src/dns.c
- src/exec.c
- src/iptables.c
- src/ping.c
- src/turbostat.c
A few plugins historically required collectd to be run as root. Capabilities offer a way to control more precisely the privileges given to the collectd process, depending on which plugins are loaded.
My goal to start with, is simply to help the user configure his system to run collectd with reduced privileges. Once we've got a bit more experience with this, it would be nice to have collectd drop the unneeded capabilities itself, depending on which plugins are loaded.
So this hasn't been thoroughly tested yet, I just wanted to pass it through jenkins, and get some feedback about the idea.
Also, I'm sure more plugins than just these 6 require privileges.
> Add capabilities checking to plugins needing privileges

- src/utils_format_json_test.c
Solaris 10 defines label_t in /usr/include/sys/machtypes.h,
unless POSIX_C_SOURCE is defined, or when __EXTENSIONS__ is defined.
Fixes #1301
> Work around Solaris 10 defining label_t

- configure.ac
Right now, if you have the xfs development headers installed,
they will be picked up. Add an option to disable this behaviour.
Fixes #1878
> Add an option to disable building with XFS support

- src/collectd.conf.in
- src/collectd.conf.pod
- src/grpc.cc
The config mimicks the *network plugin*, i.e. it looks something like this:
```
<Plugin grpc>
<Server "example.com" "50051">
</Server>
</Plugin>
```
The SSL option names have been copied from the Apache webserver, the option names of the `Listen` block have been changed to match.
> gRPC plugin: Implement sending of metrics.

- AUTHORS
- README
- configure.ac
- contrib/redhat/collectd.spec
- src/Makefile.am
- src/collectd-lua.pod
- src/collectd.conf.in
- src/collectd.conf.pod
- src/daemon/plugin.h
- src/lua.c
- src/utils_lua.c
- src/utils_lua.h
This is a squashed version of #1861, which should make the diff a bit easier to review.
I changed a few things compared to the original work from 2010:
- It now works with Lua 5.2 and 5.3
- The BasePath is prepended to Lua's package.path
- The exported functions are in a Collectd module (aka table).
- Added a few logging functions, so collectd.log_info, collectd.log_error etc.
- Return as many errors as possible to Lua, so they can be caught.
I removed the filtering callbacks for now since I haven't had time to test them. We can always add them back later. I hope you don't mind @schmurfy. Also kept you as the author of the commit and added you to AUTHORS.
> Add a Lua plugin for Collectd

- src/utils_dns.c
utils_dns.c: In function ‘handle_ip’:
utils_dns.c:531:29: warning: pointer of type ‘void *’ used in arithmetic
[-Wpointer-arith]
memcpy(buf, (void *) ip + offset, len - offset);
^
> utils_dns.c: fix compiler warning

- configure.ac
- src/write_riemann.c
riemann_client_set_timeout() was added in 1.8.0, but this
version hasn't landed in all distro's yet.
Fixes #986
> support older versions of riemann-c-client

- README
- configure.ac
- src/Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/hugepages.c
- src/types.db
Plugin that allows stats for hugepages to be collected.
Change-Id: Ide5ff31c54206cf5ee3d6155899bd53e8edae7bd
Signed-off-by: Jaroslav Safka <jaroslavx.safka@intel.com>
Signed-off-by: Kim Jones <kim-marie.jones@intel.com>
Signed-off-by: Maryam Tahhan <maryam.tahhan@intel.com>
> hugepages plugin: a stats plugin for hugepages

- src/python.c
If AfterFork is called after threads have been initialized.
Also handle SIGTERM while reading from an interactive session slightly more gracefully.
> python plugin: Fixing possible problems with the GIL.

- proto/collectd.proto
- src/grpc.cc
This is done to use a naming closer to that of the *unixsock* and *exec plugins*.
> grpc plugin: Rename "DispatchValues" to "PutValues".

- src/utils_mount.c
backport of commit 225ee7bb45152c51c1c9508b2e776cef36d2682d for collect-5.5 branch.
> 5.5: Fix compilation against >=xfsprogs-4.7.0

- src/collectd.conf.pod
- src/target_replace.c
This allows using Target:Replace to transform metadata values. It also adds a new DeleteMetaData option to allow conditionally deleting metadata keys whose value matches the regex.
> Allow Target:Replace to manipulate metadata.

- src/onewire.c
Actually print error messages, return value from OW API is either 0 or -1 - not very informative.
(This is redoing of pull request #1911 with comments addressed; sorry for creatine new PR)
> onewire plugin - improve error messages

- src/amqp.c
- src/apache.c
- src/curl_json.c
- src/curl_xml.c
- src/dbi.c
- src/java.c
- src/lua.c
- src/memcached.c
- src/modbus.c
- src/mqtt.c
- src/mysql.c
- src/netapp.c
- src/openldap.c
- src/python.c
- src/routeros.c
- src/snmp.c
- src/tail.c
- src/tail_csv.c
- src/varnish.c
- src/write_graphite.c
- src/write_kafka.c
- src/write_mongodb.c
- src/write_redis.c
`user_data_t` is one of those structs where we used to create a variable just for a single function call. This patch inlines these cases into the function call using a compound literal.
> Tree wide: Use user_data_t compound literal where appropriate.

- src/collectd.conf.in
- src/collectd.conf.pod
- src/utils_format_graphite.c
- src/utils_format_graphite.h
- src/write_graphite.c
The Collectd naming hierarchy often contains multiple levels with duplicate naming. For example, the CPU plugin uses the string "cpu" for both plugin and type (when `ValuesPercentage false`), leading to Graphite metrics with redundant components:
`example_host.cpu.0.cpu.idle`
Other examples include both the Load plugin and Memory plugin which use the same plugin and type name:
`example_host.load.load.shortterm`
`example_host.memory.memory.cached`
This new option drops the latter of these fields when it duplicates a previous metric component.
> write_graphite plugin: add option DropDuplicateFields

- src/collectd.conf.pod
- src/daemon/meta_data.c
- src/daemon/meta_data.h
- src/target_set.c
This uses the syntax from Target:Notification to allow interpolating field and metadata values via Target:Set. It also adds a new DeleteMetaData option to allow deleting metadata keys.
> Allow Target:Set to delete metadata and interpolate field values.

- src/collectd.conf.in
- src/collectd.conf.pod
- src/hugepages.c
- src/types.db
This PR implements three new options for the *hugepages plugin*:
*  `ValuesPages` (enabled by default) reports the number of used and free *pages* as `vmpage_number`.
*  `ValuesBytes` (disabled by default) reports the number of used and free *bytes* in hugepages as `memory`.
*  `ValuesPercentage` (disabled by default) reports the *percentage* of used and free hugepages as `percentage`.
All options can be enabled / disabled independently from each other so users can gather the metrics in the form(s) they need.
This PR also does a fair bit of refactoring that the actual feature implementation depends on. Sorry about that.
> hugepages plugin: Implement the Values{Pages,Bytes,Percentage} options and refactoring.

- src/daemon/common.c
If strjoin() runs out of buffer space when joining strings, use the
remainder of available space rather than skipping additional strings.
> Truncate strjoin arguments if > DATA_MAX_NAME_LEN

- bindings/perl/lib/Collectd.pm
- src/collectd-perl.pod
- src/perl.c
This PR moves perl plugins registration from perl plugin level to collectd level.
So, perl plugin read/write callbacks can be called multithreaded (in parallel), not in single thread, as it was before. Also no callbacks are called by collectd unless some perl plugin registers that callback.
These changes are mostly backward-compatible for perl plugins, with only difference for `flush` operation.
Before that, all perl plugins was 'invisible' by Collectd core, all callbacks was from 'perl' plugin.
So, to make explicit flush, one should flush 'perl' plugin. After this patch, each perl plugin is registered at Collectd level with its own name, so calls to flush `perl` plugin needs to be changed to flush that plugin name as it was registered by perl plugin code. I see no problem in this, …
> perl plugin: new implementation with plugin_register_complex_read() and so.

- src/collectd.conf.pod
- src/daemon/utils_time.c
- src/daemon/utils_time.h
- src/postgresql.c
"Zulu" time is always in UTC and the timezone part is just a 'Z'.  This is a pretty common form, and it is a requirement of the Google Stackdriver metric ingestion API.
This PR adds a couple of functions alongside the existing RFC3339 ones (the latter use local time instead of UTC and give the timezone in the +hh:mm form).
thanks
> Add RFC3339 Zulu time functions

- src/daemon/common.c
- src/daemon/common.h
By using fgets in parse_value_file, this PR fixes #1941.
In addition, parse_value_ext is introduced that simplifies the debugging of the issues raised in this function. It allows to add comment string that is printed as a part of INFO or other messages. It allowed me to find which file was responsible for garbage errors when used together with parse_value_file
> use fgets in parse_value_file, fixes #1941

- AUTHORS
- src/hddtemp.c
- src/lvm.c
The hddtemp plugin imposes a 32-drive and 1024-byte limit on the response from the hddtemp daemon.  On my system, the 1024-byte limit truncates the response after 29 drives.
Drop the drive limit and increase the buffer limit to 1 MB.  (This is hopefully larger than anyone will need, and prevents collectd from being DoSed by the hddtemp daemon.)
> hddtemp: Support more than 32 drives

- src/dpdkstat.c
Signed-off-by: Taras Chornyi <tarasx.chornyi@intel.com>
> dpdkstat: Fixed issue with unused var when configured w/o debug

- src/Makefile.am
write_graphite doesn't have anything to do with json. This seems to have
been accidentally added in 30c1111.
Fixes https://bugs.debian.org/839771
> write_graphite: remove linking against libyajl

- src/collectd.conf.in
- src/collectd.conf.pod
- src/memcached.c
Added new option "Address".
We use separate Memcached instances per project on single server.
Each project has its own IP in 127.0.0.0/8 and each Apache or Memcached instance binds to appropriate IP on standard 80 and 11211 ports. Check for "localhost" or "127.0.0.1", as it now implemented in `memcached` plugin, is not suitable for us. Our internal patch was reworked to be applied to current `master` branch and proposed to review and merge.
Superseedes: #905
> memcached: Added Address option

- README
- configure.ac
- src/Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/intel_rdt.c
- src/rdtmon.c
- src/types.db
The **rdtmon** plugin collects information provided by monitoring features of Intel Resource Director Technology (Intel(R) RDT) like Cache Monitoring Technology (CMT), Memory Bandwidth Monitoring (MBM). CMT monitors last level cache occupancy (LLC). MBM supports two types of events reporting local and remote memory bandwidth. Local memory bandwidth (MBL) reports the bandwidth of accessing memory associated with the local socket. Remote memory bandwidth (MBR) reports the bandwidth of accessing the remote socket. Also this technology allows to monitor instructions per clock (IPC).
All events are reported on a per core basis. Monitoring of the events can be configured for group of cores.
Plugin uses PQoS library for Intel(R) RDT. <https://github.com/01org/intel-cmt-cat>
> RDT monitoring plugin

- src/vserver.c
Cf. https://sourceware.org/ml/libc-alpha/2016-02/msg00093.html
> Use readdir() instead of the deprecated readdir_r().

- src/daemon/common.c
AIX doesn't have MSG_DONTWAIT define as MSG_NONBLOCK in common.c
This fix is similar to MSG_NONBLOCK in src/pinba.c and src/statsd.c
> commom: Fixed AIX doesn't have MSG_DONTWAIT

- src/processes.c
* Remove unused fields from structures
Fields cpu_user, cpu_system, vmem_minflt, vmem_majflt are always equal to zero for new entries (which are passed to ps_list_add()).
Values of these fields are not used in `procstat_t` entries too. So, that can be safely removed.
* Fix counters initialization / spikes
processes plugin generates spikes on (re)start. That is caused by wrong counter logic: When collectd (re)started, monitored processes, which was started before collectd, already have non-zero values in cpu_user/cpu_system/vmem_minflt/vmem_majflt, so `want_init` is false. What causes spike. 
At other hand, processes which are started between read cycles, should be fully accounted without initialization. So, we must skip only first cycle for these counters.
I think this is a bug, so, If …
> Processes plugin: improvements / fixes

- src/nginx.c
As documented in http://nginx.org/en/docs/http/ngx_http_stub_status_module.html , nginx provides following status information:
accepts -   The total number of accepted client connections. 
handled -   The total number of handled connections. 
The 'handled', as noticed, is the same as 'accepts' unless some resource limits have been reached (for example, the worker_connections limit). 
In normal state, these values are equal. When an error occurs, the difference between these values appear, but rate of this difference is too small (compared with the number of accepted connections) to see it on graphs.  So, it does not useful to provide pure 'handled' metric, but 'failed' (failed=accepts-handled) should be provided instead. Such 'failed' metric also allows to configure notifications, based …
> Nginx plugin: Incorrect metric provided

- src/Makefile.am
- src/aggregation.c
- src/amqp.c
- src/daemon/common.c
- src/daemon/common.h
- src/daemon/plugin.h
- src/daemon/plugin_mock.c
- src/daemon/utils_cache_mock.c
- src/exec.c
- src/testing.h
- src/unixsock.c
- src/utils_cmd_flush.c
- src/utils_cmd_flush.h
- src/utils_cmd_getthreshold.c
- src/utils_cmd_getval.c
- src/utils_cmd_getval.h
- src/utils_cmd_listval.c
- src/utils_cmd_listval.h
- src/utils_cmd_putval.c
- src/utils_cmd_putval.h
- src/utils_cmds.c
- src/utils_cmds.h
- src/utils_cmds_test.c
- src/utils_vl_lookup.c
- src/utils_vl_lookup.h
- src/utils_vl_lookup_test.c
- src/valgrind.FreeBSD.suppress
- src/write_kafka.c
The idea is to reuse the parser not only in the backend but also in client tools.
Using it for collectdctl is currently blocked by #1748.
> Add a generic parser for the text protocol

- configure.ac
- src/daemon/Makefile.am
- src/daemon/common.c
capget(2) is Linux specific and the use of the raw syscalls is
discouraged. Also, there have been interesting crashes on some systems.
Issue: #2009
> src/daemon/common.c: Rewrite check_capability() using cap_get_bound().

- src/openvpn.c
When plugin loaded without configuration, it starts to spam logs with message
'read-function of plugin `openvpn' failed'.
Related issue: #1932
> openvpn: Fixed openvpn_read() on empty configuration.

- src/zfs_arc.c
I accidentally added prefetch_metadata_misses in 61635f3 but we
already had that metric.
Fixes #1963
> zfs_arc: remove double metric

- configure.ac
The sort order of the `find` command proves to be dependent on external
factors, which makes `./configure` pick different java versions on
different systems, making the whole build non-reproducible (see
https://reproducible-builds.org/ for more details).
Adding a call to `sort`, with the locale forced, fixes this issue.
Fixes: #1523
> configure.ac: make finding java deterministic

- src/modbus.c
The previous version failed on FreeBSD with:
modbus.c: In function 'mb_read_data':
modbus.c:476:21: error: storage size of 'sockaddr' isn't known
struct sockaddr sockaddr;
^
> modbus plugin: Avoid sizeof(struct sockaddr).

- configure.ac
- src/write_kafka.c
Use `rd_kafka_set_logger()` only when `rd_kafka_conf_set_log_cb()` is not
available:
write_kafka.c: In function 'kafka_handle':
write_kafka.c:119:6: error: 'rd_kafka_set_logger' is deprecated (declared at /usr/local/include/librdkafka/rdkafka.h:2400) [-Werror=deprecated-declarations]
rd_kafka_set_logger(ctx->kafka, kafka_log);
^
Fixes: #2029
> write_kafka plugin: Fix support for librdkafka 0.9.0.

- configure.ac
- proto/Makefile.am
- proto/prometheus.proto
- src/Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/write_prometheus.c
This new plugin embeds an HTTP server that can be scraped from _Prometheus_, similar to the way _collectd_exporter_ works. The metric family names and labels are created in the same manner as _collectd_exporter_ so this plugin can function as a drop-in replacement.
> write_prometheus plugin: New plugin for exposing metrics to Prometheus.

- bindings/perl/lib/Collectd/MockDaemon.pm
- bindings/perl/lib/Collectd/Unixsock.pm
- bindings/perl/t/01_methods.t
I just noticed that at some point the unixsock module's reporting of fractional seconds broke `Collectd::Unixsock::listval_filter` as the regexp for the data lines didn't match any more so nothing was returned. This fixes this bug.
Also updated the mock daemon to provide realistic values (with fractional parts and without in turn so as to test compatibility with both) and fixed some indentation to use all tabs as the rest of the module does.
> Fix Collectd::Unixsock

- src/collectd.conf.pod
- src/turbostat.c
Added boolean and updated documentation to reflect new config option. 
Fixes #1974
> Turbostat Plugin - Add config boolean for logical CPU naming

- src/Makefile.am
Since being pulled out of the core daemon, the daemon no longer provides
all the required symbols for these shared objects. The "tail", "match"
and "tail_match" utils need to be compiled in explicitly. Also, we need
to link with the liblatency.la convenience library for the
"Distribution" handling in the "match" util.
Issue: #2067
> src/Makefile.am: Fix dependencies for the "tail" and "match" utilities.

- docs/README.virt.md
- src/Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/daemon/Makefile.am
- src/daemon/plugin_mock.c
- src/virt.c
- src/virt_test.c
After the discussion in https://github.com/collectd/collectd/pull/2037 , here's the same code implemented on top of the existing codebase.
As explained in https://github.com/collectd/collectd/pull/2037 , we are considering to switch to collectd in oVirt for monitoring hosts and libvirt domains in future releases.
We can't just neglect to monitor all the domains if one fraction thereof is unresponsive, so we need to enhance the monitoring code to work with that.
We will implement that on top of the more generic domain tag/partition approach I implemented here.
This patch required some refactoring, but I tried to keep this minimal.
I choose to upload few patches to make the review easier, but I have zero problems squashing them.
More code could be backported from …
> Add support for virt domain tags

- src/daemon/utils_random.c
- src/daemon/utils_random.h
- src/write_kafka.c
Previously, negative numbers would be truncated to `ffffffff` by the buffer length on architectures where longs are 64 bit.
Fixes: #2074
> write_kafka plugin: Use 32bit random number when formatting a random key.

- configure.ac
- src/Makefile.am
- src/apple_sensors.c
- src/daemon/Makefile.am
- src/daemon/collectd.h
- src/daemon/common.c
- src/disk.c
- src/libcollectdclient/collectd/client.h
- src/libcollectdclient/network_buffer.c
- src/multimeter.c
- src/network.c
- src/ntpd.c
- src/ted.c
- src/write_mongodb.c
This fixes a lot of stuff in configure.ac, mainly:
- Quote m4 macros consistently
- 2 space indents
- Indent all the macros in the same way
- Remove redundant checks
- Limit certain checks to only run on certain platforms
- Remove a lot of unused AC_DEFINE and AM_CONDITIONAL calls
- Order some stuff around
- Fixes some checks that didn't actually check anything, i.e. libesmtp.
- Removed some checks for headers that are in std C89/99
Still to do is to remove all calls to $PKG_CONFIG --exists with PKG_CHECK_MODULES macros, but I think this patch set is big enough as it is.
> More autoconf work

- contrib/docker/rootfs_prefix/.gitignore
- contrib/docker/rootfs_prefix/rootfs_prefix.c
- No need to declare errno
- Remove one level of indentation
> contrib/docker: cleanup wrapper a bit

- src/processes.c
- src/tcpconns.c
All the hard work from jca@, i'm only proxying the patches already commited in our ports-tree in http://marc.info/?l=openbsd-ports-cvs&m=148087062627664&w=2
Dunno if `kvm_getfiles()` could be properly detected within configure, but as jca@ figured out, NetBSD can't use that codepath as "their `struct kinfo_file` doesnt have some needed members" (or something..)
> Fix processes and tcpconns plugins on OpenBSD

- src/intel_rdt.c
- Use pqos callback to redirect pqos library messages to collectd output.
- Monitoring groups fail to start when intel_rdt plugin has unpredictably stopped without unsubscribing from the pqos library. Reset pqos monitoring groups registers after pqos library is initialized.
> intel_rdt: fix plugin based on new version of libpqos

- src/virt.c
If we use more than one reader instance, we can spot errors like
this in the system logs:
Dec 12 09:59:24 $HOST collectd[19338]: reading number of
domains: invalid connection pointer in virConnectNumOfDomains
Dec 12 09:59:24 benji.rokugan.lan collectd[19338]: read-function of
plugin `virt-2' failed. Will suspend it for 20.000 seconds.
This causes unnecessary delay in the sampling of libvirt.
The reason for this is just one instance (always #0) takes care
of establishing the libvirt connection.
But this could be done safely in the plugin init callback: according
to doc, this function is called at least once before all the read
instances.
> virt plugin: Open connection on init()

- src/virt.c
Only one virt reader instance should take care of connection
handling (connection/disconnection) to avoid races and plugin
data corruption, potentially crashing collectd.
This bug cannot be triggered with instances=1 (default settings).
> virt plugin: handle disconnect on inst#0

- src/daemon/configfile.c
For the network plugin, this was changed in ac73c75aed7 (which landed in 5.6)
which was a backward incompatible change breaking user configuration. Adding
support back in a central location ensures a more consistent behavior across
plugins. At the same time, we issue a warning message that this behavior is
deprecated.
GH #2083, #2098
> configfile: Reintroduce support for boolean string config values.

- src/netlink.c
Monitoring drops is very handy to see drop rate of qdisc/class (to adjust length of queue and to estimate how much data are exceeding limit), and in some cases to limit interface drops that doesn't reach ethstat and other statistics.
> netlink plugin: Adding support of drops value monitoring

- src/battery.c
We call strstripnewline on it, which expects a null-terminated string.
CID #158524
> Battery plugin: nul-terminate buffer

- Makefile.am
- README
- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/mcelog.c
Plugin for collecting machine check exceptions  reported by [mcelog ](http://www.mcelog.org/)
The plugin at current stage does the following:
• Checks mcelog server liveliness, reports a failure if it’s not running of if it fails.
• Retrieve Memory Corrected and Uncorrected Errors from mcelog Unix socket (client protocol)
• Publishes collected data as notifications and statistics(values)
> mcelog plugin 

- src/zfs_arc.c
Linux seems to have changed the layout of the statistics file. The first commit skips the first two lines of the file as they contain two headers and no statistics. The second commit removes the "other_size" gauge for Linux because it is not available (anymore).
> zfs_arc updates for linux

- Makefile.am
- configure.ac
- docs/BUILD.dpdkstat.md
- src/collectd.conf.in
- src/collectd.conf.pod
- src/dpdkstat.c
- src/utils_dpdk.c
- src/utils_dpdk.h
This patch contains rework of existing dpdkstat plugin. Changes are focused on
extracting common dpdk related features into utils file that could be reused by
other DPDK plugins. Also some related structural changes are introduced.
List of changes:
- introduction of new utils_dpdk.c that handles child process spawning,
and terminating, messaging between parent and child, DPDK configuration
and initialization and DPDK commands execution
- DPDK EAL specific options put into separate subsection of
dpdkstat configuration
- documentation update
Those changes are preparatory steps for upstreaming dpdkevent plugin
that is going to collect DPDK ports and logical cores status info.
Signed-off-by: Krzysztof Matczak <krzysztofx.matczak@intel.com>
> dpdkstat plugin rework

- src/ovs_events.c
- src/utils_ovs.c
- Fixed FreeBSD compilation issue:
```
src/utils_ovs.c: In function 'ovs_db_event_thread_init':
src/utils_ovs.c:895:25: error: assignment makes pointer from integer without a cast [-Werror]
pdb->event_thread.tid = -1;
^
src/utils_ovs.c: In function 'ovs_db_event_thread_destroy':
src/utils_ovs.c:942:25: error: assignment makes pointer from integer without a cast [-Werror]
pdb->event_thread.tid = -1;
^
src/utils_ovs.c: In function 'ovs_db_poll_thread_init':
src/utils_ovs.c:948:24: error: assignment makes pointer from integer without a cast [-Werror]
pdb->poll_thread.tid = -1;
...
```
- Fixed CLANG warnings:
"-Wsign-compare, -Wtautological-compare"
```
src/utils_ovs.c:934:29: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
if (pdb->event_thread.tid < …
```
> ovs_events: fix #2127

- Makefile.am
The chrony plugin uses the `pow()` math function so it needs to be built with `-lm`. Otherwise collectd crashes with `symbol lookup error: /usr/lib/collectd/chrony.so: undefined symbol: pow`.
> chrony: add missing build flag

- Makefile.am
unixsock_la_LIBS is not being processed by automake and thus being incorrectly linked. This results in an symbol error when loading the module. Changing unixsock_la_LIBS to unixsock_la_LIBADD fixes this on my system (Fedora 25).
Error message:
> Jan 14 01:15:18 fedora collectd[20351]: dlopen ("/home/piotr/collectd/lib/collectd/unixsock.so") failed: /home/piotr/collectd/lib/collectd/unixsock.so: undefined symbol: handle_getthreshold. The most common cause for this problem is missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
> unixsock.so: undefined symbol: handle_getthreshold -> link unixsock against libcmds

- contrib/systemd.collectd.service
- src/collectd.conf.pod
Intel RDT plugin is using model-specific registers (MSRs), which require an additional capability to be enabled if collectd is run as a service.
Signed-off-by: Przemyslaw Szczerbik <przemyslawx.szczerbik@intel.com>
> collectd.service: add intel_rdt plugin capability requirement

- contrib/redhat/collectd.spec
Update version in redhat rpm spec file to fix error building rpm package for 5.7.1 version.
> Fix rpm spec file for 5.7.1

- src/collectd.conf.in
- src/collectd.conf.pod
- src/virt.c
We want to export more disk stats, like disk_time.
To do so, we must use the virDomainBlockStatsFlags API, but it
could not be available on all the platforms collectd supports.
To cope with that, we add a minimal layer around the API, and
we use virDomainBlockStatsFlags only if available.
This patch adds the code to use the new API and the fallback code
in the case the platform' libvirt is too old.
> virt plugin: support virDomainBlockStatsFlags

- src/dpdkstat.c
This patch fixes parsing of metrics' types. Some statistics, such as
rx_q0errors, rx_q0bytes or rx_q0packet, don't contain suffix _errors, _bytes or
_packets. This has caused them to use generic type 'derive', rather than
more specific one, for instance 'if_rx_errors'. Additionally, some
statistics contain string 'error', rather than 'errors'.
Signed-off-by: Przemyslaw Szczerbik <przemyslawx.szczerbik@intel.com>
> dpdkstat: Fix metrics' types

- src/collectd.conf.in
- src/collectd.conf.pod
- src/dpdkstat.c
Fix the shared memory object name so that it's configurable. This way multiple
DPDK applications running in containers can be monitored at the same time
(assuming collectd is also running in that container).
Signed-off-by: Maryam Tahhan <maryam.tahhan@intel.com>
> dpdkstat: fix fixed shared mem object name

- src/collectd.conf.in
- src/collectd.conf.pod
- src/virt.c
Add a metric to report physical cpu consumed by the hypervisor,
split per user/system time. This is provided by libvirt since version
0.9.11, and used by oVirt.
We also extend the newly-added 'ExtraStats' option to allow
users to toggle on/off the new metric. Default is off.
> virt plugin: Add physical cpu reporting

- bindings/java/org/collectd/java/GenericJMXConfValue.java
AtomicIntegers are used to address some concurrency problems in Java, and this is advised by some metrics libraries like Netflix's servo:
https://github.com/Netflix/servo/wiki#jmx
Unfortunately, the GenericJMXConfValue.java class is not able to get the values from such types, hence this PR.
I scanned the Java doc for the Java package:
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/package-summary.html
I think I have not forgotten any types.
Tests: tested at runtime
> Java bindings - Adding Atomic* support

- src/collectd.conf.in
- src/collectd.conf.pod
- src/ovs_events.c
Added new `DispatchValues` config option to the plugin to make the dispatching of link status value configurable. Also, the sending notification option is enabled by default.
> ovs_events: Make dispatch link status configurable

- src/dpdkstat.c
- src/utils_dpdk.c
- src/utils_dpdk.h
This change forces dpdkstat plugin to check if memory needs to be resized on
every DPDK_CMD_GET_STATS command, rather than resizing it only once at
initialization. Additionally it fixes incorrect metric retrieval logic, which
allows plugin to dispatch metrics only if number of retrieved extended statistics
is equal to allocated stats array size for port. Based on DPDK API documentation
rte_eth_xstats_get (and rte_eth_xstats_get_names) function can return positive
value lower than array size, which isn't considered a failure.
If primary DPDK process is restarted with a greater number of ports bound to
DPDK driver while collectd dpdkstat plugin is running, then memory isn't resized.
Due to insufficient memory allocation dpdkstat plugin is unable to gather metrics
from new ports. …
> dpdkstat: fix retrieval of statistics

- Makefile.am
- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/dpdkevents.c
Dpdkevents plugin collects and reports following events from DPDK based
applications:
- link status of network ports bound with DPDK
- keep alive events related to DPDK logical cores
In order to get link status plugin forks child process that attaches itself to
DPDK application as secondary DPDK process and fetches link status data using
DPDK API. This is the same approach like for dpdkstat plugin, also the same
utils_dpdk.c helper is utilized.
For getting keep alive events plugin communicates with DPDK application
via shared memory area. This is possible only if keep alive feature
is implemented in monitored application.
More details can be found under link
http://dpdk.org/doc/guides/sample_app_ug/keep_alive.html
Minimal required version of DPDK is 16.07.
Change-Id: …
> Plugin for getting DPDK ports link status and keep alive events.

- src/daemon/common.c
- src/daemon/common.h
So it seems #2010 broke `check_capability()`. Reading `cap_get_bound(3)` doesn't really enlighten me on the purpose and use of this function. But the fact is, the way it was used in `check_capability()` always returned 1, whatever the effective capabilities were set to.
I came accross https://github.com/maximk/diod-ether/blob/master/tests/misc/tcap.c which's author was smart enough to decipher the manpage, and I rewrote `check_capability()` based on his code.
From what I tested, the function now works as expected:
```
$ getcap /opt/collectd/sbin/collectd
/opt/collectd/sbin/collectd =
$ /opt/collectd/sbin/collectd -T
option = ReadThreads; value = -1;
Created new plugin context.
[info] plugin_load: plugin "ping" successfully loaded.
[info] plugin_load: plugin "write_log" successfully …
```
> daemon/common.c: Fix check_capability() by using cap_get_proc()

- Makefile.am
- README
- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/ovs_stats.c
OVS stats plugin uses OVS utils to get available
bridge/interface statistics from OVSDB.
Change-Id: Iabe71d64fef7fdbfd5a272c3599a92bce2adf055
Signed-off-by: Mytnyk, VolodymyrX <volodymyrx.mytnyk@intel.com>
> ovs_stats: Implement OVS statistics plugin.

- configure.ac
On EPEL6:
src/daemon/common.c: In function 'check_capability':
src/daemon/common.c:1571: error: implicit declaration of function 'CAP_IS_SUPPORTED'
make[1]: *** [src/daemon/common.lo] Error 1
> Check for the CAP_IS_SUPPORTED macro

- src/ovs_stats.c
Increase devname buffer to ensure that snprintf output would not be truncated before the last format character
Fix for #2201 
Signed-off-by: Taras Chornyi <tarasx.chornyi@intel.com>
> ovs_stats: Increase devname buffer

- src/ovs_stats.c
- src/utils_ovs.c
src/utils_ovs.c:366:20: warning: Access to field 'type' results in a dereference of a null pointer (loaded from variable 'jval')
(int)(jval)->type);
^~~~~~~~~~~~
...
> ovs_events: fixes issue #2205

- src/collectd.conf.in
- src/collectd.conf.pod
- src/ovs_events.c
Right now, the plugin dispatches values by default and doesn't send any notification messages. The expected behaviour of the event plugin is to send notification by default. So, changed default value of
SendNotification & DispatchValues options to opposite.
> ovs_events: change configuration option defaults

- configure.ac
The OvS plugins haven't been tested/validated on other platforms than Linux platform. Thus, disabling unsupported platforms in the configure file.
This fixes #2203
> ovs: enable only supported platforms (#2203)

- src/processes.c
After a bb0000acfc57e230fc1c26099bc7acb913680f1a an extra pse.cpu_system statement was left in the AIX / elif HAVE_PROCINFO_H section, which causes the compilation to fail.
Noticed by @tbendiksen in https://github.com/collectd/collectd/pull/1981#issuecomment-283597731
bb0000acfc57e230fc1c26099bc7acb913680f1a was merged before collectd-5.7, so this PR is against 5.7 branch.
> processes plugin: Fix broken compilation on AIX

- docs/BUILD.dpdkstat.md
Dpdkstat plugin  documentation  updated with init/reinit duration info.
> dpdkstat: doc updated with initialization time notice

- src/dpdkstat.c
If "EnabledPortMask" option is not set
all DPDK ports will be monitored.
Signed-off-by: Taras Chornyi <tarasx.chornyi@intel.com>
> dpdkstat: Enable all ports by default.

- src/collectd.conf.in
- src/collectd.conf.pod
- src/utils_format_kairosdb.c
- src/utils_format_kairosdb.h
- src/write_http.c
Support attributes on write_http module specificly on kairosdb format.
> Add support for 'Attribute' option on KAIROSDB output format

- src/collectd.conf.in
- src/collectd.conf.pod
- src/processes.c
The `procstat_entry_s` used in improper way.
Added new type and simplified the code - removed unneeded assignments and values copying.
> processes plugin: Code cleanup + add per-process open files count

- src/network.c
When correct 'Signature part' is received by Collectd, configured without
AuthFile option, condition for endless loop occurs due to missing increase
of pointer to next unprocessed part.
Closes: #2174
CVE:  CVE-2017-7401.
> network plugin: Fix endless loop DOS in parse_packet()

- src/collectd.conf.in
- src/collectd.conf.pod
- src/types.db
- src/virt.c
Extend virt plugin functionality to support new statistics:
- Performance monitoring events
- Domain state & reason
- Percentage CPU usage
- CPU pinning (affinity)
- Disk errors
- File system information
- Job statistics
Leverage recently added 'ExtraStats' logic to allow user to enable or disable new metrics.
Plugin decodes domain state and reason enum values to human-readable string format, which will make it easier to interpret notifications.
Known limitation:
Missing CPU utilization metric is expected in some cases. In order to compute %CPU, we require 2 samples of CPU time. However, connection to libvirt is periodically refreshed, by default every 60 seconds. This interval can be changed with RefreshInterval virt plugin configuration option. Whenever connection is refreshed, we lose …
> virt: add support for new metrics

- src/collectd.conf.in
- src/collectd.conf.pod
- src/utils_format_kairosdb.c
- src/utils_format_kairosdb.h
- src/write_http.c
Had a new option for the kairosdb ouput format.
TTL let you sets the Cassandra ttl for the data points.
> Kairosdb ttl support

- src/redis.c
This PR adds support for keys count to redis plugin.
Currently redis plugin collects statistics about redis server but doesn't care about databases usage.
This patch simply add parsing of following lines 
```
db0:keys=4,expires=0,avg_ttl=0
db1:keys=5581,expires=0,avg_ttl=0
db12:keys=3,expires=0,avg_ttl=0
```
Note that `expires` and `avg_ttl` are not parsed.
Resulting identifiers will be like
```
<server>/redis-<node>/records-0
<server>/redis-<node>/records-1
<server>/redis-<node>/records-12
```
> redis: adding support for keys count per database

- configure.ac
- src/bind.c
FreeBSD doesn't provide the `extern long timezone`, presumably because it's "only" an XSI extension, leading to a portability issue with the previous approach.
`timegm()` is a non-standard function available in GNU's and BSD's libc which is doing exactly what we need. The previous code is left as a fallback.
Fixes: #1268
> bind plugin: Use timegm() to convert to time_t if available.

- configure.ac
- src/nut.c
> configure.ac: Remove empty else-block from AC_CHECK_LIB.

- src/utils_cmd_putval.c
`vl.values` was allocated outside of the loop and then copied into each `ret_putval->vl[]`. This means that later values overwrote the values stored in previous `ret_putval->vl[]`.
> src/utils_cmd_putval.c: Fix multi-value PUTVAL.

- src/write_prometheus.c
Calling `realloc(ptr, 0)` is undefined. Call `free()` explicitly.
Thanks to clang's scan-build for pointing this out.
> write_prometheus plugin: Fix incorrect use of realloc().

- src/perl.c
The av2notification_meta() function updated it's parameter by doing
(*m) = malloc();
Afterwards, if an error occurred, it would call `free(*m);` and (potentially)
return, leaving an invalid pointer stored in `m`. The caller would then try to
free the returned pointer because it was non-NULL.
This patch fixes this by doing several code cleanups:
*   The meta argument is not updated unnecessarily. Instead, a local variable
is allocated and used within the loop and only on success is the return
pointer updated.
*   Introduce additional local variables instead of re-using the `tmp` variable
multiple times.
*   Name the variable pointing to the end of the linked list appropriately
`tail` and remove one level of indirection. Reading code that is using
pointers to pointers is unnecessarily hard. …
> perl plugin: Fix potential double-free.

- src/chrony.c
- src/types.db
These are fixes for some issues I noticed on a machine operating as a stratum-1 server using chrony. One commit changes the time_offset value to use the last measured offset from the source report instead of current estimated offset from the sourcestats report. I think that's what most users are interested in monitoring, but if @bbczeuz or anyone else thinks the sourcestats offset would still be useful, I can rework the patch to add a new type instead.
Is there a guideline on renaming values of existing plugins, which would break compatibility? If there is interest, I think we could try to reduce the number of types specific to this plugin and maybe make the naming a bit more consistent.
> chrony plugin bug fixing

- Makefile.am
- configure.ac
- m4/ax_compare_version.m4
This change fixes builds using automake 1.11.  
As far as I can tell, automake 1.12 changed the java timestamp files from classdist_noinst.stamp to classnoinst.stamp.  This change adds a version check to configure.ac to set a variable (JAVA_TIMESTAMP_FILE) that is used in Makefile.am to select which timestamp file is used.  In order to do the version checking, I used AX_COMPARE_VERSION documented at https://www.gnu.org/software/autoconf-archive/ax_compare_version.html
> fix build on automake 1.11

- contrib/redhat/collectd.spec
This plumbs the configuration for the snmp_agent plugin through the RPM spec.
> allow configuration of snmp_agent in rpm builds

- src/curl_json.c
- src/curl_json_test.c
Previously, keys had a "magic" as their first member which was used to differentiate between the two types when they were returned from the binary search tree.
This patch creates a new struct, cj_tree_entry_t, which includes an enum identifying which union member is valid.
I have to admit I'm a bit on the fence on this one. It feels more "correct" but unfortunately isn't as readable as I'd hope it to be. Thoughts?
> curl_json plugin: Refactor the way trees/keys are stored.

- src/snmp_agent.c
This patch resolves compilation issue of snmp_agent plugin which appears on last 3 PRs. This issue appears due to Net-SNMP v5.4.3 installed on the collectd CI systems.
> SNMP Agent: Fix compilation issue of snmp_agent plugin

- src/openldap.c
This prevents collectd from segfaulting when the ldap session setup
fails before opening a connection to openldap (syntax error in the URL
option for example).
> openldap: check ld structure before passing it to ldap_unbind()

- src/collectd-snmp.pod
As described at http://net-snmp.sourceforge.net/dev/agent/structsnmp__session.html,  `peername` field of `snmp_session` structure, and, as result, `Address` option of Collectd `snmp` plugin configuration, may include transport specifier and/or port number. 
Examples of transport specifier are here: http://net-snmp.sourceforge.net/docs/man/snmpcmd.html
I haven't check how it works with TCP transport, but at least it tries to connect by TCP.
Configuration examples are updated too.
Closes: #2302
> snmp plugin: Option `Address` documented in more details.

- src/write_riemann.c
Since [0.2.13](https://github.com/riemann/riemann/releases/tag/0.2.13), Riemann supports microseconds time resolution. riemann-c-client supports it since [1.10.0](https://github.com/algernon/riemann-c-client/blob/master/NEWS.md).
This PR adds microseconds resolution in write_riemann.
I tested it locally, example event received by Riemann with my PR:
```
INFO [2017-06-13 21:20:04,058] defaultEventExecutorGroup-2-1 - riemann.config - #riemann.codec.Event{:host foo.bar, :service processes/ps_state-paging, :state nil, :description nil, :metric 0.0, :tags nil, :time 1.497381604056424E9, :ttl 20.0, :plugin processes, :type ps_state, :ds_name value, :type_instance paging, :ds_type gauge, :ds_index 0}
```
without my PR:
```
INFO [2017-06-13 21:22:03,810] defaultEventExecutorGroup-2-2 - …
```
> Add micro-seconds resolution in write_riemann

- src/apache.c
- src/ascent.c
- src/bind.c
- src/curl.c
- src/curl_json.c
- src/curl_xml.c
- src/nginx.c
- src/write_http.c
Issue: #2328
After redirect received, Collectd send subsequent requests to new location.
That is wrong - Collectd should use configured URL for all poll cycles, regardless of the responses received previously.
Problem was caused by https://github.com/curl/curl/issues/1631. To avoid that when old `libcurl` version used, we set request url in each poll cycle.
> curl plugins: Use configured URL for all poll cycles

- src/collectd.conf.in
- src/collectd.conf.pod
- src/dpdkevents.c
- src/dpdkstat.c
- src/utils_dpdk.c
- src/utils_dpdk.h
This PR contains the following fixes:
- dpdkevents: detect primary DPDK application (re)start
- dpdkevents: initialization fixes
-  dpdk plugins: bug fixes and improvements
> Feat dpdkevents fixes

- src/apcups.c
Previously the apcups plugin could not be used without defining
an explicit configuration.
While the apcups plugin did provide a localhost fallback, it
did not however provide a 3551 port fallback in practice,
eventhough a constant for that purpose was already present.
Thanks to Pascal de Bruijn for report.
Supersedes: #2347
> apcups: allow to use plugin without explicit configuration

- src/ipc.c
Compilation fail caused by typo in 2761915bed8c6caea41018be3e675aa712cc0b0a / #1842.
This change already released since collectd-5.6.0 and collectd-5.7.0, so PR created against 5.6.
I have checked that commit by eyes and found no another occurences of such typo.
Issue: #2305 
CC @rubenk
> Fixed failed compilation on AIX

- src/collectd.conf.pod
- src/snmp_agent.c
List of changes:
* Added comments into code;
* Fixed possible race conditions between thread start and locks initialization. Lock initialization should be done before starting pthread;
* Added missing `llist_destroy()` calls;
* Added a check for `llist_create()` success;
* Fix null pointer dereference (Issue #2338);
* Changed plugin initialization:
* Do not start working thread if plugin not configured.
That allows to avoid useless CPU consumption by polling loop.
* Do not register 'write' / 'missing' callbacks if there was no `<Table>` configured.
These callbacks do not do anything in this case.
* Registration of 'shutdown' callback delayed to 'init' phase.
* Documented `PluginInstance` option.
> snmp_agent: Fixes and improvements

- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/nut.c
Changes:
* Implemented use of 'plugin_register_complex_read', so querying will be multi-threaded;
* Added 'ConnectTimeout' option, implemented with use of 'upscli_tryconnect()' added in nut-2.6.2;
The `upscli_connect()` used before is a blocking function.
* The `upscli_cleanup()` should be called only at Collectd shutdown, excessive calls was removed;
* Added `upscli_init()` call if `ForceSSL` enabled.
* Added a check for duplicates in `UPS` option.
Some useful notes:
* upscli_list_next() has internal hardcoded read timeout of 5 seconds.
* Nut old releases can be downloaded here: http://pkgs.fedoraproject.org/repo/pkgs/nut/
* http://networkupstools.org/docs/man/upsclient.html
Issue: #2344
> nut plugin: Multi-threaded ups polling with connect timeout.

- src/processes.c
- src/types.db
Collectd reports `/proc/PID/io` fields `io_rchar/io_wchar` as `ps_disk_octets` type and `io_syscr/io_syscw` as `ps_disk_ops` type.
The names of these types do not match values they represent. 
1) For `io_rchar/io_wchar` data type should be named as `ps_io_octets`. In Linux, these values represent any I/O of process, not disk I/O only: they include sockets, pipes, console I/O, etc.
The `ps_io_octets` type can be added in addition to the existing `ps_disk_octets` for which values can be obtained from `read_bytes/write_bytes` of /proc/PID/io. These values will be much more correct for reporting as `ps_disk_octets` than existing `io_rchar/io_wchar`. Please note what `read_bytes/write_bytes` is _real_ disk I/O, it does not account file I/O from cache.
2) For `io_syscr/io_syscw` correct type …
> processes: Show real disk IO in addition to process IO (Linux only)

- src/intel_pmu.c
Fixed compilation errors. ssnprintf() was not replaced to snprintf() while merging intel_pmu plugin to master branch.
> intel_pmu: fix compilation error caused by migration to snprintf().

- src/network.c
@rubenk, please merge this.
The issue appeared in 3e2272cea52a2dace364c82fbcfeecf9dd9fbd34 (#1735) which is merged to 5.6, so rebased to that branch.
Thanks.
> network: Fix free() before use

- src/apache.c
- src/daemon/plugin.c
- src/memcached.c
- src/openldap.c
- src/perl.c
- src/routeros.c
- src/snmp.c
- src/tail_csv.c
Citation from Collectd wiki (https://collectd.org/wiki/index.php/User_data_t):
> If the callback is deleted or callback registration is failed, the struct is freed using the my_config_free function.
There are several functions which register callbacks and has `user_data_t` argument:
- `plugin_register_write(), plugin_register_log(), plugin_register_notification(), plugin_register_flush()` - which calls `create_register_callback()`.
- `plugin_register_complex_read()`, which implemented in other way.
Most of plugins expects what free() will happen if registration failed.
For first functions group, in case of failure, `create_register_callback()` calls `destroy_callback()` which frees userdata.
But there was no code in `plugin_register_complex_read()` for userdata free.
That code was added, …
> Free `userdata` if plugin_register_complex_read() has failed.

- src/collectd.conf.in
- src/collectd.conf.pod
- src/mcelog.c
For mcelog's unix socked data source (default /var/run/mcelog-client), mcelog plugin generates collectd notifications that merge both corrected and uncorrected memory error info. This is incorrect behaviour. Separate notifications should be created for each category and also severity should be differentiated. This pull request fixes this.
This pull request also updates the mcelog plugin to only distpatch notifications for memory corrected and uncorrected errors when the value changes for each dimm and implements a persist option if you wish to continuously send notifications.
> Feat mcelog notification bugfixes

- proto/types.proto
- src/daemon/utils_cache.c
- src/daemon/utils_cache.h
- src/grpc.cc
As mentioned in #2370, I've added metadata support to the GRPC plugin. In order to do this, I also had to add the `uc_iterator_get_meta` function for getting metadata out of a cache iterator.
I'm still relatively inexperienced in C/C++, so let me know if there are any changes I should make to be more idiomatic.
> Add metadata support to GRPC plugin

- Makefile.am
- configure.ac
To detect cflags and libs use the sometimes provided pkg-config for
libdpdk. That avoids build errors on systems where special flags are
needed and provided by dpdk via pkg-config, but not yet considered by
the collectd build system.
This closes #2399
Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>
> configure.ac: dpdk: use pkg-config

- configure.ac
Since pull request #2400 pkg-config works great for dpdk, but not if
there is no pkg-config around at all.
To fix that the PKG_CHECK_MODULES macro needs to define a valid fourth
argument, otherwise it will error out.
This closes 2404
Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>
> configure.ac: dpdk: tolerate no pkg-config

- src/curl.c
- src/dpdkevents.c
- src/dpdkstat.c
- src/mic.c
- src/nut.c
- src/perl.c
- src/utils_curl_stats.c
- src/utils_tail_match.c
`plugin_dispatch_values()` will automatically fill that value in. We should probably have a similar cleanup in the notification code, which still heavily uses `hostname_g`.
> Treewide: Don't set value_list_t.host to hostname_g.

- configure.ac
- src/Makefile.am
To detect cflags and libs use the sometimes provided pkg-config for
libdpdk. That avoids build errors on systems where special flags are
needed and provided by dpdk via pkg-config, but not yet considered by
the collectd build system.
Backport of https://github.com/collectd/collectd/pull/2400 and https://github.com/collectd/collectd/pull/2405 tested on Debian.
> configure.ac: dpdk: use pkg-config - 5.7

- Makefile.am
- configure.ac
- src/synproxy.c
- src/types.db
This plugin provides statistics for Linux SYNPROXY available since 3.12. When kernel modules are loaded,    the file with per CPU counters is created under /proc/net/stat/synproxy.
> New plugin: synproxy

- src/uptime.c
It's a fix for the https://github.com/collectd/collectd/issues/2424
I changed implementation to read from `/proc/uptime` instead of `/proc/stat`.
> Reimplemented `uptime` plugin to read from `/proc/uptime`

- src/perl.c
Closes: #927
Please review and merge this small bugfix. Thanks.
> perl plugin: Added check of proper interpreter initialization.

- src/openldap.c
When plugin failes to connect to LDAP server, the `ldap_unbind_ext_s(st->ld, NULL, NULL);` is called.
According to `man 3 ldap_unbind_ext_s` (https://linux.die.net/man/3/ldap_unbind_ext_s), that call is used to unbind from the directory, terminate the current association, and free the resources contained in the ld structure. 
When plugin shutdown, the `ldap_unbind_ext_s` called again, which causes coredump.
The plugin code was changed to set `st->ld=NULL` after `ldap_unbind_ext_s` call.
No more coredumps.
> openldap: Fix crash on shutdown when openldap connection failed

- src/collectd.conf.in
- src/collectd.conf.pod
- src/swap.c
Default value: true
Usage:
```
<Plugin "swap"> 
ReportIO false 
</Plugin> 
```
This would disable reporting the Swap IO.
This is an implementation for #2433
> Added `ReportIO` option to the `swap` plugin

- src/collectd.conf.in
- src/collectd.conf.pod
- src/cpu.c
Hello,
The "cpu" plugin currently lacks two Linux-specific CPU states:
- guest (since Linux 2.6.24) Time spent running a virtual CPU for guest operating systems under the control of the Linux kernel.
- guest_nice (since Linux 2.6.33) Time spent running a niced guest (virtual CPU for guest operating systems under the control of the Linux kernel).
(excerpts from procfs(5))
This patch brings support for guest and guest_nice CPU states into collectd. It lacks testing on non-Linux systems though. Feedback on whatever can be improved would be greatly appreciated.
> cpu plugin: add linux-specific "guest" states.

- src/collectd.conf.in
- src/collectd.conf.pod
- src/utils_latency_config.c
- src/utils_latency_config.h
- src/utils_tail_match.c
When several distributions needs to be calculated in one 'tail' instance,
all their metrics will be reported as single 'bucket' type with the same plugin instance value.
That is confusing. This patch allows to split these metrics to their own types.
Practical example: webserver log line has reponse time and response length. 
We want to calculate distribution for both these values.
> tail plugin: Allow to set type for "bucket" metrics

- src/collectd.conf.pod
- src/turbostat.c
If multiple packages are defined, support non-logical core enumeration by prefixing each core id by its package id
Completes https://github.com/collectd/collectd/pull/2056 fix for https://github.com/collectd/collectd/issues/1974
> turbostat: better support for mutliple packages

- src/collectd.conf.in
- src/collectd.conf.pod
- src/filecount.c
Hi!
Proposed patch adds ability to make flexible configuration of `filecount` plugin:
- Allow to set plugin name;
- Allow to set empty plugin instance;
- Allow to set metrics type: 'FilesSizeType' and 'FilesCountType' options added;
- Allow to disable metric reporting;
- Allow to set metrics type instance ('TypeInstance' option added).
Continues work of #1944.
Configuration example:
```
<Plugin filecount>
<Directory "/var/spool/postfix/active">
Plugin "postfix"
Instance ""
TypeInstance "active"
</Directory>
<Directory "/var/spool/postfix/deferred">
Plugin "postfix"
Instance ""
TypeInstance "deferred"
</Directory>
<Directory "/var/spool/postfix/incoming">
Plugin "postfix"
Instance ""
TypeInstance "incoming"
</Directory>
<Directory "/var/spool/postfix/maildrop">
Plugin "postfix"
Instance "" …
```
> Filecount plugin: Custom values for reported plugin, type and type instance

- Makefile.am
- configure.ac
- src/msr-index.h
- src/turbostat.c
Since Linux 4.12, the kernel does not expose msr-index.h to the userland
anymore. This commit pulls and hardcode the required definitions.
Should fix https://github.com/collectd/collectd/issues/2443
> turbostat: import msr-index header from linux

- src/collectd.conf.pod
This change adds description for MaxSetDuration, which is introduced at #2440.
> write_redis_plugin: Add document for MaxSetDuration

- src/collectd.conf.pod
- src/curl.c
- src/memcachec.c
- src/tail.c
- src/tail_csv.c
Like added in  #1558 and #1563 , added option 'PluginName' to other Collectd plugins:
tail plugin: Allow custom plugin name for file instances
tail_csv: Allow custom plugin name for file instances
curl plugin: Allow custom plugin name for each Page block
memcachec: Allow custom plugin name for each Page block
> Allow custom plugin name for 'curl', 'memcachec', 'tail' and 'tail_csv' plugins.

- src/collectd.conf.in
- src/collectd.conf.pod
- src/processes.c
- src/types.db
In linux the maximum count of memory mapped files is configured via `/proc/sys/vm/max_map_count` which is 65530 by default. 
With bigger machines that are capable of running many application threads this may quickly become a sparse resource - therefore I'd like to be able to track it.
> add option to collect the count of active memory maps for linux processes

- src/collectd.conf.in
- src/collectd.conf.pod
- src/curl_xml.c
Hi!
Proposed patches adds ability to set custom plugin name and set plugin instance from XML data.
curl_xml is a generic plugin and we found such feature very useful.
In our case, we have XML-response like this:
```
<?xml version="1.0"?>
<statistic>
<source id="total">
<errors>4</errors>
<avg-duration>900</avg-duration>
<max-duration>1500</max-duration>
</source>
<source id="pool1">
<errors>1</errors>
<avg-duration>1000</avg-duration>
<max-duration>1500</max-duration>
</source>
<source id="pool2">
<errors>3</errors>
<avg-duration>850</avg-duration>
<max-duration>1000</max-duration>
</source>
</statistic>
```
From this response and with proposed patches, our collectd produces RRDs:
service-total/service_errors.rrd
service-total/service_avgduration.rrd
service-total/service_maxduration.rrd …
> Curl_xml: Custom names for plugin/plugin instances

- src/write_prometheus.c
Unfortunately, for *libmicrohttpd* "dual stack" means "enforce IPv6 (but allow IPv4, too)". That means that on systems without IPv6, libmicrohttpd'd initialization fails (when the dual stack flag is set). To work around this limitation we open the socket ourselves and pass it to libmicrohttpd to use.
Fixes: #2149
> write_prometheus plugin: Fall back to IPv4 socket if IPv6 fails.

- src/intel_pmu.c
In case reported counters were scaled metadata contains information basing on which scaled value was calculated. 
If there are more events than counters, the kernel uses time multiplexing. With multiplexing, at the end of the run, the counter is scaled basing on total time enabled vs time running: final_count = raw_count * time_enabled/time_running
> intel_pmu: add metadata with information about scaling

- src/libcollectdclient/network_parse.c
Shout-out to *scan-build* for finding this one!
> libcollectdclient/network_parse.c: Ensure memory allocated in parse_values() is always freed.

- src/curl_json.c
Currently curl_json will barely ignore boolean values in a non erroneous
way, so that if you have an array like this: `{ foo: [false, 123] }`
you will be able to access the 123 number like `foo[1]`
We now rather call our number parser with "0" for false, "1" for true.
This PR superseedes #1332
> Currently curl_json will barely ignore boolean values in a non erroneous

- src/memcached.c
When Collectd calculates 'hitratio', it divides two continiously-grown values.
So, reported metric contains the average since 'memcached' start, which is incorrect.
Collectd should report actual hitratio, not average for weeks-months-years.
The second commit adds connections rate reporting.
The value of `hitratio` is calculated as `get_hits / cmd_get` , unlike the rest, `incr_hitratio` and `decr_hitratio`, which are calculated like `incr_hits / (incr_hits + incr_misses)`.
The `get_hits / (get_hits + get_misses)` formula may be used to unify the code, if use only these variables.  But new `get_*` stats was added in memcached: the `get_expired` in memcached-1.4.26 , and `get_flushed` in memcached-1.4.28, so that unification cannot be applied.
> memcached: Fix hitratio reporting, add connections rate report

- src/collectd.conf.in
- src/collectd.conf.pod
- src/ipmi.c
Changes: 
* Added instances support and IPMI LAN connection option
* Added a notification on connection state change (notify about connection issues)
* Removed  the sensor removal in case of reading errors
* Added the lock to do not request new readings until previous reading is complete
* Disabled SDRs local cache
* Added the check for sensor 'is readable' flag
* Added the check for sensor event reading type (if sensor is discrete or not)
* Added checks for sensor states 'scanning disabled' and 'initial update in progress'
* Changes in error reporting
Please review and merge.
Superseedes #2023
> ipmi plugin: Implemented IPMI LAN connection and plugin improved 

- src/collectd-python.pod
- src/cpython.h
- src/python.c
- src/pyvalues.c
Extended python Notification class to support metadata in the same
way as it is implemented in Values class. The Values metadata class
implementation has been used as a example/source.
> python: Extend Notification class

- src/daemon/common.c
- src/daemon/common.h
- src/mcelog.c
- src/multimeter.c
- src/ntpd.c
- src/ted.c
- src/write_tsdb.c
Function sread() behaves incorrectly and unexpectedly in case of EOF - it closes FD. 
At the same time, in case of socket errors it does not close FD.
Function sread() used in two modules: zone.c and apcups.c.
Both of them do `close(fd)` when sread() return value is not equal to zero - i.e in both cases of socket error and socket EOF. Duplicated `close()` call occurs.
I think *read* function should not close fd in any cases, and other developers expects the same, I think.
This patch is proposed to fix this.
The `swrite()` function is ok, no similar fix needed.
src/apcups.c:
```
if (sread(*sockfd, (void *)&packet_size, sizeof(packet_size)) != 0) {
close(*sockfd);
*sockfd = -1;
return -1;
}
...
if (sread(*sockfd, (void *)buf, packet_size) != 0) {
close(*sockfd);
*sockfd = -1;
return -1;
} …
```
> Remove close() call from sread()

- AUTHORS
- src/collectd.conf.in
- src/collectd.conf.pod
- src/utils_format_kairosdb.c
- src/utils_format_kairosdb.h
- src/write_http.c
I needed to be able to override the standard "collectd" prefix applied to metrics send to KairosDB.
A new option "Prefix" is now available when using the KAIROSDB format with the write_http plugin.
If not specified, this option defaults to "collectd".
> Implementation of "Prefix" option for write_http plugin

- src/ipmi.c
- Add more analog sensors like 'PS1 Input Power', 'System Airflow' etc. The sensor type mapping => collectd db type done using sensor base unit type (+ percentage sensor type). 
- Avoid reading value of discrete sensors by ipmi_sensor_id_get_reading() function.
Example of analog sensors:
```
Locating sensor record...
Sensor ID              : PS1 Input Power (0x54)
Entity ID             : 10.1
Sensor Type (Threshold)  : Other
Sensor Reading        : 0 (+/- 0) Watts
Status                : ok
Lower Non-Recoverable : na
Lower Critical        : na
Lower Non-Critical    : na
Upper Non-Critical    : 868.000
Upper Critical        : 920.000
Upper Non-Recoverable : na
Positive Hysteresis   : Unspecified
Negative Hysteresis   : Unspecified
Assertion Events      :
Assertions Enabled    : unc+ ucr+ …
```
> ipmi plugin: add more analog sensors support

- src/ceph.c
- src/ceph_test.c
This patch is not backward compatible with previous ceph versions.
It adds support for [this](https://github.com/ceph/ceph/commit/767502e26ac0cfff5f060fe2ff9eca88de31258d#diff-b6cb32f55d238418c321e793d17d0da3) commit.
> Add support for ceph version luminous

- src/collectd.conf.in
- src/collectd.conf.pod
- src/utils_dpdk.c
- src/utils_dpdk.h
Correction of tracing from child process
- There was read 16kb from pipe but only less then 1kb was traced.
Rest of trace data was lost.
Added support for two EAL parameters:
LogLevel - optional EAL paramenter which enable debug traces from rte libs
If parameter is not used default trace level = 7 (INFO) is used
LogLevel "8" - (DEBUG) can be set to collectd.conf into dpdkstat
EAL section
RteDriverLibPath - optional EAL parameter which enable loading of shared
pmd driver libs. Param value can be full path to single
pmd diriver lib or directory where pmd driver libs are
located. E.g.: "/usr/lib/dpdk-pmd/librte_pmd_i40e.so"
or "/usr/lib/dpdk-pmd"
Signed-off-by: Jiri Prokes <jirix.x.prokes@intel.com>
> Correction of tracing from child process and new EAL params support

- src/nfs.c
This patch adds new NFS 4.2 procedures that are used in Linux since 3.18
> Add new NFS 4.2 counters on Linux

- src/libcollectdclient/server.c
Trying to compile latest HEAD on AIX, I noticed that the struct `ip_mreq` does not define the field `imr_address`. I checked on Gentoo Linux and the definition is the same there. But on Linux, the struct `ip_mreqn` is present and thus the failing code path is not used. 
It also fails in the assignment of `sa->s_addr`.
Note: I don't have a setup to test multicast, so this may or may not break it. It compiles on Linux (when manipulating it to think ip_mreqn is undefined) and IBM AIX 7.1 after this change.
> libcollectdclient: fix usage of ip_mreq

- src/dpdkstat.c
Fixed dpdkstats plugin compilation issue caused by #2519 commit.
===================
CC       src/dpdkstat_la-dpdkstat.lo
src/dpdkstat.c: In function ‘dpdk_stats_preinit’:
src/dpdkstat.c:128:10: error: unused variable ‘errbuf’ [-Werror=unused-variable]
char errbuf[ERR_BUF_SIZE];
^
src/dpdkstat.c: In function ‘dpdk_stats_reinit_helper’:
src/dpdkstat.c:449:10: error: unused variable ‘errbuf’ [-Werror=unused-variable]
char errbuf[ERR_BUF_SIZE];
^
cc1: all warnings being treated as errors
> dpdkstats: Fix compilation issue

- src/libcollectdclient/network_parse.c
This adds two defines that are missing on AIX because they don't have
the endian.h header file. AIX is always big endian, so no further check
is required for that. As I have no access to IBMs XLC compiler, this
patch limits the definitions to GNU GCC.
> libcollectdclient: add defines for AIX

- src/snmp_agent.c
Allocate "entry" later so that the error handling blocks don't leak it.
CID: 179244
> snmp_agent plugin: Fix memory leak.

- src/libcollectdclient/network_buffer.c
That size_t is then used to declare Variable Length Arrays. Hopefully
this helps to convince Coverity that pkg_values and pkg_values_types are
actually fully initialized.
CID: 141009, 141010
> libcollectdclient: Ensure vl->values_len is non-zero.

- src/write_riemann.c
> write_riemann plugin: Unlock mutex before destroying it.

- src/ovs_stats.c
This also refactors the ovs_stats_update_iface_ext_ids() function to
handle errors, instead of many nested if blocks.
CID: 179231
> ovs_stats plugin: Fix null dereference of "port".

- src/utils_ovs.c
CID: 179233
Additionally:
*   `src/utils_ovs.c`: Initialize `pdb->sock` to `-1` earlier.
`ovs_db_destroy()` was called before the field was initialized, leading to `close(0)` being called.
> src/utils_ovs.c: Assign variable only once.

- src/gps.c
- src/write_graphite.c
- src/write_tsdb.c
*   gps plugin: Typo, called lock() instead of unlock(). CID: 158522
*   write_graphite plugin: Unlock mutex before destroying it. CID: 179225
*   write_tsdb plugin: Unlock mutex before destroying it. CID: 179224
> gps, write_graphite, write_tsdb plugins: Fix locking issues.

- src/table.c
The Coverity check gets confused by the `tbl->results == NULL` check: due to the check, is assumes that tbl->results *may* be NULL. It then discovers the dereference in tbl_clear() without realizing that "result" and "result_num" are linked and that situation can't happen. This assertion makes this link a bit easier to conclude.
CID: 37966
> table plugin: Assert that result_num is zero when result is NULL.

- src/rrdtool.c
The buffer provided for value_list_to_string() was not long enough to fit a timestamp and a negative value using exponent and maximum precision of the gauge format.
Signed-off-by: @octo
This PR is a copy of #2556 rebased onto *collectd-5.8*.
> rrd plugin: Fix writing of long values.

- src/ping.c
Coverity gets confused if holding the lock while allocating pingobj.
CID: 37934
> ping plugin: Lock the mutex later.

- src/virt.c
The `continue` in the macro was supposed to continue the `for` loop, but was (unexpectedly) exiting the `do…while` loop instead.
CID: 179238
> virt plugin: Remove `do {} while(0)` loop around macro.

- src/libcollectdclient/network_parse_test.c
> network_parse_test.c: Only test security features if libgcrypt is available.

- src/powerdns.c
Coverity is concerned that if buffer is `NULL`, `strtok_r()` is called with two `NULL` arguments, causing a `NULL` pointer dereference.
CID: 37968
> powerdns plugin: Ensure powerdns_get_data() returns a non-NULL buffer.

- src/perl.c
Previously, the while loop ensured that meta was NULL, causing the for
loop to never been executed. This introduces a new temporary variable to
avoid changing meta before the for loop.
CID: 37960
> perl plugin: Fix exporting notification meta data.

- src/ovs_stats.c
- src/utils_ovs.c
During running collectd test commands (`collectd -T`) the deadlock issue has been discovered. This PR resolces this deadlock. During investigation, a few deadlock issue have been detected and fixed.
- **Dead-lock on destroyed mutex**
The issue happens when EVENT thread is already destroyed (event mutex) during ovs_db_destroy() 
function but POLL thread just connected to the socket and trying to send the 
OVS_DB_EVENT_CONN_ESTABLISHED message to EVENT thread via ovs_db_event_post() function which 
requires the EVENT thread mutex which has been destroyed already.
- **Internal dead-lock on pdb->mutex & pdb->event_thread.mutex**
- **OvS stats dead-lock on g_stats_lock**
- **Event can be skipped (low reproduce rate ~5%)**
There is a race condition when ovs_db_event_post() is called at the same …
> Fix collectd ovs deadlock

- Makefile.am
- configure.ac
- contrib/systemd.collectd.service
- src/collectd.conf.in
- src/collectd.conf.pod
- src/processes.c
- src/types.db
- src/utils_taskstats.c
- src/utils_taskstats.h
[Linux Delay Accounting](https://www.kernel.org/doc/Documentation/accounting/delay-accounting.txt) reports the time a task was delayed by
* waiting for a CPU (while being runnable),
* completion of synchronous block I/O initiated by the task,
* swapping in pages,
* memory reclaim.
This patch adds four metrics per configured process, one for each of the bullet points. Metrics are reported in percent rather than, for example, nanoseconds per second.
> processes plugin: Add support for Linux Delay Accounting.

- src/processes.c
Remove unused ps_delay() function when compiled without libtaskstats/libmnl
Closes: #2609
> processes plugin: Fix compilation when ps_delay() not used.

- src/memcached.c
Check for 'recv(...) == 0' state was lost while implementing persistent connections at #2388.
That can cause a deadloop if connection was closed right after successfull send of 'stats' command.
> memcached: Check for closed connection to avoid deadloop

- src/utils_tail_match.c
As reported in #2587, the f46d76e976ed76d2d8fa297918ecd308680d7ae9 causes regression.
1) It adds two fixed decimal places into type instance of reported percentiles.
Before: 
```
10
```
After:
```
10.00
```
Also, the difference in format of percentile appeared after f46d76e976ed76d2d8fa297918ecd308680d7ae9 : the '%.0f' was in use when no type instance is configured, and '%.2f' - when type instance is set.
This was fixed by setting format to '%.4g' for all cases. 
I think it's enough to use '%.4g' to output percentile values which are in range from 0 to 100.
2) It reduces accuracy of bounds in reported buckets.
Before:
```
10.05
```
After:
```
1e+02
10
```
This was fixed by reverting format back to '%g' as it was before f46d76e976ed76d2d8fa297918ecd308680d7ae9. 
Summary:
- Removed two …
> tail plugin, latency: Fix regressions after #2535

- src/ipmi.c
The value of `Sensor` option was ignored. 
Ignorelist was set to a wrong value of instance name.
References: #2626
> ipmi plugin: Fix broken 'Sensor' configuration option

- src/collectd.conf.pod
- src/modbus.c
Modbus used big endian 16-bit registers.  With 32 bit and float it would follow that the 16bit registers that are combined to form a 32bit value would also be big endian.  Sadly some folks don't do it this way and we have a mixed endian world.
Instead of ABCD with register[n] having AB and register[n+1] having CD, you end up with CDAB where register[n] has the low order bytes (CD) and register[n+1} has the high order bytes.  
This is and issue with some Xetawave LLC and Freewave Technologies MODBUS IO devices, some versions of ABB Totalflow.
> Adding support for CDAB endian 32-bit modbus polls

- src/write_kafka.c
Since librdkafka-0.11.0 applications should use rd_kafka_last_error()
to retrieve the error code from the legacy APIs.
Thanks to hikdo.
Closes: #2607
Closes: #2628
Closes: #2640
> write_kafka: 'rd_kafka_errno2err' is deprecated, fix failed builds

- docs/BUILD.dpdkstat.md
Update the dpdkstats documentation to state that it shouldn't be used with
OVS-with-DPDK. The Open vSwitch plugins is what should be used.
Signed-off-by: Maryam Tahhan <maryam.tahhan@intel.com>
> docs: update dpdkstats documentation

- src/write_prometheus.c
Otherwise Collectd fails to bind the socket after restart.
Thanks to Richard Weinberger and Brandon Hume for reporting.
Closes: #2570
Closes: #2673
> write_prometheus: Set SO_REUSEADDR on listening socket

- src/cpu.c
- src/daemon/collectd.c
- src/daemon/common.c
- src/daemon/common_test.c
- src/daemon/plugin_mock.c
- src/daemon/utils_subst_test.c
- src/disk.c
- src/interface.c
- src/tape.c
- src/uptime.c
- src/utils_mount_test.c
- src/utils_vl_lookup.c
- src/zfs_arc.c
I just tried rebuilding collectd on Solaris again and noticed a lot of failured because kstat_ctl_t requires the inclusion of kstat.h.
> Include kstat.h if available to provide kstat_ctl_t

- src/netlink.c
- src/write_prometheus.c
> Tree wide: Replace sstrerror() with STRERRNO.

- README
This commit adds text in the README to advise users of the DPDK plugins to
use compiler defenses such as -fstack-protector.
Signed-off-by: Kevin Laatz <kevin.laatz@intel.com>
> README: Include compiler defenses suggestion

- src/utils_dpdk.c
This commit increases the size of the "high_str" buffer,
which is later used by the strncpy() function. Static analysis
showed that there was a potential issue in accessing this string
if the buffer is smaller.
Signed-off-by: Harry van Haaren <harry.van.haaren@intel.com>
> dpdk: increase buffer size for parsing lcores

- src/ntpd.c
This PR addresses https://github.com/collectd/collectd/issues/2358
Here I'm simply skipping `0.0.0.0` hosts that are returned for POOL servers that should not be reported.
> Skip `0.0.0.0` hosts in ntpd plugin

- src/libcollectdclient/network_parse.c
- src/stdendian.h
There is currently a failing test and I am not sure why this happens. Does this work on Linux?
> Add fallback for endianness conversion

- contrib/redhat/collectd.spec
This fixes a typo in collectd.spec which manifested when building with `with_mcelog` set to false, invalidating `with_mbmon` setting.
> RPM spec: fix mbmon/mcelog typo

- src/stdendian.h
Uncomment line that is actually needed
> Fix gcc issue on Mac byteorder

- src/routeros.c
This happens when the `radio-name` property is unset on a wireless
interface. Why this is done is beyond me, but it does seem to be a thing.
> Fix routeros unset radio-name showing up as "(null)"

- contrib/redhat/collectd.spec
Hi
This small PR adds the ability to build Debug-enabled collectd RPMs:
`$ rpmbuild -bb --with='debug' collectd.spec`
Without this flag, it does not appear possible to build 'debug' RPMs for use on RHELish systems.
The default behaviour has not changed — without the flag, the rpms are non-debug, as normal.
> Add ability to turn on collectd "debug" feature in RPMs

- configure.ac
- src/netlink.c
- src/types.db
Related:  #2510
Related links: 
https://lkml.org/lkml/2016/2/9/886 
https://patchwork.kernel.org/patch/8151861/
> netlink plugin: Handle new counter from Linux kernel version 4.6+.

- src/write_redis.c
The calculation result of the data range
when "max_set_duration" is used is incorrect,
because the (char []) type, i.e. string, variable "time" is used
as the number for the time calculation.
As a result, data in the wrong range is deleted.
With this change, the correct data is deleted
by calculation using a double type value.
> write_redis: fix "max_set_duration" deletes unexpected data

- src/utils_cmd_listval.c
- src/utils_cmd_listval.h
- src/utils_cmds.c
- src/utils_cmds.h
> Remove empty `cmd_listval_t` data structure and related no-op code.

- Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/intel_pmu.c
- src/intel_rdt.c
- src/utils_config_cores.c
- src/utils_config_cores.h
- src/utils_config_cores_test.c
New "Cores" option is similar to that available in intel_rdt plugin.
New tool utils_config_cores is added to parse "Cores" option. It is used by intel_pmu and intel_rdt to avoid redundant code.
Having this option will allow to configure monitoring of PMU events only on specific CPUs thus decrease number of opened descriptors and improve performance significantly.
> intel_pmu: core groups feature

- Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/daemon/plugin_mock.c
- src/valgrind.suppress
- src/virt.c
- src/virt_test.c
Introduced support for events that are sent directly from libvirt – it can be enabled when “PersistentNotification” parameter is set to “false”. This change is needed to handle properly all notifications for VMs state changes. In that mode collectd sends notification as soon as possible, right after it is received from libvirt (previously some state changes notifications could be not sent by collectd because of issues with caching domains data).
When “PersistentNotification“ parameter is set to “true”, then old implementation will be used – it handles state changes notification on its own in plugin code by caching VM states and comparing state changes but there are some known limitations (e.g there are problems with notifications for domains that were removed from cache before …
> virt: Fix tracking of VM state changes

- src/daemon/common.c
This adressed to solve compilation issue on Solaris platform:
src/daemon/common.c:64:8: error: unknown type name 'kstat_ctl_t'
extern kstat_ctl_t *kc;
> Added missing include of 'kstat.h'

- src/libcollectdclient/collectd/network_buffer.h
This adressed to solve compilation issue on Solaris platform:
In file included from src/libcollectdclient/network_parse.c:26:0,
from src/libcollectdclient/network_parse_test.c:32:
./src/config.h:1517:0: error: "_FILE_OFFSET_BITS" redefined
> Added missing include of 'config.h'

- src/libcollectdclient/network_parse.c
- src/stdendian.h
This adressed to solve compilation issue on Solaris platform:
```
src/libcollectdclient/network_parse_test.c: In function 'test_parse_time':
src/libcollectdclient/network_parse_test.c:286:19: error: implicit declaration of function 'htobe64' [-Werror=implicit-function-declaration]
uint64_t be = htobe64(cases[i].in);
```
> Cherry-picked #2717 and #2741 to collectd-5.8

- src/stdendian.h
- src/utils_config_cores_test.c
This adressed to solve compilation issues.
> Added missing include of 'config.h' and cherry-picked #2761 for AIX support in collectd-5.8.

- AUTHORS
- Makefile.am
- README
- configure.ac
- contrib/redhat/collectd.spec
- src/amqp1.c
- src/collectd.conf.in
- src/collectd.conf.pod
- src/utils_deq.h
This write plugin allows data to be sent to an AMQP 1.0 intermediary such as the Apache Qpid Dispatch Router (e.g. direct messaging) or Apache Artemis Broker (e.g. queue backed messaging).
It is similar to the existing amqp plugin which is for AMQP version 0.9.1 (e.g. rabbitmq server).
> Write amqp1 plugin

- src/collectd.conf.pod
- src/modbus.c
Adding the "Scale" and "Shift" parameters from the snmp-plugin to the modbus plugin in order to be able to correct amplified data.
> modbus: Add scale and shift to modbus

- src/collectd.conf.in
- src/collectd.conf.pod
- src/ipmi.c
As requested and discussed in #2703 and #2713
New options to allow independent filtering of SEL events.
Functionality is similar to existing options 'Sensor' and 'IgnoreSelected',
which are used now for filtering metrics. 
Change-Id: I0fde54a25577e61a4c90a4ff52f62117540a4343
Signed-off-by: Mariusz Szafranski <mariuszx.szafranski@intel.com>
> ipmi plugin: Add SELSensor and SELIgnoreSelected config options.

- src/daemon/collectd.h
- src/lua.c
- src/perl.c
- src/utils_lua.c
- src/utils_lua.h
This breaks when external headers use those functions.
Fixes #2769
> Stop poisoning function in debug mode

- src/collectd-snmp.pod
- src/collectd.conf.in
- src/snmp.c
Added new options `PluginInstance`, `TypeInstance`, `TypeInstanceOID` and `PluginInstanceOID`.
These allows flexible configuration of reported metrics.
Existing `Instance` option marked as deprecated.
Issue of feature request: #2636
> snmp plugin: Implemented new configuration options

- src/ntpd.c
This is a bug and can be applied to 5.8 too.
Superseedes #976
> ntpd: Don't treat normal peers as refclocks.

- src/collectd.conf.pod
- src/redis.c
- src/types.db
- src/write_redis.c
See commit messages for details.
> redis plugin: Bugfixes, extended error reporting, persistent connections and parallel polling

- src/bind.c
- src/daemon/common.c
- src/daemon/configfile.c
- src/daemon/plugin.c
- src/daemon/plugin.h
- src/daemon/plugin_mock.c
Superseedes #2011 
Superseedes #2799
This PR is the next attempt to implement this enhancement.
Unlike previous, this one does not try to touch each plugin. 
Instead, only `configfile.c` functions are affected.
I think this is a shortest way to reach results.
cc @rubenk 
Ruben, what do you think?
> RFE: Add plugin name field into plugin context use it to improve error reporting

- src/collectd-tg.c
collectd-tg currently uses CLOCK_MONOTONIC when calling clock_gettime to acquire a time value for use in its lcc_value_list_t objects.  By definition, CLOCK_MONOTONIC "represents monotonic time since some unspecified starting point."  Apparently this "unspecified starting point" is some time further into the future than the standard Unix epoch (1-1-1970).  As a result, the timestamps that are sent out from collectd-tg are not standard epoch timestamps, and convert into human-readable dates much further into the past than the system's actual time.  Using CLOCK_REALTIME instead fixes this problem.
> Use CLOCK_REALTIME for collectd-tg times (fixes issue 2219)

- src/notify_email.c
Hi!
I tried to test `pcie_errors` plugin and got following notifications with use of `notify_email` plugin:
```
2018-06-22 14:03:35 - WARNING@test
Message: Uncorrectable(non_fatal) Error set: Unsupported Request
```
As can be seen, much of notification info was lost (not sent).
With this PR applied, now messages looks like this:
```
2018-06-22 14:59:21 - WARNING@test
Host: test
Plugin: pcie_errors
Plugin instance: 0000:02:00.0
Type: pcie_error
Type instance: non_fatal
Message: Uncorrectable(non_fatal) Error set: Unsupported Request
```
@rubenk, any votes against this change? I made it non-optional.
---
From other side, we can build service description via `format_name`.
The result will be like this:
```
2018-06-22 14:26:09 - WARNING@test
Service: …
```
> notify_email: Include all notification parameters into email

- src/redis.c
The `operations_per_second` metric removed as duplicate of other metric and as
it has wrong value also. Collectd should not report wrong values.
Metric `operations_per_second` is based on `instantaneous_ops_per_sec` field
from Redis `INFO` output. That field is calculated based on buffer of 16 values,
updated from `stat_numcommands` once per 100ms.
So, `instantaneous_ops_per_sec` value has average only for last 1.6 seconds.
While Collectd poll period is 10 seconds, statistics for 8.4 seconds is lost.
Herewith, Collectd already has correct metric `total_operations`, based on
`total_commands_processed` field taken from same `stat_numcommands` internally
in Redis. Value of this metric should be used instead of removed metric.
> redis plugin: Remove `operations_per_second` metric.

- src/collectd.conf.pod
- src/curl.c
- src/curl_json.c
- src/curl_xml.c
- src/daemon/configfile.c
- src/daemon/plugin.c
- src/dbi.c
- src/modbus.c
- src/oracle.c
- src/postgresql.c
- src/snmp.c
- src/tail.c
- src/tail_csv.c
- src/utils_db_query.c
- src/utils_db_query.h
- src/utils_tail_match.c
- src/utils_tail_match.h
Also:
curl plugin: Added 'Interval' option
curl_xml plugin: Added 'Interval' option
> tree-wide: Use interval value from plugin context, do not set 'vl->interval' in plugins more.

- src/collectd.conf.pod
- src/utils_format_graphite.c
- src/utils_format_graphite.h
- src/utils_format_graphite_test.c
- src/write_graphite.c
- src/write_kafka.c
This PR adds support for sending metrics to Graphite using the tagging support added in the 1.1.1 release.
To enable tags, set `UseTags true` in the Carbon configuration block.
When enabled, the metric names generated will look like `test.single;host=example.com;plugin=test;plugin_instance=f.o.o;type=single;type_instance=b.a.r` and can be queried from Graphite like `seriesByTag("name=test.single", "plugin=test")`.
For more information on tag support in Graphite, see [the documentation](http://graphite.readthedocs.io/en/latest/tags.html).
If tag support is not enabled, there is no change to the metric names that are sent to Graphite.
When tag support is enabled `DropDuplicateFields`, `AlwaysAppendDS`, `Prefix` & `Postfix` configuration options all retain their meaning, though `Postfix` is …
> Graphite 1.1+ tag support

- Makefile.am
- README
- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/pcie_errors.c
- src/pcie_errors_test.c
- src/testing.h
- src/types.db
The pcie_errors plugin collects PCI Express errors from Device Status in Capability
structure and from Advanced Error Reporting Extended Capability where available.
At every read it polls config space of PCI Express devices and dispatches
notification for every error that is found. Notification is also sent after error is cleared.
> New plugin to read PCIe errors

- src/write_prometheus.c
Since 0.9.53, libmicrohttpd requires explicit setting of this flag.
Closes: #2849
> write_prometheus: Added MHD_USE_INTERNAL_POLLING_THREAD flag

- src/daemon/collectd.c
Parsing is broken since:
386ecab4 Reading configuration file is now done outside main().
So after mentioned commit we've got:
collectd: invalid option -- 'B'
This commit fixes this.
> Fix parsing option for avoiding making BaseDir

- src/routeros.c
Collectd uses `radio-name` when sending metrics from `Registration Table`.
But there is no such field in table on my router. So, client should be identified by MAC-address.
When reporting `regtable`, it maybe even be preferable to use MAC-address than Radio-name, but I'm unsure and this patch behaves in backward-compatible way.
cc @manio .
References: https://github.com/octo/librouteros/pull/8
https://wiki.mikrotik.com/wiki/Manual:Interface/Wireless#Registration_Table
```
Password for user admin:
Status: re
Param 0: .id = *1
Param 1: interface = wlan1
Param 2: mac-address = 00:11:22:3E:1C:EE
Param 3: ap = false
Param 4: wds = false
Param 5: bridge = false
Param 6: rx-rate = 65Mbps-20MHz/1S
Param 7: tx-rate = 48Mbps
Param 8: packets = 34591,20635
Param 9: bytes = 6689896,2094536
Param 10: …
```
> routeros: Use MAC-address when Radio-name is missing

- src/amqp1.c
Fixes a formatting error log message that mistakenly mentions "graphite" when it should say "json" (as it is in the context of trying to output JSON data)
> Fix typo in amqp1 JSON format error message

- configure.ac
It's now valid to disable building with libxml2, using --without-libxml2. It's
also possible to set a custom prefix --with-libxml2=/custom/path.
> Add --with-libxml2 option to configure.

- src/nfs.c
The previous buffer of 64 fields was too short for the current number of
72+2 fields in NFS 4.2, causing the message
nfs plugin: Unexpected number of fields for NFSv4 server statistics: 62.
This change, originally proposed in [1], fixes that issue in a
forward-compatible manner by reusing the already known number of fields
from the static arrays.
[1]: https://github.com/collectd/collectd/issues/2076#issuecomment-350466628
Fixes #1304, #2076, #2317.
> nfs: Fix number of fields for NFSv4

- src/daemon/utils_avltree.c
- src/daemon/utils_avltree_test.c
I assume ```c_avl_iterator_prev``` is symmetric to ```c_avl_iterator_next``` 
so
```
c_avl_iterator_t *iter = c_avl_get_iterator(...);
void *key;
void *value;
while (c_avl_iterator_next(iter, &key, &value) == 0) {
...
}
c_avl_iterator_destroy(iter);
```
and
```
c_avl_iterator_t *iter = c_avl_get_iterator(...);
void *key;
void *value;
while (c_avl_iterator_prev(iter, &key, &value) == 0) {
...
}
c_avl_iterator_destroy(iter);
```
would iterate over the same elements in counter order,
But currently ```c_avl_iterator_prev```-cycle iterates over a single element only.
> fix c_avl_iterator_prev

- src/virt.c
The libvirt plugin refreshes its list of domains every RefreshInterval
seconds. If a domain crashes after getting the list, getting the stats
for its block devices returns an error. We then try to call
virDomainGetName on an invalid pointer. Fix this.
> Fix segfault in libvirt plugin

- contrib/docker/rootfs_prefix/rootfs_prefix.c
On 2018-09-06 Marc Fournier wrote:
> Hello Florian !
> 
> Yes, sure, sorry to have omitted this! I'm fine with MIT. Glad this is
> useful to others :-)
> 
> +1 for adding a default "fallback" licence to COPYING. In case this has
> unexpected implications, let's just add the MIT licence to root_prefix/* so
> Baruch can move forward with his project.
> 
> Cheers,
> Marc
> contrib/docker/rootfs_prefix: Add MIT license header.

- src/utils_dpdk.c
The config path was changed in DPDK by the commit 'adf1d86  eal: move
runtime config file to new location’. As a result, the dpdk plugins won't
be able to link to the DPDK primary application after this change.
This commit adds a compile time check for the DPDK verison being used and
sets the DPDK runtime config file location accordingly.
Suggested-by: Michael Luo <michael.luo@intel.com>
Signed-off-by: Kevin Laatz <kevin.laatz@intel.com>
> dpdk: fix dpdk runtime config file path

- src/ceph.c
src/ceph.c:284:8: warning: Null pointer argument in call to string comparison function
(strcmp("filestore", state->stack[state->depth - 2]) == 0) &&
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/bits/string2.h:817:8: note: expanded from macro 'strcmp'
: __builtin_strcmp (s1, s2)))); })
^~~~~~~~~~~~~~~~~~~~~~~~~
src/ceph.c:285:8: warning: Null pointer argument in call to string comparison function
(strcmp("journal_wr_bytes", state->stack[state->depth - 1]) == 0) &&
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/bits/string2.h:817:8: note: expanded from macro 'strcmp'
: __builtin_strcmp (s1, s2)))); })
^~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
Cherry-pick for collectd-5.8.
> Backport: ceph plugin: fix scan-build warnings

- src/ntpd.c
Found by scan-build:
src/ntpd.c:833:5: warning: Potential memory leak
ERROR("ntpd plugin: ntpd_do_query (REQ_GET_KERNEL) failed with status %i",
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/daemon/plugin.h:391:20: note: expanded from macro 'ERROR'
^~~~~~~~~~
1 warning generated.
> ntpd: plug potential leak on error

- src/gps.c
gpsd version 3.18 changed the prototype of gps_read(). Make the
gps_read() call depend on GPSD_API_MAJOR_VERSION to fix that.
This fixes build failures like:
gps.c: In function 'cgps_thread':
gps.c:144:11: error: too few arguments to function 'gps_read'
if (gps_read(&gpsd_conn) == -1) {
^~~~~~~~
> gps plugin: fix build with newer gpsd

- src/turbostat.c
scan-build: Using '/usr/bin/clang-6.0' for static analysis
make  all-am
make[1]: Entering directory '/home/ruben/src/collectd'
CC       src/turbostat.lo
src/turbostat.c:1292:5: warning: Argument to free() is the address of the global variable 'thread_delta', which is not memory allocated by malloc()
sfree(threads);
^~~~~~~~~~~~~~
./src/daemon/common.h:41:5: note: expanded from macro 'sfree'
free(ptr);                                                                 \
^~~~~~~~~
src/turbostat.c:1299:5: warning: Argument to free() is the address of the global variable 'core_delta', which is not memory allocated by malloc()
sfree(cores);
^~~~~~~~~~~~
./src/daemon/common.h:41:5: note: expanded from macro 'sfree'
free(ptr);                                                                 \ …
> turbostat plugin: free the right variable

- configure.ac
checking xmmsctrl.h usability... yes
checking xmmsctrl.h presence... no
configure: WARNING: xmmsctrl.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: xmmsctrl.h: proceeding with the compiler's result
checking for xmmsctrl.h... yes
checking for xmms_remote_get_info in -lxmms... yes
AC_CHECK_HEADER uses the preprocessor, which doesn't look at CFLAGS.
Use CPPFLAGS so it uses the right include path to look for xmmsctrl.h
> Fix detection of xmmsctrl.h

- src/disk.c
Linux 4.19 will add additional counters, which caused this plugin to bail out because it checked the number of fields exactly instead of ensuring that there are *at least* the number of fields expected.
Fixes: #2951
> disk plugin: Support Linux kernels with additional fields.

- src/daemon/utils_cache_mock.c
- src/write_stackdriver.c
All current uses of `do_post()` did provide a non-NULL pointer, but NULL is explicitly handled elsewhere, so we should cover all cases.
`http_code` vs. `status` was a simple mistake.
> write_stackdriver plugin: Fix potential NULL dereference and error reporting.

- src/collectd.conf.pod
- src/cpufreq.c
- src/types.db
Extending cpufreq plugin to read the following additional metrics:
- number of p-state(cpu frequency) transitions
- time spent in each p-state
Both metrics are reported by the Linux cpufreq-stats driver:
https://www.kernel.org/doc/Documentation/cpu-freq/cpufreq-stats.txt
> cpufreq plugin: Read number of p-state transitions and time spent in each p-state

- src/ovs_stats.c
The correct value in the OpenFlow 1.4 statistics is 1024_to_1522_packets,
even if collectd is using 1024_to_1518_packets:
$ ovs-ofctl -O OpenFlow14 dump-ports ovsbr0
OFPST_PORT reply (OF1.4) (xid=0x2): 3 ports
port  guest2: rx pkts=0, bytes=0, drop=0, errs=0, frame=?, over=?, crc=?
tx pkts=0, bytes=0, drop=0, errs=?, coll=?
duration=132.213s
rx rfc2819 1_to_64_packets=0, 65_to_127_packets=0,
128_to_255_packets=0, 256_to_511_packets=0,
512_to_1023_packets=0, 1024_to_1522_packets=0,
1523_to_max_packets=0,
Correct it to the right value.
Signed-off-by: Matteo Croce <mcroce@redhat.com>
> ovs_stats: use correct OpenFlow value

- src/utils_oauth.c
This solves sporious errors like this one:
> write_stackdriver plugin: POST https://monitoring.googleapis.com/v3/projects/{projectId}/timeSeries: API error 401: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
> src/utils_oauth.c: Renew OAuth tokens 30 seconds before they expire.

- src/virt.c
virDomainGetCPUStats() call is only required when `pcpu' extra statistics is requested.
While not supported in all configurations, this call may fail which causes failure in
reporting of other domain metrics.
virDomainGetCPUStats() was initially added in c7f23810d1f09f45cb4016da6eca6021d56bb0f7 (collectd-5.8.0)
> virt plugin: Remove optional virDomainGetCPUStats() from main flow

- src/disk.c
If you don't reset diskstats_t for a given diskname when it disappear and the diskname is reused later (for exemple an iSCSI disk) the "disk" plugin detect an "counter wrap around" because linux /proc/diskstats are
resetted to 0 for that diskname. Because of that the plugin send incorrect stats for the new disk.
Note1: the number of bytes written is calculated by multiplying the number of sector written by 512, which seems incorrect if those sector are 4k ones but I haven't tested that.
Note2: the patch proposed here is racy for the disk removal detection, a better way to detect it would be through udev, but I guess it will necessitate its own thread and more linux specific code.
> disk: in linux, reset the disk when it disappear from /proc/diskstats

- src/daemon/utils_cache.c
- src/daemon/utils_cache.h
- src/threshold.c
- src/write_riemann_threshold.c
I am using intensively the collectd notifications and thresholds and I find that due to the lack of an initial _unknown_/_unset_ state for metrics there are some inconsistencies.
Some points I think this modification could improve:
* The docs says "_If a threshold is configured to be non-persistent a notification is created for each state change_". This is not 100% true as you will never receive a notification when a metric is initially considered OK, as it is collectd itself setting that default instead of the threshold plugin or any other plugin.
* Having this initial transition will help when collectd notifications are plugged to other external visualization tools.
* Setting by default `OK` to all the metrics, regarless of the presence or not of threshold definitions, doesn't look …
> Add a new UNKNOWN state as the initial state of metrics

- src/collectd.conf.in
- src/collectd.conf.pod
- src/virt.c
This change allows to read Hostname from Libvirt metadata API.
Applications like OVirt or Openstack Nova uses this metadata API to
store additional informations like the 'user facing' Guest name.
To do so, a new choice 'metadata' is added for 'HostnameFormat' and
'PluginInstanceFormat'. And two new options are also added to localize
the hostname into the Guest metadata: HostnameMetadataNS and
HostnameMetadataXPath.
Closes: #2805
> virt: allow read Hostname from libvirt metadata

- src/sensors.c
That makes no more sense after lm-sensors got new maintainers.
Closes: #3006
> sensors: Removed checks for upper limit of SENSORS_API_VERSION

- configure.ac
- src/sensors.c
The lm_sensors-3.0.0, which introduces 'modern' API, released 2007-11-24.
The time came to drop older version support.
> sensors plugin: Drop support for libsensors older than 3.0.0

- configure.ac
The AC_CHECK_LIB test runs unconditionally, and fails with DPDK 18.11
when built with Meson as there is no longer a libdpdk.so linker script,
but only a pkg-config file, so -ldpdk (which is what AC_CHECK_LIB runs)
fails.
Run the preprocessor and link autoconf tests only if the pkg-config
check fails. If it succeeds, trust its result and the variable that it
sets.
Signed-off-by: Luca Boccassi <bluca@debian.org>
> configure.ac: run dpdk build tests only if pkgconfig fails

- src/python.c
PyOS_AfterFork() is deprecated in favour of the new functions PyOS_BeforeFork(), PyOS_AfterFork_Parent() and PyOS_AfterFork_Child(). (Contributed by Antoine Pitrou in bpo-16500.)
Since the -Werror=deprecated-declarations flag is on, the fact that PyOS_AfterFork is deprecated now results in a warning, and since all warnings being treated as errors, collectd fails to compile.
This commit detects when we have python 3.7 or newer, and uses the new replacement function.
Signed-off-by: Manoj Srivastava <srivasta@golden-gryphon.com>
> [python-3.7-fix]: Allow compilation with Python 3.7

- src/netlink.c
Hi all! This is a bugfix backport request to collectd-5.8:
mnl_attr_validate2() function implements strict equality check of kernel and
userspace structures size. Additional counters was added to 4.6 Linux kernel,
sizes was changed and mismatch can occur.
This patch weakened validation.
Now Collectd just checks if structures, received from kernel space, has enough
data.
Closes: #2510
#	src/netlink.c
> Backport: netlink plugin: Use of less strict rules in link_filter_cb()

- contrib/collection3/share/style.css
- Fit to the form contents instead of filling the page width
- Relate better to the table below by aligning left-hand side and
rounding corners
> collection3: Improve index.cgi form fieldset border style

- CONTRIBUTING.md
Document this change so it can be referenced from the ChangeLog status set by the bot.
> CONTRIBUTING.md: Document the new change log requirement / behavior.

- CODEOWNERS
The idea is to test the concept discussed in #2958.
CC: @sunkuranganath, @kwiatrox, @anaudx, @rjablonx 
ChangeLog: Code ownership of five plugins has been handed out to folks from Intel.
> CODEOWNERS: Add code owners as discussed at the meetup.

- src/write_prometheus.c
Fixes compilation issue on Mac OS X. See also #3055.
ChangeLog: write_prometheus plugin: A compilation issue on Mac OS X has been fixed.
> write_prometheus plugin: Only use SOCK_CLOEXEC if it is defined.

- contrib/collection3/bin/graph.cgi
collection3: Output graph.cgi debug as UTF-8
Ensure text and symbols e.g. degrees Celsius are shown as intended.
> collection3: Output graph.cgi debug as UTF-8

- src/daemon/common.c
- src/daemon/common_test.c
Additionally, test the (NULL, 0) output buffer for all test cases rather
than an individual, isolated test case.
Fixes: #3062
ChangeLog: collectd: An invalid memory access in the `strjoin()` function has been fixed.
> strjoin(): Fix behavior if output buffer is NULL.

- src/collectd-snmp.pod
- Remove outdated snmp plugin docs re. threading, and add docs about how the snmp plugin uses complex reads, and some notes for tuning.
Fixes #3077.
Note that I also removed some end of line whitespaces, my editor does this on save automatically to keep things tidy.
ChangeLog: snmp plugin: Document thread usage correctly.
> Document the snmp plugin's use of complex reads

- src/daemon/collectd.c
- src/daemon/configfile.c
When they return an error, collectd should not ignore this.
Fixes #3076 
Changelog: Handle failure of simple config callbacks
> Handle failure of simple config callbacks

- src/daemon/types_list.c
We allocate a number of times for each line in types.db.
Since plugin_register_dataset() makes a copy of the dataset anyway, we
can create the dataset on the stack instead of the heap.
This reduces the number of calloc calls on my system from 624 to 337
when running collectd -T with the default types.db.
Changelog: reduce the nr of allocations when parsing types.db
> Reduce the nr of allocations when parsing types.db

- Makefile.am
Apparently the default behaviour for pod2man changed at some point and
now it exits with a syntax error instead of exiting successfully with a
<POD ERRORS> section.
Now we do display the syntax issue:
[ruben@localhost collectd]$ make -j
POD2MAN  src/collectd.conf.5
src/collectd.conf.pod around line 10361: You forgot a '=back' before '=head2'
POD document had syntax errors at /usr/bin/pod2man line 69.
make: *** [Makefile:9641: src/collectd.conf.5] Error 255
> Don't hide errors when creating manpage

- .cirrus.yml
Following the decision(*) to sunset our old Jenkins-based CI, here's a first attempt to provide a replacement using cirrus-ci's "free for opensource projects" plan. Not all checks we had with Jenkins have been re-implemented (yet), and the plan is to focus first on building/testing the code & submitted patches. ie: we'll take care of the nightly builds later.
One major difference is that all the tests are run in docker images we maintain (see https://github.com/collectd/ci-docker/blob/master/README.md). This will be much less cumbersome to work with than the VM templates we had previously: anyone with the docker engine installed can run tests locally, and build new images. And anyone can submit patches to https://github.com/collectd/ci-docker/ to improve existing images or add support for …
> Re-implement CI using cirrus-ci

- src/lua.c
Found while running collectd -T under valgrind:
==25971== 75 (64 direct, 11 indirect) bytes in 1 blocks are definitely lost in loss record 154 of 274
==25971==    at 0x483AB1A: calloc (vg_replace_malloc.c:762)
==25971==    by 0x4854009: lua_cb_register_read (lua.c:288)
==25971==    by 0x4FBE886: ???
==25971==    by 0x4FD4900: ???
==25971==    by 0x4FBEAD7: ???
==25971==    by 0x4FBEB04: ???
==25971==    by 0x4FBDF16: ???
==25971==    by 0x4FBEE5E: ???
==25971==    by 0x4FB53ED: ???
==25971==    by 0x48536E7: lua_script_load (lua.c:465)
==25971==    by 0x485387E: lua_config_script (lua.c:532)
==25971==    by 0x485395E: lua_config (lua.c:557)
Changelog: Lua plugin: A memory leak has been fixed.
> lua plugin: cleanup properly when shutting down

- contrib/docker/50docker-apt-conf
- contrib/docker/Dockerfile
I originally created this change in the context of #2973, which has been fixed in the mean time. I though I'd leave this here in case anyone is interested.
No changelog since it touches contrib/ only.
> contrib/docker/: Switch to Debian slim, separate ENTRYPOINT/CMD, install suggestions.

- src/rrdcached.c
ChangeLog: rrdcached plugin: Time resolution has been improved to microseconds.
Have been sending an int to rrdcached for the epoch value, it supports microseconds. You want to use microseconds. 
See https://lists.oetiker.ch/pipermail/rrd-developers/2003-March/001007.html for we want this
> changed time format to no longer lose microseconds

- configure.ac
Looks like the check result used to be stored in a variable of a different name.
I hope that this will fix the Cirrus CI builds.
ChangeLog: Build system: The "df" plugin is now built when `getmntent_r()` is available.
> Build system: enable the "df" plugin when getmntent_r() is available.

- Makefile.am
Older versions of pod2man don't have this
> pod2man: remove --errors argument

- configure.ac
- src/utils/mount/mount.h
Fixes a regression introduced in 6378ec288f34ff250b2971a1452338a2b34c240a.
> configure.ac: Fix include of "utils/mount/mount.h".

- src/ovs_stats.c
src/ovs_stats.c:863:23: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
for (int i = 0; i < YAJL_GET_ARRAY(ifaces_list)->len; i++) {
~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
> ovs_stats plugin: fix compiler warning

- src/turbostat.c
src/turbostat.c:1466:5: warning: no previous prototype for function 'save_affinity' [-Wmissing-prototypes]
int save_affinity(void) {
^
src/turbostat.c:1479:6: warning: no previous prototype for function 'restore_affinity' [-Wmissing-prototypes]
void restore_affinity(void) {
^
> turbostat plugin: fix two compiler warnings

- src/virt.c
src/virt.c:725:7: warning: no previous prototype for function 'metadata_get_hostname' [-Wmissing-prototypes]
char *metadata_get_hostname(virDomainPtr dom) {
^
1 warning generated.
> virt plugin: fix compiler warning

- src/write_prometheus.c
make[1]: Entering directory '/home/ruben/src/collectd'
CC       src/write_prometheus_la-write_prometheus.lo
In file included from src/write_prometheus.c:29:
src/write_prometheus.c: In function ‘metric_family_get’:
./src/daemon/plugin.h:393:20: warning: ‘%s’ directive argument is null [-Wformat-overflow=]
393 | #define ERROR(...) plugin_log(LOG_ERR, __VA_ARGS__)
|                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/write_prometheus.c:725:5: note: in expansion of macro ‘ERROR’
725 |     ERROR("write_prometheus plugin: Adding \"%s\" failed.", name);
|     ^~~~~
src/write_prometheus.c:725:46: note: format string is defined here
725 |     ERROR("write_prometheus plugin: Adding \"%s\" failed.", name);
|                                              ^~
CCLD     write_prometheus.la
> write_prometheus plugin: fix compiler warning

- src/utils/oauth/oauth.c
make[1]: Entering directory '/home/ruben/src/collectd'
CC       src/utils/oauth/liboauth_la-oauth.lo
src/utils/oauth/oauth.c: In function ‘get_assertion’:
src/utils/oauth/oauth.c:283:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
283 |   else if (status >= buffer_size)
|                   ^~
> oauth.c: fix compiler warning

- src/intel_rdt.c
make[1]: Entering directory '/home/ruben/src/collectd'
CC       src/intel_rdt_la-intel_rdt.lo
src/intel_rdt.c: In function ‘rdt_dump_cgroups’:
src/intel_rdt.c:74:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
74 |     for (int j = 0; j < cgroup->num_cores; j++) {
|                       ^
src/intel_rdt.c: In function ‘rdt_dump_data’:
src/intel_rdt.c:103:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
103 |   for (int i = 0; i < g_rdt->num_groups; i++) {
|                     ^
CCLD     intel_rdt.la
> intel_rdt plugin: fix compiler warnings

- src/collectd.conf.in
- src/collectd.conf.pod
- src/types.db
- src/virt.c
ChangeLog: virt: Add block info statistics for disk devices
Previously block info statistics(allocation, capacity, physical) were available through libvirt api but were missing in data from collectd-virt plugin.
virDomainBlockInfo statistics are now exposed through virt plugin as:
-disk_allocation
-disk_capacity
-disk_physical
NOTE: newly added block info statistics can be fetched from libvirt only for devices with available 'source' property - because of this scenario additional logic for checking if source is available has been added to virt plugin
NOTE2: previously 'block stats' statistics were stored and described in source code as 'block info' - this pull request contains refactoring that renames 'block_info_*' family of functions to 'block_stats_*' as it should be named from …
> virt: Add block info statistics for disk devices

- src/virt.c
If connection has failed then `lv_init' returns early without initializing `notif_thread'.
This causes segfault due to incorrect `pthread_join()` call on Collectd shutdown.
Closes: #3082 
Changelog: virt plugin: Fix segfaults on shutdown
cc @fromanirh
cc @rubenk
> virt plugin: Fix segfaults on shutdown

- Makefile.am
- src/collectd.conf.pod
- src/virt.c
ChangeLog: virt: Fix parsing config file options
This PR fixes issues related to parsing configuration options for virt plugin:
- fixed domain filtering option
- fixed interface filtering option
- added return statement to properly finish successful parsing
ExtraStats' option value - without that, parsing of config file will
fail if 'ExtraStats' option is used in the collectd config file
because return code is the one for unrecognized parameter key.
- fixed parsing of RefreshInterval - previously error was thrown by
mistake if value was not written between double quotes(i.e. "60" was
fine but 60 was not)
- previously validation for boolean option value(such as value of
'IgnoreSelected' parameter) in virt plugin was missing and bad input
in config file could be unnoticed by user(in config …
> virt: Fix parsing config file options

- contrib/systemd.collectd.service
This prevents showing eg. /etc if that's a separate file system.
Resolves: https://github.com/collectd/collectd/issues/3134
> Remove ProtectSystem from service file

- src/collectd.conf.pod
- src/modbus.c
ChangeLog: Allow setting up RS485 mode for Modbus-RTU
> Add support for RS485 to modbus plugin

- src/collectd-lua.pod
- src/lua.c
Changelog: lua plugin: Make it possible to register more than one reader/writer (bug)
Changelog: lua plugin: Don't destroy interpreter too early (bug)
Changelog: lua plugin: free mutex on callback destroy (issue)
Changelog: lua plugin: Cleanup
Closes: #2379
Closes: #3139
> lua plugin: Make it possible to register more than one reader/writer; bugfixes; cleanup.

- src/virt.c
Changelog: virt plugin: Support new metric from libvirt-5.0.0 virDomainMemoryStats()
Closes: #3143
> virt plugin: Support new metric from libvirt-5.0.0 virDomainMemoryStats()

- src/virt.c
If Collectd started before libvirtd, that results as no connection and no more retries.
lv_init()/lv_connect() reworked to avoid this.
Reference: b2541eb463165a5973fedb5d51eab8288fcd7ebc
Reference: 5903e6d5414b1a9580a63c29afff1788cec6c91e
This PR is checked on my production systems.
Changelog: virt plugin: Do not fail if no connection on init()
> virt plugin: Do not fail if no connection on init()

- src/virt.c
Changelog: virt plugin: Added new code of virDomainShutoffReason enum and domain events
https://www.redhat.com/archives/libvir-list/2017-May/msg00540.html
> virt plugin: Added new code of virDomainShutoffReason enum and domain events

- src/virt.c
Changelog: libvirt plugin: split memory report into dedicated types
As documented (https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainMemoryStats),
statistics elements represents following:
1)
```
VIR_DOMAIN_MEMORY_STAT_SWAP_IN: The total amount of data read from swap space (in kb). 
VIR_DOMAIN_MEMORY_STAT_SWAP_OUT: The total amount of memory written out to swap space (in kb). 
```
These elements are about swap usage, not used amount, and should not be submitted as GAUGE type (which `memory` type is).
So, move these elements values to `swap_io` type which is DERIVE.
2) 
```
VIR_DOMAIN_MEMORY_STAT_MAJOR_FAULT: The number of page faults that required disk IO to service. 
VIR_DOMAIN_MEMORY_STAT_MINOR_FAULT: The number of page faults serviced without disk IO.
```
These elements are …
> Libvirt plugin: split memory report into dedicated types

- src/collectd.conf.pod
- src/virt.c
PR #2701 (which is not released) adds 'domain_state' metric and ExtraStats's option `domain_state`
selector behaviour was changed: now it enables metric, not notification.
Removed inconsistency between documentation and implementation.
Not all `get_domain_state` calls was covered by selector check.
As result, metric was always sent for inactive domains.
That is fixed now.
Changelog: virt plugin: Updates regarding to 'domain_state' metric
ChangelogX: Do not report 'domain_state' metric when not enabled by ExtraStats;; Updated documentation according to changed `domain_state` selector behaviour.
> virt plugin: Updates regarding to 'domain_state' metric

- src/virt.c
This is fix for typo in #3151.
> virt plugin: Fix typo after #3151

- src/collectd.conf.in
- src/collectd.conf.pod
- src/curl.c
- src/curl_json.c
- src/curl_xml.c
In situations when hostnames in URLs resolve to both IPv4 and IPv6 addresses, sometimes it's useful to have separate statistics for both of these.
With this commit, within `<Page>` block you can set
```
AddressFamily "ipv6"
```
or
```
AddressFamily "ipv4"
```
to specifically use one or the other.
This might also solve issue #2171
ChangeLog: curl_* plugins: Ability to force specific AddressFamily has been added.
> curl plugin: add AddressFamily

- src/write_riemann.c
Make it possible to capture information using filters in collectd and use this information in Riemann for deciding what to do with the event.
ChangeLog: write_riemann plugin: MetaData is copied to Riemann events
This is basically a rewrite of #1675 opened a few years ago but which has never been merged.  It relies on the current MetaData API.
Cc @faxm0dem 
Closes #1675
Closes #2940
> Copy MetaData to Riemann events in write_riemann

- src/collectd.conf.in
- src/collectd.conf.pod
- src/virt.c
Changelog: virt plugin: improvements and fixes.
1)
```
virt plugin: Added ExtraStats selector 'memory' 
This allows to disable virDomainMemoryStats calls when hypervisor/drivers
does not supports that function or it does not provide additional details.
```
2)
```
virt plugin: Added ExtraStats selector 'vcpu'  
This allows to disable virDomainGetVcpus calls when hypervisor/driver
does not supports that function.
```
3)
```
virt plugin: Do not request cpu maps when not required
```
4)
```
virt plugin: Disable ExtraStats selectors when unsupported by libvirt 
When function is not supported by driver, log filled by continuous messages like:
libvirt: Domain Config error : this function is not supported by the connection driver: virDomainGetDiskErrors
libvirt API allows us to detect such cases …
```
> virt plugin: improvements

- configure.ac
From Python 3.8 and onwards C extensions are no longer
linked to libpython so in order to embed python within
an application the --embed flag needs to be added to
python3-config --libs. A fall back is provided as the
command will error out on previous python versions.
References: https://bugs.python.org/issue36721
Resolves: #3166 
ChangeLog: Add Python 3.8 compatibility
> Add Python 3.8 compatibility

- contrib/redhat/collectd.spec
* nvidia_gpu
* write_stackdriver
* pcie_errors
The first 2 are disabled, as I don't know what lib they require
(configure fails)
Change-Id: I56456b418edd3defb3c5620a5ad58f527951309c
> redhat spec: fix build due to new upstream plugins

- src/barometer.c
- src/daemon/configfile.c
- src/load.c
- src/logfile.c
- src/openvpn.c
- src/syslog.c
- src/ted.c
Some plugins' RC was != 0 and started to fail due to stricter verification introduced by 3b9c7b2.
This commit fixes those return values. For some plugins, fix verbosity of error message: non-zero rc
should be error, not warning.
Fixes #3180
What I chose to do:
* fix RC when I judged it to be non-fatal (load, logfile)
*  fix loglevel from WARNING to ERROR in other cases (barometer, openvpn, ted)
* add log message (syslog)
ChangeLog: fix incorrect return codes or log level for several plugin config callbacks
> Fix return value or loglevel for several plugins

- configure.ac
- src/utils/dns/dns.c
- src/utils/dns/dns.h
glibc has removed __NAMESER and __BIND symbols from their codebase.
There is no benefits of use defines from glibc, so replaced them by numbers.
Closes: #3145
Changelog: dns plugin: Do not use headers from glibc
> dns plugin: Do not use headers from glibc

- configure.ac
configure unconditionally adds gcc-specific W-style flags which break compilation when compiling with other compilers like Oracle Studio. The PR adds conditionals around the W-style flags to only be applied when compiling with GCC.
Changelog: Build system: Add conditionals in configure around the W-style flags to only be applied when compiling with GCC.
> Use GCC-specific flags only when compiling with GCC

- src/daemon/utils_cache.c
This changes a bad pointer reference in uc_iterator_get_values, which
would cause the grpc plugin to crash.
This also fixes uc_insert by making it properly add the meta_data to
the cache.
Both of these changes should make the grpc QueryValues call work as
expected.
> utils_cache: fix pointer reference and meta_data ingestion

- Makefile.am
This is a possible fix for #3194.
ChangeLog: Build system: Use test_utils_proc_pids only when compiling the plugin that uses it
> Use test_utils_proc_pids only when compiling the plugin that uses it

- configure.ac
Without these lines `--with-libnetsnmpagent=<dir>` will not set `CPPFLAGS` and `LDFLAGS` properly. The structure is now the same as it is already the case for the corresponding libnetsnmp library.
ChangeLog: Build system: Add missing definitions for libnetsnmpagent in configure.ac
> Add missing definitions for libnetsnmpagent

- src/powerdns.c
Changelog: powerdns: Added 'unreachables' reporting
Issue: #3112
Wiki https://collectd.org/wiki/index.php/Plugin:PowerDNS provides configuration with 'unreachables' reported, but that is not supported by plugin.
This PR fixes that.
> powerdns: Added 'unreachables' reporting

- Makefile.am
This is to avoid some warnings in Makefile.am which I was introduced in the movement of the pid test inside the conditional using the code in PR #3197 
ChangeLog: Build system: Avoid warning in Makefile.am to fix issues introduced in PR #3197
> Move Makefile rules for pid_test inside conditional for code

- configure.ac
- src/disk.c
Changelog: Recover setlocale() call in src/daemon/collectd.c do_init() - issue #3181 
Changelog: configure.ac: Removed unused checks for functions
(Cause is #1865 changes, released in 5.8.0, so it might require backport)
> Issue 3181

- CODEOWNERS
since the last matching pattern takes the most precedence.
> Move trusted-contributors down the list

- src/daemon/configfile.c
- src/daemon/plugin.c
- src/daemon/plugin.h
- src/daemon/plugin_mock.c
Changelog: daemon: Check if plugin actually loaded before reporting configuration issues
1.1)
Case: Plugin not loaded, "complex" configuration found.
Old Behaviour:  
* dispatch_value_plugin() not called. 
* Reported message (for each block in plugin configuration):
"There is a `%s' block within the configuration for the %s plugin. The plugin either only expects "simple" configuration statements "
"or wasn't loaded using `LoadPlugin'. Please check your configuration."
* dispatch_block_plugin() returns 0 (daemon continues to run).
1.2) 
Case: Plugin not loaded, "simple" configuration found.
Old Behaviour: 
* called dispatch_block_plugin()->dispatch_value_plugin()->cf_dispatch()
* Reported message:
"Found a configuration for the `%s' plugin, but the plugin isn't loaded or didn't register a …
> daemon: Check if plugin actually loaded before reporting configuration issues

- src/virt.c
Changelog: virt: Fix memory leak with libvirt MetadataXPath enabled
Backport fixes for collectd#3225 to collectd-5.9
> Backport fixes for collectd#3225 to collectd-5.9

- configure.ac
- src/network.c
This is a backport of https://github.com/collectd/collectd/pull/3207/
> Cppflags backport

- src/syslog.c
This makes the log message more consistent with the behaviour,
and also is consistent with pre-
3b9c7b21b4ddfcf59a0147bc9e91e8889ca78d56 behaviour
Change-Id: I0e8aa2f5c44cb5b4142001954f4544c4157125c9
Fixes: #3236
ChangeLog: Syslog plugin restore previous behaviour: fallback to info for unsupported level
> Don't fail if syslog loglevel doesn't match

- ChangeLog
- src/utils/common/common.c
This should fix #3232 #3235 and #3236 
ChangeLog: Fixes failing plugins after introduction of snprintf wrapper
> fix ssnprintf wrapper

- src/zfs_arc.c
Probably due to a merge gone wrong, the first two lines were skipped twice, skipping four lines in total and thus missing the "hits" and "misses" counts.
ChangeLog: zfs_arc plugin: A bug that caused the first to values to be skipped was fixed.
> zfs_arc plugin: Fix skipping of leading lines

- configure.ac
ChangeLog: Build System: Fix activation of snmp_agent
If netsnmp library has been built without mib loading support (through
--disable-mib-loading), build of snmp_agent fails on:
```
src/snmp_agent.c: In function 'snmp_agent_get_asn_type':
src/snmp_agent.c:160:47: error: dereferencing pointer to incomplete type 'struct tree'
return (node != NULL) ? mib_to_asn_type(node->type) : 0;
```
struct tree is defined in net-snmp/libray/parse.h which is included by
net-snmp/mib_api.h only if NETSNMP_DISABLE_MIB_LOADING is not set.
To fix this error, check for get_tree function in netsnmp library in
addition to init_agent in netsnmpagent library
Fixes:
- http://autobuild.buildroot.org/results/6d7ac28f154f83208f949c62d28411855f1817f8
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure.ac: fix activation of snmp_agent

- configure.ac
ChangeLog: Remove double "without" added by commit b7818712d46e9fbac7bd9dfe93dca936c101d680
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure.ac: fix typo

- src/sysevent.c
ChangeLog: sysevent plugin: use sstrncpy instead of strncpy
> Use sstrncpy instead of strncpy in sysevent plugin

- src/turbostat.c
ChangeLog: turbostat plugin: Power metrics update for recent server CPUs.
Adding Intel server Skylake, Cascade lake and Ice Lake CPU watts telemetry. Added CPU model numbers to allow the plugin to read this CPU package telemetry.
> Upstream turbostat

- src/sysevent.c
ChangeLog: sysevent: Add a few missing calloc result checks in the sysevent_init function
> Check for sysevent plugin init calloc failures

- src/java.c
The error message did not contain a 'not'
Closes: https://github.com/collectd/collectd/issues/3285
> Fix typo in src/java.c

- src/zfs_arc.c
Fixes #2843
ChangeLog: zfs_arc plugin: New cache values are now read on Linux
> zfs_arc plugin: Read dbuf_size, dnode_size and bonus_size

- src/contextswitch.c
ChangeLog: contextswitch plugin: fix deprecation warning on Linux
> Only include <sys/sysctl.h> when needed

- configure.ac
- src/exec.c
Pass the environment as a parameter to the child process
and don't modify the environment of the parent process.
Follow-up to 0684aea7
Closes #3041
Changelog: exec: fix a race condition when setting environment variables
> exec: fix a race condition when setting environment variables

- configure.ac
Add -std=c++11 when checking gor protobuf/util/time_util.h otherwise
test will fail on:
```
configure:104495: checking google/protobuf/util/time_util.h usability
configure:104495: /home/br-user/autobuild/run/instance-2/output/host/bin/mips-linux-gnu-g++ -c -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -D_FORTIFY_SOURCE=1  -pthread  conftest.cpp >&5
In file included from /home/br-user/autobuild/run/instance-2/output/host/opt/ext-toolchain/mips-linux-gnu/include/c++/5.3.0/atomic:38:0,
from /home/br-user/autobuild/run/instance-2/output/host/mips-buildroot-linux-gnu/sysroot/usr/include/google/protobuf/io/coded_stream.h:113,
from /home/br-user/autobuild/run/instance-2/output/host/mips-buildroot-linux-gnu/sysroot/usr/include/google/protobuf/duration.pb.h:23,
from …
```
> configure.ac: fix protobuf/util/time_util.h detection

- src/exec.c
- src/network.c
Changelog: exec plugin: fix memory reclamation at plugin shutdown
Changelog: network plugin: fix data race accessing sending_sockets
These were spotted with the help from AddressSanitizer.
> network,exec: fix memory issue

- configure.ac
In libtokyotyrant handling, set `with_libtokyotyrant_ldflags` to `"-L$withval/lib"`, not `"-L$withval/include"`.
> Fix libtokyotyrant handling

- configure.ac
Check libupsclient `$withval `for being a regular file in addition to being executable/searchable. The value may be a directory name.
> Fix libupsclient detection

- Makefile.am
We plan to use this library in the write_gcm plugin in the https://github.com/Stackdriver/collectd fork. I hope it's OK with you to make this change upstream before we are ready to contribute the Stackdriver plug-in into this codebase.
ChangeLog: no user-visible changes; internal refactoring.
> Create internal library for utils_llist

- src/collectd-snmp.pod
- src/collectd.conf.in
- src/snmp.c
ChangeLog: snmp plugin: support for bulk transfer.
As per issue #2495 we are experiencing so long collect time for switch with high number of port so i took a try at that.
This is the first attempt, it's working but i may not have seen every failure opportunities, i tried to be the less disruptive as possible.
This mostly modify the csnmp_read_table to switch over to 'GETBULK' PDUs if conditions are ok, and handle the extra return values with the same loop.
Comments are welcome
> snmp plugin: add support for SNMP Bulk Transfer

- src/daemon/configfile.c
Empty <Plugin> section can be used to autoload plugin,
which does not supports configuration callback.
Closes: #3347
Changelog: daemon: Fix regression caused by #3217
> daemon: Fix regression caused by #3217

- src/write_riemann.c
Changelog: Fix memory leak in write_riemann
Change-Id: If95da8d90c078c19ac0062e3bbb006185dcc441d
> Fix memory leak in write_riemann

- configure.ac
Since Python 3.8 --embed flag needs to be provided to python-config to embed python.
Reference: https://bugs.python.org/issue36721
This was partially addressed in #3170 but only fixed building and not linking with python.
ChangeLog: Fix linking with Python 3.8
> Fix linking with Python 3.8

- src/amqp1.c
- src/network.c
Fix a few memory leaks on error paths in the amqp1 plugin and one in the network code.
ChangeLog: network: Fix memory leak.
ChangeLog: amqp1 plugin: Fix leaks on error paths.
> Leak fixes

- .travis.yml
This disables the grpc plugin on OSX in order to avoid CI issues shown in https://github.com/collectd/collectd/pull/3350
> Remove grpc from Mac builds for now

- src/aggregation.c
ChangeLog: Fix unreachable clause where both tmp_plugin and tmp_plugin_instance are non-empty.
> Fix unreachable clause where both tmp_plugin and tmp_plugin_instance are non-empty.

- src/battery.c
- src/processes.c
- src/thermal.c
- src/utils/common/common.c
- src/utils/common/common.h
Also fixes a potential unterminated string in `thermal_procfs_device_read`.
ChangeLog: collectd: Factored out read_text_file_contents for reading text files
and used it to fix a potential unterminated string in the `thermal` plugin.
/cc @jkohen 
[edit @mrunge]: Broke the ChangeLog line, since CI fails on long changelog lines.
> Factor out read_text_file_contents to ensure that data read from text files is a valid C string.

- src/cpu.c
- src/memory.c
- src/swap.c
- src/uuid.c
Changelog: Contain use of sysctl / sysctrlbyname to BSD variants, as deprecated on Linux
With pending deprecation warning of gclib sys/sysctl.h and associated functions, refactor code that used sysctl so it constrains use to BSD variants.
As per analysis in of @kraj PR: https://github.com/collectd/collectd/pull/3234
The sysctl & sysctlbyname (declared in sys/sysctl.h) are BSD based functions, available in: FreeBSD, NetBSD and macOS. OpenBSD appears to be exception as it only has sysctl and no sysctlbyname declared.
Refactored code: cpu.c, memory.c, swap.c & uuid.
Changes have maintained existing precedence of use between sysctl / sysctrlbyname
Logic is based on:
HAVE_SYSCTL && HAVE_SYSCTLBYNAME == most BSDs or
__OpenBSD__ == OpenBSD which does not have sysctlbyname
TESTING:
Operationally …
> Restrict use of sys/systl to BSD variants in alignment with gclib deprecation on Linux

- src/daemon/utils_cache.c
- src/daemon/utils_cache.h
This is useful for traversing all the meta data elements in a value list, since there is no element to look up the metadata object.
For sample usage, see Stackdriver#166
ChangeLog: internal API change.
> Expose meta_data_toc function in utils_cache.

- Makefile.am
- src/collectd.conf.pod
- src/write_http.c
write-http can optionally configure cURL Statistics as per other cURL based plugins
ChangeLog: write_http plugin: add ability to configure cURL Statistics
> Allow cURL Statistics option in write-http plugin

- Makefile.am
ChangeLog: build system: Avoid $< (implied source) in non-inference rules
> Efuss fix 3313

- configure.ac
- src/nfs.c
ChangeLog: NFS plugin: An implementation for NetBSD (using sysctl) has been added.
Implement the NFS plugin for NetBSD using sysctl.
As NetBSD doesn't collect separate statistics for NFSv2 and NFSv3 and doesn't (yet) support NFSv4, this is v3 only.
> Implement the NFS plugin for NetBSD

- AUTHORS
- Makefile.am
- README
- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/dcpmm.c
- src/types.db
ChangeLog: dcpmm plugin: a new plugin for Intel Optane DC Presistent Memory (DCPMM).
dcpmm plugin collects performance and health statistics from Intel Optane DC Presistent Memory (DCPMM).
Signed-off-by: TG, Hari <hari.tg@intel.com>
> dcpmm plugin

- src/types.db
Changelog: types.db: fix ping_droprate range spec
It's always in range 0-1 since the initial support for the data source
in commit 9cc8e54618fe3f8e7af879fcc9e04d71125456fd
> types.db: fix ping_droprate range spec

- src/network.c
- src/network_test.c
ChangeLog: network plugin: Add a new metadata "network:ip_address"
Although the telemetry data already have the "host" identifier, it
can be determined by clients. This additional metadata will help you
to detect spoofing at server side.
It will also help you to filter the data by sender's address.
> network plugin: Add a new metadata "network:ip_address"

- src/battery.c
This patch will enable the collectd battery module to read capacity off the sysfs power_supply charge_now, charge_full and charge_full_design files since some systems do not offer the "energy_now", "energy_full" and "energy_full_design" files that are currently used.
The module will still check for the energy files but fall back to the new method.
Since the charge files are provided in microamps/hour, the values are adjusted to be Wh and therefore the same as provided by the original approach. (The same conversion factor _voltage_min_design_ is used by xfce4 power manager so the values match)
ChangeLog: battery plugin: read linux sysfs charge files
> battery plugin: read linux sysfs charge files

- bindings/perl/lib/Collectd/Unixsock.pm
The code does not currently handle the collectd daemon going away gracefully. This change makes the code robust against those cases.
ChangeLog: perl Unixsock: Made the module robust against socket errors and disconnects.
> Make the perl Unixsock module robust against socket errors and disconnects

- src/daemon/filter_chain.c
ChangeLog: Fix constant for max plugin name length introduced in #1034
> Fix constant for max plugin name length introduced in #1034

- src/amqp.c
- src/amqp1.c
- src/connectivity.c
- src/daemon/plugin.c
- src/daemon/plugin.h
- src/daemon/plugin_mock.c
- src/dns.c
- src/email.c
- src/exec.c
- src/gmond.c
- src/gps.c
- src/ipmi.c
- src/mcelog.c
- src/mqtt.c
- src/network.c
- src/pinba.c
- src/ping.c
- src/procevent.c
- src/python.c
- src/rrdtool.c
- src/sigrok.c
- src/sysevent.c
- src/unixsock.c
- src/utils/ovs/ovs.c
``pthread_setname_np()`` does not work reliably when a thread has been created in a detached state. Set the thread name first, and then call ``pthread_detach()`` afterwards (if necessary).
This prevents error messages like this one:
```
set_thread_name("unixsock conn"): No such process
```
ChangeLog: Fix a race condition when setting thread names
> Set the thread name before detaching the thread

- src/nut.c
- src/types.db
ChangeLog: nut: Adding support for the "output.realpower" value from the ups code.
Calculating the value from voltage and current does not work for all USV's,
so this would be a benefit to have, when the USV provides the value.
> nut: add readout of power

- version-gen.sh
ChangeLog: build: Cleanup version-gen.sh
Existing script matches too generously.  eg, an annotated
tag 'foo-connectd-bar' will not be filtered.  Effectively,
this commit replaces 'grep collectd' with 'grep ^collectd-',
but removes the grep and does the filtering directly in sed.
> Cleanup version-gen.sh

- src/match_regex.c
ChangeLog: match_regex: Accept all data types of meta data
match_regex currently accepts only string type of meta data, but
there is no reason to reject other data types since they can be
easily stringified by meta_data_as_string().
Accepting all data type will provide more benefit, for example
the following config can distinguish that data is local or remote,
the previous match_regex outputs many error logs for this config
though:
```xml
<Match "regex">
MetaData "network:received" "true"
</Match>
```
Signed-off-by: Takuro Ashie <ashie@clear-code.com>
> match_regex: Accept all data types of meta data

- docs/maintainer_guide.md
We moved away from that model and every commit should go
through a review.
> Remove section about self-approve patches

- src/zookeeper.c
ChangeLog: plugin ZooKeeper: Add 'quorum' stat
Add 'quorum' stat to ZooKeeper plugin so that alerts are able to tell the difference between data lag and loss of quorum.
> Add 'quorum' stat to ZooKeeper plugin

- src/utils/format_stackdriver/format_stackdriver.c
JSON does not support NaN values and the Stackdriver POST requests are malformed becuase of cutting the request in the middle.
This change special-cases NaN values and prevents them from being written to the backend.
ChangeLog: write_stackdriver plugin: Fixed NaN value handing with gauge metrics.
> Special case NaN double values for GAUGE metrics.

- contrib/collection.cgi
ChangeLog: contrib collection.cgi: parse types.db to discover DS names
Fixes users, entropy, and ntpd (time_offset/frequency_offset) graphs
that were broken by the great data source name normalization of
collectd v4 -> v5.
> collection.cgi: parse types.db to discover DS names

- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/varnish.c
ChangeLog: varnish plugin: Support for Varnish 6, deprecated 2, 3 and 5.
ChangeLog: varnish plugin: Added counters for vmod-goto.
I keep Varnish 4 because Varnish Software keep support for Varnish Plus 4. Deleted Varnish 2, 3 and 5 because does't maintened: https://varnish-cache.org/releases/
> Support for Varnish 6 and remove Varnish 2, 3 and 5

- src/processes.c
ChangeLog: processes plugin: fix number of running processes 
scanning /proc/*/stat AND computing other process stats takes too much
time. Consequently, the number of running processes based on the occurences
of 'R' as character indicating the running state is typically zero. Due
to processes are actually changing state during the evaluation of it's
stat(s).
The 'procs_running' number in /proc/stat on the other hand is more
accurate, and can be retrieved in one single 'read' call.
In the unlikely case that procs_running can not be retrieved from
/proc/stat, (read interrupted prior to reading up to 'procs_running'
the value '1' assumed, since this plugin is at least being executed.
> Changelog: processes plugin: fix number of running processes

- src/collectd.conf.in
- src/collectd.conf.pod
- src/df.c
- src/utils/ignorelist/ignorelist.c
- src/utils/ignorelist/ignorelist.h
ChangeLog: plugin df: Add LogOnce option
Enabling LogOnce true option in df plugin reduces syslog spam when stat
constantly fails for any of the mounted partitions.
> LogOnce option for df plugin

- src/collectd.conf.in
- src/collectd.conf.pod
- src/gpu_nvidia.c
The plugin instance can now be configured via collectd.conf. Currently, the GPU name is used. However, this does not allow us to distinguish between GPUs of the same type, e.g. in workstations or computing clusters, which often contain multiple GPUs of the same type. 
Hence, I propose to configure the plugin instance of the gpu_cuda plugin via the two booleans 'InstanceByGPUIndex' and 'InstanceByGPUName'. The GPU index is unique for every NVIDIA GPU in the system. Furthermore, this is more in line with the cpu plugin, which uses the core as plugin instance. I set the default to "GpuId-GpuName".
I also replaced MAX_DEVNAME_LEN with NVML_DEVICE_NAME_BUFFER_SIZE from nvml.h.
ChangeLog: GPU NVML plugin: configurable plugin instance by GPU name and/or GPU index.
> configurable plugin instance in gpu_cuda plugin

- src/collectd.conf.pod
- src/tail_csv.c
This PR adds a new option to tail_csv plugin called `FieldSeparator`. The value for this option is a single character. This option is used to define a custom separator. Default will be ',' so the PR is backward compatble.
Closes #2893 
ChangeLog: tail_csv plugin: Adds a FieldSeparator option
> Add a FieldSeaparator option to tail_csv plugin

- AUTHORS
- Makefile.am
- README
- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/slurm.c
- src/types.db
This PR adds a new plugin called slurm that collects node, job and internal health statistics for the SLURM workload manager (see https://slurm.schedmd.com/).
In addition to the plugin implementation in `src/slurm.c`, I added new corresponding types to `types.db`, the relevant bits for autoconf & automake, README docs, collectd.conf manpage bits, collectd.conf.in changes, and the corresponding AUTHORS file contributions update.
Please let me know if I missed anything.
Note that for the auto-generated collectd.conf, I believe it just adds the `LoadPlugin slurm` line, although slurm needs the `Globals true` option to work properly; not sure if it's possible to include the macro magic in the `collectd.conf.in` file to have that option on by default.
Also note that even though I updated …
> Add slurm plugin

- CODEOWNERS
As discussed at the collectd meetup: add a new @collectd/core-maintainers group which owns the daemon and a few plugins that are hand-picked for having a large "blast radius". This is in preparation of adding a bunch of @collectd/trusted-contributors which can then approve PRs for the majority of files in the repository.
> CODEOWNERS: Add "core maintainers" owning daemon and important plugins.

- configure.ac
ChangeLog: Improved check for libjevents which is dependency for intel_pmu plugin
Add a check to provide better information for users who would try to compile the plugin with the old libjevents version.
> intel_pmu plugin: add check for lib symbol in configure.ac

- src/python.c
Add individual error messages required in #2700 
The API PyType_Ready may fail, when it happens, the program may crash.
ChangeLog: collectd: Error-handling code of PyType_Ready has been added.
> Add error handling for PyType_Ready

- src/amqp1.c
- src/collectd.conf.pod
ChangeLog: amqp1 plugin: Add options to limit send queue length.
Add two options to control send queue length and behavior: SendQueueLimit and SendQueueDropNew
If SendQueueLimit is set to an integer greater than 0, the send queue in the
amqp1 plugin will be constrained to that number of entries to avoid unbounded
memory use in the case that there is no amqp1 connection. If the
SendQueueDropNew parameter is set to true, new messages will be dropped when
the queue is full and a new message is enqueued, otherwise the oldest message
in the queue will be dropped. The default is for the oldest message to be
dropped.
Signed-off-by: Ryan McCabe <rmccabe@redhat.com>
> amqp1: Add options to limit send queue length

- Makefile.am
- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/mdevents.c
- src/mdevents_test.c
This plugin, named **mdevents**,  is responsible for gathering the events from RAID arrays that were written to syslog by mdadm utility (which is a user-space software for managing the RAIDs). Then, based on configuration provided by user, plugin will decide whether to send the collectd notification or not. 
Mdevents needs the syslog and mdadm to be present on a platform that collectd is launched.
Based on the naming of existing dpdk plugins (dpdkstat for metrics, dpdkevents for notifications) and the fact that there is already plugin called **md** for gathering metrics from RAIDs, giving this plugin name **mdevents** felt like the best option.
A slight change to ignorelist API was introduced - it is now possible to retrieve the count of nodes in array and the current **ignore** setting …
> New plugin to read RAID events

- src/dpdk_telemetry.c
ChangeLog: Fix build for dpdk-telemetry plugin
Include unistd.h instead of sys/unistd.h to fix the following build
failure on musl:
```
src/dpdk_telemetry.c:43:10: fatal error: sys/unistd.h: No such file or directory
#include <sys/unistd.h>
^~~~~~~~~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/aafb8c72f147fefc7a988c45e4dc17de48b07a95
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> src/dpdk_telemetry.c: fix build on musl

- src/amqp.c
- src/collectd.conf.pod
ChangeLog: amqp plugin: allow multiple hosts to support failover
With this implementation all the hosts must use the same port number. Specifying a different port for each host would be tricky wrt config backwards compatibility and it's not clear how important it is.
> amqp: allow multiple hosts for failover

- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/varnish.c
This is mainly code taken from https://github.com/collectd/collectd/pull/3360, but without losing previous varnish versions.
ChangeLog: varnish plugin: Add varnish 6 support.
ChangeLog: varnish plugin: Add counters for vmod-goto.
> Add varnish 6 support

- src/varnish.c
ChangeLog: varnish plugin: Add target in category for varnish 6
Fixes #2206
I've limited it to varnish 6 because it's the only one I tested, but it should probably works for varnish 5 too.
This basically improve category precision by adding "target" information.
for SMA, targets are s0 or Transient, both of which have large difference, Transient being a small cache (around 20MB here), and s0 the large one (configured via malloc option). examples and explanation here : https://blog.anine.io/varnishstat-varnish-performance-tuning-part-ii-2/
For SMF, it should work the same way based on #2206 example (not tested)
I've also included backend name in VBE stats, for them to be of any use when you have more than one backend.
It's been a while since I've coded in C, so please triple check it :)
> Add target in category for varnish 6

- src/zookeeper.c
Add missing fields for the 3.5 zookeeper version : `zk_last_proposal_size`, `zk_min_proposal_size` and `zk_max_proposal_size`
Note : list of fields in the mntr 4LW can be found here [http://zookeeper.apache.org/doc/r3.5.7/zookeeperAdmin.html#sc_4lw](http://zookeeper.apache.org/doc/r3.5.7/zookeeperAdmin.html#sc_4lw). The current documentation (for the 3.6.0) is not up-to-date
ChangeLog: zookeeper plugin: Add proposal mntr fields
> Zookeeper - Add missing 3.5 mntr fields

- src/mqtt.c
After losing our connection to a MQTT broker our subscription will be gone, too, so we need to subscribe to our topic once again after reconnecting, otherwise collectd will not receive any MQTT messages any more.
ChangeLog: MQTT plugin: Resubscribe after a reconnect
Fixes: #3442
> MQTT: Resubscribe after a reconnect

- src/zookeeper.c
Add missing `zk_open_file_descriptor_count` and `zk_max_file_descriptor_count` mntr fields to handled fields for 3.4 version.
There was, I think, a typo resulting in checking 3 times the `zk_ephemerals_count` field instead of these two missing fields.
ChangeLog: zookeeper plugin: fix missing mntr fields
> Zookeeper - Fix missing Mntr fields

- src/collectd.conf.pod
This question recently came up on the mailing list.
ChangeLog: sensors plugin: The documentation has been improved.
> collectd.conf(5): Document the format expected by "sensors"' ignore list.

- src/ceph.c
`(struct cconn).asok` was implicitly initialized to zero. If connecting to a ceph daemon failed, the field would be left unmodified and `cconn_close()` would eventually close file descriptor 0.
ChangeLog: ceph plugin: An incorrect close on file descriptor 0 has been fixed.
See also: #3455
> ceph plugin: Initialize file descriptor to -1.

- src/types.db.pod
I just wanted to document that data source names must be unique within a data set (see prometheus/collectd_exporter#78) and ended up rewording most of the manpage.
ChangeLog: types.db(5): Documentation of metric definitions has been improved.
> types.db(5): Improve wording and document conventions.

- src/mysql.c
- src/types.db
ChangeLog: mysql plugin: report slave_io_running and slave_sql_running
added reporting of the fields Slave_IO_Running and Slave_SQL_Running as 0 and 1. Needed to catch more cases when replications broke.
I have added an entry to types.db, please advise me which existing type should be used.
> mysql: report slave_io_running and slave_sql_running

- src/intel_pmu.c
ChangeLog: intel_pmu plugin: fix the possible crash on plugin init
If HardwareEvents group in configuration consisted only of events that can't be resolved collectd was crashing during init. Added a check to end the group only if some events were actually added to the group.
> intel_pmu: fix crash after specifying incorrect HardwareEvents

- src/processes.c
If machine has high number of CPUs or interrupts or both, the /proc/stat
can easily grow over current buffer size 4kB. On my current machine (64
cores, ~300 interrupts) the /proc/stat has 12kB of data. And since the
`procs_running` line is after the interrupts it is never read.
Increasing the size to 64KB so it will accommodate even heavier machines.
It would be nice if this would be more dynamic to don't allocate large buffer on smaller machines. I have no idea about the current smallest supported setup by the collectd. Optionally the part could be reprogrammed to read the whole file in 4kB chunks, something similar is already done in `read_fork_rate`.
ChangeLog: Process plugin: Increase reading buffer for /proc/stat
> processes: increase reading buffer for /proc/stat

- src/types.db
- src/ubi.c
ChangeLog: ubi: fix data source type from counter to gauge
Currently the values are stored in the ubi plugin as data source type
`counter`. But this makes no sense, because the values change very slowly
and I don't want to know the rate of change. It is better to store the
value as data source type `gauge`. Then I can see the current value.
> ubi: fix data source type

- src/daemon/configfile.c
ChangeLog: collectd: A special case, mapping "libvirt" to the "virt" plugin, has been removed.
> src/daemon/configfile.c: Remove special case for the "libvirt" plugin.

- Makefile.am
- src/testing.h
- src/utils/common/common.c
- src/utils/common/common_test.c
- src/utils/strbuf/strbuf.c
- src/utils/strbuf/strbuf.h
- src/utils/strbuf/strbuf_test.c
I'm planning on using this code to build the string representation of a label based metric. This certainly will have uses all throughout the daemon though. Looking for "ADD" or "ADDF" macros should uncover places that might benefit from this code.
ChangeLog: collectd: The `strbuf` utility library has been added. It simplifies building strings iteratively.
> strbuf: Library that implements printing to a dynamically allocated buffer.

- Makefile.am
- src/daemon/metric.c
- src/daemon/metric.h
- src/daemon/metric_test.c
- src/daemon/plugin.h
- src/statsd.c
- src/testing.h
- src/utils/format_graphite/format_graphite_test.c
- src/utils/format_json/format_json_test.c
- src/utils/format_stackdriver/format_stackdriver.c
*   `metric_family_t` holds the metric type, metric name, and a list of metrics.
*   `metric_t` holds the value, a label set, collection time, interval, and a pointer to the parent *metric family*.
This another break-out from #3506, trying to make the change easier to review.
ChangeLog: collectd: The new `metric_t` and `metric_family_t` data structures hold metrics that are identified by a label set.
> Implement metric_t and metric_family_t.

- src/capabilities.c
- src/capabilities_test.c
Fixes #3511
ChangeLog: Conditionalize return type for microhttpd callback functions
> capabilities: conditionalize mhd callback return type

- contrib/collection3/etc/collection.conf
Instead of just `{type_instance}` (which is sometimes empty for some data), show `{instance}`. This one contains the former and is more informative.
IMHO this is a minor change and doesn't warrant a `ChangeLog:` entry.
But anyway, to please the CI:
ChangeLog: collection3: Improve some small titles
> collection3: Show instance for Current/Voltage

- Makefile.am
- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/netlink.c
- src/netlink_test.c
- src/types.db
ChangeLog: Add VFs statistics and link info to netlink plugin.
Add option to read statistics and link info for VFs under specified PFs similar to that returned by `ip -s link show`.
Add regexp functionality to match for interface name similar to that of util ignore list.
Buffer size for libmnl is calculated during init as the default one does not work well with big number of VFs.
> Netlink plugin: add option to read VF stats

- Makefile.am
- configure.ac
- distbench/Makefile.am
- distbench/bkjg.c
- distbench/function.h
- distbench/main.c
- distbench/margalit.c
- distbench/run-all.sh
- distbench/sshmidt.c
This adds a “distbench” subdirectory for benchmarking different
implementations of distribution_t and three sample implementations.
ChangeLog: Added a benchmark for distribution metrics.
> [Interns] Add a skeleton for benchmarking distribution_t.

- src/slurm.c
As mentioned in #3037 the Slurm plugin fails to build with Slurm >= 20.02. This PR ensures that it can be built with all Slurm versions.
ChangeLog: Slurm plugin: Provide compatibility with Slurm versions >= 20.02
> slurm: compatibility with Slurm >= 20.02

- contrib/curl_jolokia/curl_jolokia.conf
- contrib/curl_jolokia/jolokia_2_collectdcfg.py
- src/collectd.conf.in
- src/collectd.conf.pod
- src/curl_jolokia.c
ChangeLog: curl_jolokia plugin: integrate jolokia to fetch jmx counters via HTTP/json
Http://jolokia.org is another way to query jmx counters. It breaks the dependency chain by specifying a REST/HTTP API to access the values of http counters.
The module itself is intended to be configured by using the attached python script.
The configuration of the plugin consists of 3 parts:
- URL setup of the servlet container
- the Json Post data, which is a 'BULK-Request' in the nomenclature of jolokia
- a table of matches from the JMX names and their Attributes to the name of the metric on collectd side
The Python script uses the pyjolokia library to access your jolokia host. It queries the list interface of jolokia, which gives you all available beans. it then filters this list by patterns, so you …
> Add client interface for the jolokia.org JMX client.

- src/daemon/metric.c
- src/daemon/metric.h
ChangeLog: Distribution Metrics: Integrated distribution metrics into collectd core.
Added new distribution_t value to metric_type_t enum, added distribution_t* to the value_t pointer, modified function metric_reset to call distribution_destroy when appropriate, added according documentation to metric.h. Modified metric_list_clone to call distribution_clone when appropriate.
> Integrate distribution metrics into collectd core

- Makefile.am
Sorry, I added the ignorelist functionality last-minute in the initial PR (https://github.com/collectd/collectd/pull/3494) and I missed this.
ChangeLog: infiniband plugin: Fix the build by linking with libignorelist.
> infiniband: fix build

- src/curl.c
When AddressFamily field was set in config file in configuration for curl plugin, memory was allocated and pointer was stored in af variable. At the end of block of code, this memory wasn't freed. 
ChangeLog: curl plugin: Fix memory leak
> Fix memory leak in curl plugin

- src/network_test.c
ChangeLog: Avoid empty initialization when gcrypt is absent as it leads to compile error on Sun Studio
> Fix network test

- src/mysql.c
In MariaDB 10.5 information_schema.innodb_metrics was cleaned:
https://github.com/MariaDB/server/commit/d09aec7a15ab4be539d2b110742af544fa6b139f
String column 'status' was replaced with boolean column 'enabled'.
Therefore we need to modify request for fetching data from that table.
Fixes #3533
ChangeLog: mysql: compatibility with MariaDB >=10.5
> mysql: Compatibility with MariaDB >= 10.5

- .cirrus.yml
Regular support for Jessie ended in 2018, LTS in June 2020.
> .cirrus.yml: Remove Debian Jessie.

- src/libcollectdclient/network_parse.c
Fixes the following warning:
```
"src/libcollectdclient/network_parse.c", line 261: warning: initializer does not fit or is out of range: 248
```
ChangeLog: libcollectdclient: A build error on Solaris has been fixed.
> libcollectdclient: Don't initialize a char with 0xF8.

- src/daemon/distribution.c
- src/daemon/distribution_test.c
ChangeLog: Distribution data structure: Avoid deadlocks.
- Unlock locks in `distribution_percentile` and `distribution_average` when `bucket_counter` is 0.
- Call tests second time for deadlocks detection.
> Avoid deadlocks.

- docs/BUILD.dpdkstat.md
- src/collectd-snmp.pod
- src/collectd.conf.pod
- src/mysql.c
- src/sensors.c
- src/utils/format_stackdriver/format_stackdriver.c
This patch leaves out rewrite master/slave from mysql and also
master from snmp.
This repaces blacklist with blocklist, whitelist with allowlist.
ChangeLog: collectd: Fix problematic use of language where possible.
> Rewrite problematic language where possible

- src/snmp_agent.c
Fixes:
```
src/snmp_agent.c:965:9: error: ‘strncat’ output may be truncated copying between 0 and 127 bytes from a string of length 127 [-Werror=stringop-truncation]
strncat(out, str, DATA_MAX_NAME_LEN - strlen(out) - 1);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
ChangeLog: snmp_agent plugin: A `strncat()` truncation warning has been fixed.
> snmp_agent plugin: Fix strncat() truncation warning.

- Makefile.am
ChangeLog: intel_rdt plugin: A build issue of the plugin's unit test has been fixed.
> Makefile.am: Link test_plugin_intel_rdt with libpqos.

- Makefile.am
ChangeLog: Build system: Clean up generated gRPC files when running `make distclean`.
> Makefile.am: Add types.grpc.pb.{cc,h} to CLEANFILES.

- src/netlink.c
ChangeLog: netlink: fix use of REG_NOERROR.
`REG_NOERROR` is used since version 5.12.0 and https://github.com/collectd/collectd/commit/f7fd32e5209e188db7985a42054252fc4cbfe7c1
However, `REG_NOERROR` is not defined by musl, even GNU regex do not mention `REG_NOERROR`, so just remove it to avoid the following build failure:
```
src/netlink.c: In function 'check_ignorelist':
src/netlink.c:243:51: error: 'REG_NOERROR' undeclared (first use in this function); did you mean 'REG_NOTBOL'?
if (regexec(i->rdevice, dev, 0, NULL, 0) != REG_NOERROR)
^~~~~~~~~~~
REG_NOTBOL
```
Fixes:
- http://autobuild.buildroot.org/results/cd4d75888b5259b028132dd224be34f69bcbb702
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> src/netlink.c: remove REG_NOERROR

- src/write_influxdb_udp.c
Hello:
This is a PR to move the build of the influxdb points outside de mutex. Extra memory and a copy operation are needed but this allow write threads to build points in paralell which is convinient in high load environments.
Regards,
Carlos.
ChangeLog: write_influx_udp: build influxdb points outside de mutex.
> write_influx_udp: build influxdb points outside de mutex.

- src/write_http.c
Fix the probable bug inside write_http plugin. For loop by i variable every time takes the same metric from the metric family. Due to the iteration by i, it looks like we should take ith element every time.
ChangeLog: write_http plugin: A bug when iterating over metrics in a metric family has been fixed.
> Fix bug inside write_http plugin

- src/daemon/configfile.c
ChangeLog: configfile.c: Fix memory leaks in case of failure
> configfile.c: Fix memory leaks in case of failure

- .cirrus.yml
ChangeLog: It had been reached EOL at November 30th, 2020.
There is no security updates available anymore.
ref. https://wiki.centos.org/About/Product
> cirrus: drop CentOS6 (EOL)

- src/perl.c
ChangeLog: Perl plugin: add unlock pthread mutex before exit.
Fix a small error due to the unreleased lock by add pthread_mutex_unlock(&perl_threads->mutex) before program exit. #3894
> Fix a small error due to the unreleased lock for 

- src/utils/oauth/oauth.c
- src/utils/oauth/oauth.h
- src/write_stackdriver.c
ChangeLog: Stackdriver plugin: increase OAuth access token buffer size to 2048 to match https://developers.google.com/identity/protocols/oauth2#size
Fixes #3897
> Increase buffer size for oauth access token to 2048

- configure.ac
- src/collectd.conf.pod
- src/nginx.c
Add support for UNIX domain sockets for NGINX servers that listen on a socket.
With this PR, one can serve the `stub_status` module on a socket, which can be more secure and faster than exposing it on a normal port. For example, I use the following NGINX configuration:
```
server {
listen unix:/var/run/nginx.sock;
location /stub_status {
stub_status;
}
}
````
ChangeLog: nginx plugin: Add support for UNIX domain sockets
> nginx plugin: Add support for UNIX domain sockets

- configure.ac
Changelog: typing error in configure.ac for the CPPFLAGS of libredfish.
Probably a copy/paste error: `LIBHIREDFISH_CPPFLAGS` was used instead of
`LIBREDFISH_CPPFLAGS`.
> Fix-configure.ac: typing error for the CPPFLAGS of libredfish

- src/collectd.conf.in
- src/collectd.conf.pod
- src/write_influxdb_udp.c
Hello:
Adding a configuration option to send timestamps with different precision to InfluxDB. #3783
Changelog: write_influxdb_udp: add TimePrecision configuration option
> write_influxdb_udp: add TimePrecision configuration option

- src/utils/match/match.c
ChangeLog: ExcludeRegex in logparser plugin is optional, hence can be NULL. This change fixes debug logging causing CRITICAL error for NULL excluderegex, if debug is enabled.
> Fix debug print of excluderegex if NULL

- src/nut.c
According to [1], there are multiple fields that can indicate the (real)power. Expose the ones under the `ups` and `input` key as well.
Note: naming of the type instances are based on how `output.power` and `output.realpower` are exposed.
[1] https://networkupstools.org/docs/developer-guide.chunked/apas01.html
ChangeLog: nut plugin: Expose more (real)power values
> nut: expose more (real)power

- src/daemon/collectd.c
Changelog: Fix broken "-t" option of collectd command
"-t" option should test config file but it always returns 0 with no
message even if a broken config file is specified.
Signed-off-by: Takuro Ashie <ashie@clear-code.com>
> Fix broken "-t" option of collectd

- src/ubi.c
ChangeLog: ubi: Add percentage value calculation for the bad blocks
@pticon With this change, the percentage error of the flash can be calculated directly in the collectd ubi plugin.
Until now, this had to be done differently.
With this change, the threshold plugin can now triggers an event if there are too many bad erase blocks.
This means that the flash degenerates.
> ubi: add percent calculation

- src/collectd.conf.pod
- src/write_influxdb_udp.c
Changelog: write_influxdb_udp: Implement support for multiple Server entries
It creates one socket for each Server row in the CFG: e.g.
```
LoadPlugin write_influxdb_udp
<Plugin write_influxdb_udp>
Server "some.host.tld" "8585"
Server "some.host.tld" "8686"
Server "192.0.2.1" "8001"
Server "192.0.2.5" "8007"
Server "2001:db8::19" "5000"
</Plugin>
```
Tested on 5.13 and 6.0 code-base.
PS: Not sure which branch to PR against. main? master? 5.13? 6? This applies to each branch cleanly and works. 
This can go into main for release in 5.13, and @carlospeon is re-working the plugin for v6, where this PR also applies there (but small rebase for docs might be necessary).
> Changelog: write_influxdb_udp: Implement support for multiple Server entries

- src/cpusleep.c
ChangeLog: cpusleep plugin: migration to v6.0
> [collectd 6] cpusleep: migration to v6.0

- AUTHORS
- Makefile.am
- README
- configure.ac
- src/collectd.conf.in
- src/mmc.c
- src/types.db
ChangeLog: mmc plugin: initial checkin
This is a new plugin to track performance data of a mmc device.
The information are found in the SSR-register under `/sys/bus/mmc/devices/`
This register does have a common section and a vendor specific section.
Up to now only the vendor `swissbit` is supported to read the specific
informations.
The following information are read:
* Power cycle count
* Block erase count
* Bad blocks in percent
The need values are read from `/sys/bus/mmc/devices/<name>/ssr`.
> mmc: initial checkin

- src/memory.c
This PR introduces reporting 'available' memory for linux kernel when present in meminfo.
Right now a rough estimate to available memory based on the current metrics reported relies on summing (free, buffers, cached) metrics.
This produces an over estimate for the available memory in cases where shared memory is in use.
As the shared memory is counted towards cache, however not reclaimable.
Sample python code to show the issue, with results reported:
```
from multiprocessing import shared_memory
import psutil
def print_mem_stats() -> None:
mem_stats = psutil.virtual_memory()
print("Available:", mem_stats.available / 2**20)
print("Shared:", mem_stats.shared / 2**20)
print("Cached:", mem_stats.cached / 2**20)
def main() -> None:
print("-- Before opening shared memory --")
print_mem_stats() …
```
> Report MemAvailable when present in meminfo

- src/collectd.conf.in
- src/collectd.conf.pod
- src/statsd.c
This PR introduces the `CounterGauge` option for the `statsd` plugin.
This enables compatibility with the reference StatsD implementation, aggregating the increase during the flushing interval, reporting the current value as a differential, and resetting the counter.
Originally this was written by @vmg as a patch against version 5.5.3 to make this the standard behavior. I've adapted it so this behavior is optional and does not interfere with reporting `derive` metrics, similarly to what I saw done with the Etsy option `CounterSum`. We found use for this while performing a Debian dist-upgrade from stretch to buster where we're using a patched collectd version 5.10.0.
ChangeLog: statsd plugin: The CounterGauge option has been added. Thanks to Casey Tucker and Vicent Marti.
> add CounterGauge option in statsd

- src/types.db
ChangeLog: infiniband: Add missing commas  to the infiniband types.
See #3831 for a deeper discussion of this.
> Fix #3831 by adding commas to the infiniband types

- src/smart_test.c
get_vendor_id from smart.c assumes that VENDOR_ID is le16, so we
need to convert it into le16 in the fake-ioctl function in smart_test.c.
Fixes #3791
Signed-off-by: Bernd Zeimetz <bernd@bzed.de>
ChangeLog: smart plugin: Fix tests for big endian architectures.
> Fic smart_test.c for big endian.

- src/redfish.c
Changelog: enabling libredfish logs when collectd debug mode is enforced
In order for `libredfish` to log internal information, which are more
than useful to debugging purposes, a printing function has to be
registered through a hook : a global function pointer named `gDebugFunc`.
The `plugin_log` function is registered as the printing function through
the aforementioned hook by the `redfish_init` function, when the
`--enable-debug` option is specified to the `configure` script.
> Feature-redfish: enabling libredfish logs when collectd debug mode is enforced

- .github/workflows/build.yml
ChangeLog: Add Github actions to replace travis CI
Repeats the steps that travis was using for building collectd
-     checks out branch
-     installs dependencies (either they are already in the container or they are explicitly installed)
-     runs the same script commands as travis ( pkg-config, confgure, make)
> Replace travis CI with GHA

- src/snmp.c
ChangeLog: snmp plugin: Add support for SHA224, SHA256, SHA384 and SHA512.
> snmp plugin: Add support for SHA224, SHA256, SHA384 and SHA512

- src/ovs_stats.c
ChangeLog: ovs_stats plugin: This commit fixes plugin failure while performing the port deletion, which occurs due to wrong incremental condition and if condition.
> bug#3924 fix

- .cirrus.yml
- src/snmp.c
ChangeLog: Remove DES support in SNMP
Taken from https://src.fedoraproject.org/rpms/collectd/c/66239034741115bfc0597d1b90fb3ce9c37ce3d7?branch=rawhide,
originally proposed by Ruben.
OpenSSL removed DES.
Signed-off-by: Ruben Kerkhof <ruben@rubenkerkhof.com>
> Remove DES support in snmp plugin

- src/memory.c
ChangeLog: memory plugin: do not account reclaimable slab as used.
Align this counter with free(1).
https://gitlab.com/procps-ng/procps/-/blob/v3.3.17/proc/sysinfo.c#L789
Signed-off-by: Weiping Zhang <zhangweiping@didiglobal.com>
> ChangeLog: memory plugin: do not account reclaimable slab as used

- src/collectd.conf.in
- src/collectd.conf.pod
- src/intel_rdt.c
Added Memory Bandwidth Total metric to intel_rdt plugin. Added option to disable IPC monitoring as it also collected by intel_pmu plugin.
ChangeLog: intel_rdt: Added option to disable IPC monitoring
ChangeLog: intel_rdt: Added memory bandwidth total metric
> Intel rdt metrics improvments

- src/intel_rdt.c
ChangeLog: intel_rdt: Update intel_rdt to build on libpqos < 2
> [intel_rdt] Fix build for LIBPQOS < 2

- .cirrus.yml
Ubuntu 14.04 (Trusty) is out of standard support [1].
``make check`` fails for test_capabilities, as noted in [2].
[3] indicates that the cause is glibc, but that updates are not expected
to the version in trusty.
This PR replaces trusty with Ubuntu 18.04 (Bionic) and 20.04 (Focal).
[1] https://wiki.ubuntu.com/Releases
[2] https://github.com/collectd/collectd/pull/3936
[3] https://github.com/collectd/collectd/pull/3927#issuecomment-953350598
> [ci][cirrus] Replace trusty with bionic/focal in debian_default_toolchain

- src/disk.c
ChangeLog: Disk:  Added a block device utilization in Linux
An utilization is computed as percentage of elapsed time during which a device has some IO operations currently in progress.
> disk: add utilization

- .cirrus.yml
- .github/workflows/build.yml
* Remove Ubuntu/trusty
* Add Ubuntu/Focal and Ubuntu/Bionic
* Let ``make check`` fail on definite memory leaks only
> Fix CI failures caused by unsupported distros and updates to dependencies

- src/smart.c
This change checks the return value of the function and cancels the call
if the returned integer is not greater than or equal to 0.
ChangeLog: smart: check udev_enumerate_scan_devices() return value and unify log messages
> smart: check udev_enumerate_scan_devices() return value and unify log messages

- .cirrus.yml
It had been reached EOL at November 30th, 2020.
There is no security updates available anymore.
ref. https://wiki.centos.org/About/Product
Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>
(cherry picked from commit d836b9b20c5ac94ce67f826751d9d717ffabb49c)
> cirrus: drop CentOS6

- src/mqtt.c
The mqtt plugin publishes messages including the trailing '\0'-Byte, as can be verified using e.g. the `mosquitto_sub` command with a HEX message formatter:
```
$ mosquitto_sub -t "#" -F "%t: %X"
metrics/loragw1/users/users: 313635323334303737392E3938353A3000
^^
```
While the the MQTT PUBLISH payload is, according to the specification, application specific and most (C-Based) consumers will not notice the trailing '\0'-Byte, it is rather uncommon to publish messages like this.
We stumbled upon this error while using Telegraf to ingest metrics via MQTT, as it is Go-Based and does not use '\0'-terminated strings, leading to issues parsing these '\0'-Terminated strings into numbers.
Fix the off-by-one error by using the result of strlen() as-is.
ChangeLog: mqtt plugin: Fix off-by-one …
> MQTT: fix off-by-one error in published message length

- configure.ac
Changelog: use correct path for libgcrypt-config in configure.ac
```
If you want to compile a source file including the 'gcrypt.h' header
file, you must make sure that the compiler can find it in the directory
hierarchy.  
...
However, the path to the include file is determined at the time the
source is configured.  To solve this problem, Libgcrypt ships with a
small helper program 'libgcrypt-config' that knows the path to the
include file and other configuration options.
```
Closes #2395
> use correct path for libgcrypt-config

- Makefile.am
- README
- configure.ac
- src/mmc.c
- src/types.db
ChangeLog: mmc plugin: add support for generic and sandisk/micron health info
This PR extends the mmc plugin introduced by @feckert in #3887 with the following features:
- Support for the generic health metrics included in the eMMC 5.0 (and later) specification.
- Support for vendor-specific health metrics for micron and sandisk eMMCs.
The new vendor-specific health metrics are read out via `ioctl`s on the `/dev/mmcblk?` devices, while all other metrics are read out from the sysfs. Getting the respective device node for a path in sysfs is a non-trivial task that is solved quite nicely by `libudev`, which is why this PR also ports the plugin to use `libudev`.
I've tested the patch with sandisk and micon eMMCs, but did not have any swissbit devices at hand, so it would be nice if @feckert …
> mmc: add more vendor specific and generic data sources

- src/collectd.conf.pod
- src/virt.c
ChangeLog: Plugin virt: update the XML namespace for Nova
> Fix the virt plugin for Openstack wallaby and later use

- src/processes.c
- src/utils/common/common.c
- src/utils/common/common.h
ChangeLog: add scalloc() calloc wrapper + use it in "processes" plugin
scalloc() calloc wrapper complements already existing smalloc() malloc wrapper, already added to the v6 branch.
In v6 branch, scalloc() is used by the new "gpu_sysman" plugin.
To have user for scalloc() also in v5 branch... I changed calloc() calls which return values were no checked (for Solaris-only ps_read_process() function) in "processes" plugin, to use scalloc() instead.  Unlike the other places in processes.c which gracefully handle calloc() failures [1], scalloc() will just exit collectd with error message.  If this is unwanted, I can drop the processes.c patch.
[1] All other plugins seem to handle calloc failures gracefully.  Some of the test code uses asserts instead.  src/processes.c::ps_read_process() was …
> Add scalloc() and use it in src/processes.c

- src/cgroups.c
- src/conntrack.c
- src/daemon/types_list.c
- src/daemon/utils_cache.c
- src/daemon/utils_cache.h
- src/infiniband.c
- src/libcollectdclient/network_parse.c
- src/logparser.c
- src/statsd.c
- src/table.c
- src/turbostat.c
- src/utils/cmds/flush.c
- src/utils/cmds/putmetric.c
- src/utils/cmds/putval.c
- src/write_prometheus.c
- src/write_syslog.c
- src/write_tsdb.c
ChangeLog: Build: Fix some gcc warnings with more strict checks
Fixes are based on "-O3 -Werror -Wall -Wextra -Wformat-security" output, and partly shared with the v5 fixes in https://github.com/collectd/collectd/pull/3917:
* Properly initialize complex struct
* Fix signed vs unsigned comparison warnings
* Correct "write_prometheus" comment and fix metric family freeing in a loop
* Remove unused functions and function arguments, and when latter cannot be removed, tell compiler that they're not used
> [collectd 6] Fix some gcc warnings with more strict checks

- .github/workflows/build.yml
Fedora 28 is really old, and we now have containers for f35 and f36
> [CI] Update Fedora versions used in GHA

- configure.ac
ChangeLog: build: define PREFIX for later use.
ChangeLog: PREFIX was never defined and therefore set to the
default value `/opt/collectd`. collectd searched in
this path for desired files e.g. typesdb, plugins, etc
no matter if it was configured with `--prefix`.
Replaced `&(int){44}` with `(void *)((size_t)-1)` so
GCC-12 won't complain anymore.
Signed-off-by: lns <matzeton@googlemail.com>
Edit: @mrunge adjust ChangeLog (only one line and a limited number of characters allowed).
> Fix-configure.ac: define PREFIX in config.h

- src/utils/oauth/oauth.c
ChangeLog: increase oauth access token buffer size.
Previous PR was insufficient in fixing #3897.  Increase another OAuth access token buffer to 2048 to match the updated spec from Google.
> Increase buffer for OAuth access token.  Another fix for #3897.

- src/capabilities.c
Returning an anonymous pointer (which is limited to the scope of the function) causes an error when building with the `-Werror` flag.
Tested with: GCC 12.1.0
Test case:
```sh
echo 'void test(int **r) { *r = &(int){44}; }' | gcc -Werror=dangling-pointer -x c -c -o /dev/null -
```
Error:
```
<stdin>:1:25: error: storing the address of local variable '({anonymous})' in '*r' [-Werror=dangling-pointer=]
```
> Fix anonymous connection_state pointer

- src/collectd.conf.in
- src/collectd.conf.pod
- src/csv.c
ChangeLog: CSV plugin: Allow date setting in files generated by the CSV plugin.
> Allow date setting in files generated by the CSV plugin

- src/collectd.conf.pod
ChangeLog: collectd.conf manpage: Correct description of FQDNLookup option.
...of collectd.conf. FQDNLookup uses getaddrinfo() and not gethostname(). 
The `FQDNLookup false` check returns after the hostname was set by using `gethostname()`.
> Correct description of FQDNLookup in manpage

- src/cpython.h
Python 3.11 moves longintrepr.h into cpython sub-directory. However, in this version, longintrepr.h is always included.
ChangeLog: cpython: fix build with Python 3.11
> cpython: fix build with Python 3.11

- src/cpython.h
ChangeLog: cpython: fix build with Python 3.11
Python 3.11 moves longintrepr.h into cpython sub-directory. However, in this version, longintrepr.h is always included.
> [collectd 6.0] cpython: fix build with Python 3.11

- src/collectd.conf.in
- src/collectd.conf.pod
- src/gpu_sysman.c
- src/gpu_sysman_test.c
ChangeLog: gpu_sysman: Add more metric output variants and better control for them
Changes:
* Add "rate" variant flag (3rd one) for MetricsOutput option, and change that option to a bitmask
* Rename MetricsOutput "raw" + "derived" flag names to "counter" + "ratio" ones matching metric names [1]
* Add "ratio" variant to all metric types where L0 API provides limit / max value for the metric (frequency, power, temperature)
* Add "rate" variant for memory BW metric type, in addition to already existing "counter" and "ratio" variants
* All metric types that submit multiple variants, check now these flags, and if metric type is enabled, but none of its output variants are enabled, warning is logged
* Tests for the new metrics + related improvements to the generic sysman plugin test code …
> [collectd 6.0] gpu_sysman: Add more metric output variants and better control for them

- src/collectd.conf.in
- src/collectd.conf.pod
- src/utils/format_influxdb/format_influxdb.c
- src/utils/format_influxdb/format_influxdb.h
- src/write_http.c
- src/write_influxdb_udp.c
ChangeLog: format_influxdb: add config option to write metadata
In #3938 the feature to write meta data to influxdb was added. This adds more labels and indexes to influxdb and could not be always desirable. 
This PR adds a configuration option to enable this feature, disabled by default to keep the previous versions of write_influxdb_udp plugin behavior.
> format_influxdb: add config option to write metadata

- src/daemon/plugin.c
ChangeLog: plugin.c: fix drop probability
The higher is the position p in the window between min and max thresholds the higher must be the probability to drop. (ie, p=0, returns false and p=1 returns true).
> plugin.c: fix drop probability

- src/utils/format_json/format_json.c
ChangeLog: write_http plugin: Allow Alertmanager correlation and resolve.
In order to resolve alerts in Alertmanager:
- Move "severity" from labels to annotations, so "OKAY" notifications can match non okay notifications.
- Add "endsAt" date for "OKAY" notifications to clear the alert.
- Fix meta keys with invalid char ':', i.e. "network:received=true"
> Allow Alertmanager correlation and resolve, fix meta names with ':'

- src/apple_sensors.c
- src/battery.c
- src/disk.c
ChangeLog: Build system: Use IOMainPort over deprecated IOMasterPort
In macOS 12, `IOMasterPort`/`kIOMasterPortDefault` is deprecated in favor of `IOMainPort`/`kIOMainPortDefault`:
```
src/battery.c:250:7: error: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Werror,-Wdeprecated-declarations]
kIOMasterPortDefault, IOServiceNameMatching("battery"), &iterator);
^~~~~~~~~~~~~~~~~~~~
kIOMainPortDefault
```
> Use IOMainPort over deprecated IOMasterPort

- src/ovs_stats.c
ChangeLog: ovs_stats: fix stat value rollover
`iface->stats` is an `int64_t`, `ovs_stats_submit_one` expects a `derive_t` for the value parameter and  `derive_t` is `typedef int64_t`. 
The use of the intermediate `int` 32-bit variable `value` in `ovs_stats_get_port_stat_value` will cause rollovers every 2 GiB when trying to monitor octets sent via an interface, causing the next 2GiB to have negative data, from which no sensible graphs can be generated. This patch fixes that issue.
> use derive_t instead of int inside ovs_stats_get_port_stat_value

- src/collectd.conf.pod
ChangeLog: Mdevents plugin: Fixed the display of the events table in the manpage.
The table of mdadm events for `mdevents` plugin is incorrectly displayed in the preview and  in generated manpages.
> Fix formatting in mdadm events table

- contrib/curl_jolokia/curl_jolokia.conf
- src/snmp.c
ChangeLog: snmp plugin: Compile issue fixed if net-snmp has NETSNMP_DISABLE_MD5 set
> Fix md5 compile issue

- .cirrus.yml
- .github/workflows/build.yml
Hi,
we've found some differences in the way the CI behaves between the `main` and the `collect-6.0` branches in #4077.
This PR cherry-picks all changes to `.cirrus.yml` and `.github/workflows/build.yml` from `main` on top of `collectd-6.0`.
Changes introduced here that were not in `main`/`collectd-6.0` are:
- Usage of `on_failure:` instead of `|| cat … || false` in the `.cirrus.yml` to print a log on failure. This matches the what 1b040d7cd0a8d8fcabdd8952a48e97045de9d508 already did in the `collectd-6.0` branch and is imho prettier.
- Trigger on changes to the `collectd-6.0` branch in the GitHub action config instead of `main`.
My only experience with these CI runners is them flagging my pull requests as bad, so feel free to comment if something looks wrong.
The GitHub worker config will …
> [collectd 6] Cirrus CI / GitHub Workers - sync config with main branch

- contrib/snmp-data.conf
ChangeLog: Update the format of snmp-data.conf file to not issue deprecation warning on startup.
s/InstancePrefix/TypeInstancePrefix/g
s/Instance/TypeInstanceOID/g
Signed-off-by: Vit Kabele <vit@kabele.me>
> Update the format of contrib/snmp-data.conf

- src/memory.c
ChangeLog: memory plugin: bring to feature parity with main branch
The `memory` plugin is already ported to the v6 API but some new features have been added in the `main` branch in the meantime.
This PR should bring the `memory` plugin in the collectd-6 branch to feature parity with the `main` branch by:
- Replicating the feature introduced in #3916 (Report MemAvailable when present in meminfo)
- Cherry-Picking #3880 (do not account reclaimable slab as used)
- Cherry-Picking #3962 (add laundry and user wired pages)
> [collectd 6] src/memory.c: bring to feature parity with main branch

- src/apple_sensors.c
- src/battery.c
- src/disk.c
ChangeLog: disk plugin: migration to v6.0
This PR takes up the work by @manuelluis in #3809, rebases it on top of the most recent `collectd-6`-branch and cherry-picks the two commits affecting this plugin from the `main` branch that were added in the meantime (#3967 and #4025).
This should bring the plugin to feature parity with the `main` branch.
Issue #3620 tracks the `disk` plugin migration progress. As far as I can tell this PR should tick the Update the exec plugin to produce a metric_family_t check mark.
> [collectd 6] disk: migration to v6.0

- src/hugepages.c
ChangeLog: hugepages plugin: Skip reading write-only file `demote` in hugepages directory
Since 'demote'[1] is a write-only file do not attempt to read it. This also prevents the plugin from generating incessant logs about the failure to open it.
Fixes: #3993
[1] https://docs.kernel.org/admin-guide/mm/hugetlbpage.html
> Hugepages plugin skips reading write-only file

- src/vmem.c
ChangeLog: Vmem plugin: A feature  supporting metrics start with "pgscan_" in Kernel Linux was added.
Some Linux Kernel versions have metrics start with "pgscan_" in /proc/vmstat, for instance:
```
cat /proc/vmstat | grep pgscan
pgscan_kswapd 0
pgscan_direct 0
pgscan_direct_throttle 0
```
> vmem: add metrics start with "pgscan_" in Kernel Linux

- src/write_stackdriver.c
ChangeLog: write_stackdriver plugin: A memory leak has been fixed
The `payload` was never freed. This was affecting potentially every call to both the "write" and "flush" callbacks.
> Fix a memory leak in the `write_stackdriver` plugin

- configure.ac
- src/bind.c
ChangeLog: Avoid an implicit declaration of timegm in src/bind.c, and build failures with future compilers
The way strptime is activated using feature macros, _DEFAULT_SOURCE (successor to _BSD_SOURCE) is disabled implicitly, so timegm is hidden.  Defining _DEFAULT_SOURCE at the same time as the other feature macros solves this, and removes the need for the TIMEGM_NEEDS_BSD configure macro.
This avoids an implicit declaration of timegm in src/bind.c, and build failures with future compilers.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
[edit mrunge: added a changelog line]
> Fix glibc feature macro handling for timegm

- src/collectd.conf.in
- src/cpufreq.c
Hi, there is an error report "cpufreq plugin: Found too many frequency states (21 > 20). Plugin needs to be recompiled. Please open a bug report for this." on our machines. 
We are using Nvidia's ARMv8 processors and Linux kernel based on 4.14.150. We find that there are more than 20 in cpu's freq table:
```
cat /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state | wc -l
23
```
We try to resolve this by making MAX_AVAIL_FREQS a configurable variable in conf file in order to avoid recompiling. And  it is tested on our machines (we make MAX_AVAIL_FREQS to 30 in our conf files).
Please help review if this idea works, if not, should we simply change MAX_AVAIL_FREQS into a bigger one? 
Thanks a lot!
ChangeLog: cpufreq: make MAX_AVAIL_FREQS configurable in conf
> cpufreq: dynamically alloc MAX_AVAIL_FREQS according to time_in_state

- src/gpu_sysman.c
- src/gpu_sysman_test.c
ChangeLog: gpu_sysman plugin: Misc improvements
Improvements:
* Much improved logging of enabled/disabled metrics [1]
* Log device (memory) ECC state at start
* Add memory types from L0 v1.3 spec
* Fix error value for power limit failure log message
----
[1] Plugin supports large number of Sysman provided metrics.  It tries each metric, logs failure for each missing one, and disables further queries for that.  However, it could be hard to determine which metrics are actually enabled in the end, especially for older integrated GPUs which provide data only for couple of metrics.
After this change, plugin will log a list of the enabled (and disabled) metrics at end of query round, if the enabled metric set changed (which should happen only few times start startup).
> [collectd 6] Sysman plugin improvements

- src/collectd.conf.in
- src/collectd.conf.pod
- src/processes.c
Changelog: add contextswitches a configurable option & use buffer to read /proc/stat 's content only once
We already have a plugin "contextswitch" to collect "ctxt" in "/proc/stat" in Linux. But since we also read from "/proc/stat" from plugin "processes". We add an option to enable "contextswitch" in plugin "processes", default disabled. For this feature, please see 58a1e09e88f2cce1640a4072f7527c54832901d6 
Also, we find that we open and read "/proc/stat" repeatedly when we read "procs_running" and "fork_rate", so we also patch this by only reading "/proc/stat" once into a buffer and making "procs_running", "fork_rate" and "contextswitch" read from this buffer. For this feature, please see de2d033ba5ccd1531caab2e3772d471c219671eb
Tested on my local Linux machines; please help review. …
> processes: add contextswitches a configurable option & use buffer to read /proc/stat 's content only once

- README.md
ChangeLog: Renamed README to markdown and added TOC
Making a start on #3052 to improve readability of the README.
I have only changed the file-name and added a TOC for this PR.
> ChangeLog: Renamed README to README.md and added TOC.

- src/vmem.c
Changelog: add metrics starting with `pgrefill`
Same issue as I submit here: https://github.com/collectd/collectd/pull/4093
In newer Linux Kernel, there is only `pgrefill` instead of `pgrefill_*`, so we should add `pgrefill` into consideration. 
But maybe we should discuss if we have to keep the previous `pgrefill_` logic? Since `pgrefill` would also add all `pgrefill_*` into `refill`. 
Please help review, thanks a lot!
> vmem: add metrics starting with `pgrefill`

- src/amqp1.c
Debug messages are only available if collectd is compiled with debug enabled, making it hard to troubleshoot the situation where the amqp queue is being overrun.
I think dropping metrics merits a "warning", but could be negotiated down to pretty much any level above debug :)
> Change AMQP queue drops from DEBUG to WARNING

- src/collectd.conf.pod
- src/gpu_sysman.c
ChangeLog: gpu_sysman: fix initial min memory check value
...for GPUs with larger amounts of memory, and clarify in doc why non-standard units are used for counters, although SI units would be desirable.
> [Collectd 6] gpu_sysman: fix initial min memory check value

- contrib/postgresql/README.md
- contrib/postgresql/collectd_insert2.sql
Changelog: contrib/postgresql: Second postgresql database layout.
Motivation for that second possible postgresql layout:
------------------------------------------------------
The first layout from Sebastian 'tokkee' Harl is like that:
```
+-------------------+  +----------------+
|Identifiers        |  |values          |
+-------------------+  +----------------+
|ID          int   <-- >ID        int   |
|plugin      text   |  |tstamp    time  |
|plugin_inst text   |  |name      text  |
|type        text   |  |value     double|
|type_inst   text   |  |                |
+-------------------+  +----------------+
```
The ID connects the two tables. The plugin, plugin_inst, type and tpye_inst
create s so called identifier. The timestamp, name and value get inserted into
the value table. …
> Create a postgresql database with a table layout.

- src/write_prometheus.c
Fixes #4150
write_prometheus uses getaddrinfo to resolve the bind address. The AI_ADDRCONFIG flag causes getaddrinfo to refuse to resolve 0.0.0.0 when the system has no non-loopback IPv4 addresses configured and refuse to resolve :: when the system has no non-loopback IPv6 configured.
We want binding to a wildcard address (0.0.0.0 or ::) to always work, even if the network is down.
To achieve that, don't pass the AI_ADDRCONFIG flag when resolving a bind address.
Changelog: write_prometheus: fixed failing to listen on wildcard address before network is up
> write_prometheus: don't use AI_ADDRCONFIG for resolving bind address

- src/intel_rdt.c
Currently the compilation fails on a number of systems with the following error:
```
CC       src/intel_rdt_la-intel_rdt.lo
../../src/intel_rdt.c: In function 'rdt_config_events':
../../src/intel_rdt.c:49:54: error: 'PQOS_PERF_EVENT_LLC_REF' undeclared (first use in this function); did you mean 'PQOS_PERF_EVENT_LLC_MISS'?
PQOS_MON_EVENT_TMEM_BW | PQOS_MON_EVENT_RMEM_BW | PQOS_PERF_EVENT_LLC_REF)
^~~~~~~~~~~~~~~~~~~~~~~
../../src/intel_rdt.c:568:13: note: in expansion of macro 'RDT_EVENTS'
events &= RDT_EVENTS;
^~~~~~~~~~
../../src/intel_rdt.c:49:54: note: each undeclared identifier is reported only once for each function it appears in
PQOS_MON_EVENT_TMEM_BW | PQOS_MON_EVENT_RMEM_BW | PQOS_PERF_EVENT_LLC_REF)
^~~~~~~~~~~~~~~~~~~~~~~
../../src/intel_rdt.c:568:13: note: in expansion of macro …
```
> Intel RDT: fix compilation with libpqos < 4.4.

- src/valgrind.suppress
Currently, `make check` fails on some platforms because libvirt is leaking memory:
```
==157492== 61 (48 direct, 13 indirect) bytes in 1 blocks are definitely lost in loss record 316 of 548
==157492==    at 0x484982C: calloc (vg_replace_malloc.c:1554)
==157492==    by 0x50DFB40: g_malloc0 (in /usr/lib64/libglib-2.0.so.0.6800.4)
==157492==    by 0x4983C19: virClassNew (in /usr/lib64/libvirt.so.0.9003.0)
==157492==    by 0x4B918D9: ??? (in /usr/lib64/libvirt.so.0.9003.0)
==157492==    by 0x4F20A77: __pthread_once_slow (in /usr/lib64/libc.so.6)
==157492==    by 0x499974A: virOnce (in /usr/lib64/libvirt.so.0.9003.0)
==157492==    by 0x4B91D7A: virGetConnect (in /usr/lib64/libvirt.so.0.9003.0)
==157492==    by 0x4B503EF: ??? (in /usr/lib64/libvirt.so.0.9003.0)
==157492==    by 0x4B51277: …
```
> Add Valgrind suppression for libvirt memory leak.

- src/write_mongodb.c
When a `size_t` is a 64bit integer, the 16 byte buffer could potentially overflow. Fix this by using a larger buffer and also collectd's own `ssnprintf()` function which guarantees to result in a null terminated string.
```
In function 'wm_create_bson',
inlined from 'wm_write' at src/write_mongodb.c:229:17:
src/write_mongodb.c:99:32: error: '%zu' directive output may be truncated writing between 1 and 20 bytes into a region of size 16 [-Werror=format-truncation=]
99 |     snprintf(key, sizeof(key), "%" PRIsz, i);
|                                ^~~
src/write_mongodb.c: In function 'wm_write':
src/write_mongodb.c:99:33: note: format string is defined here
99 |     snprintf(key, sizeof(key), "%" PRIsz, i);
```
> Write MongoDB plugin: fix format trunction errors.

- src/intel_rdt.c
Newer versions of the pqos library deprecate the previous function, so we have to migrate even though it makes memory management quite ugly.
This should fix the build on Debian Sid ("unstable").
ChangeLog: Intel RDT plugin: support for PQOS ≥5.0.0 has been added.
> Intel RDT plugin: use `pqos_mon_start_pids2()` if available.

- configure.ac
- src/amqp.c
warning "amqp.h is deprecated, use rabbitmq-c/amqp.h instead."
> Fix compile warning for amqp

- .github/workflows/build.yml
This removes old and unsupported Linux distros:
*   Ubuntu 16 ("Xenial", support ended April 2021)
*   Ubuntu 18 ("Bionic Beaver", support ended June 2023)
*   Enterprise Linux 7 (technically still supported, but nine years old
at this point)
*   Fedora 34 (support ended June 2022)
*   Fedora 35 (support ended December 2022)
Fedora 36 is also unsupported. We will keep the builder until we have never versions of Fedora available (or at least Rawhide builds again).
> Build workflow: remove old distros.

- src/netlink_test.c
- src/smart.c
Valgrind complains about a conditional jump based on uninitialized memory:
```
==66438== Conditional jump or move depends on uninitialised value(s)
==66438==    at 0x10CA06: vf_info_submit (in /__w/collectd/collectd/test_plugin_netlink)
==66438==    by 0x1110F2: test_vf_submit_test (in /__w/collectd/collectd/test_plugin_netlink)
==66438==    by 0x112EAC: main (in /__w/collectd/collectd/test_plugin_netlink)
```
This is likely caused by the `vf_stats_t` being only partially initialized. Using a struct initializer is not only cleaner, it also ensures the remainder of the struct is initialized to zero.
> Netlink plugin: complete initialize structs used for testing.

- configure.ac
- src/gmond.c
`<gm_protocol.h>` has been removed in new versions of *libganglia*.
Additionally, `<rpc/types.h>` has been removed from glibc and is not in the `/usr/include/tirpc` subdirectory instead.
This fixes the gmond plugin on Debian 12 ("Bookworm") and later.
ChangeLog: gmond plugin: Compatibility fixes for new versions of libganglia have been applied.
> gmond plugin: Import `<ganglia.h>`.

- configure.ac
Deal with versions of libupsclient where `<upsclient.h>` is not self contained (it needs `<time.h>`), see networkupstools/nut#1638. This has been fixed upstream in networkupstools/nut#1641 but Debian Bookworm contains the faulty version.
ChangeLog: NUT plugin: Compatibility with new versions of libupsclient has been improved.
> NUT plugin: improve support for faulty versions of libupsclient.

- src/daemon/cmd.c
- src/daemon/cmd.h
- src/daemon/collectd.c
ChangeLog: Daemon: The interaction with Upstart and Systemd has been improved.
Fixes: #4152
> Notify upstart/systemd after initialization is complete.

- .cirrus.yml
- .github/workflows/build.yml
- src/procevent.c
- Update list of compilers used by the "bleeding_edge_compilers_task"
- Add build with `--enable-debug` to GitHub Workflow
- Add build with `CC=clang` to GitHub Workflow.
- Rename `config_flags` to `configure_flags`.
> Improve CI workflows

- src/collectd.conf.pod
- src/gpu_sysman.c
- src/gpu_sysman_test.c
ChangeLog: gpu_sysman: improve metric variants handling
In https://github.com/collectd/collectd/pull/4047 PR, Sysman plugin added option for controlling which variant(s) for the same base metric value are reported (e.g. joules counter, its rate as watts, or ratio of that compared to max power).  Reason being that while they each are useful in different situations, having all of them enabled (=default) can on some HW produce overwhelming amount of data (unless one disables some metric types).
This PR extends that support to cover all metrics:
* Memory usage, frequency, and temperature metrics had only partial support earlier
* I changed "counter" variant to a "base" one that includes both "counter" and "gauge" style base metrics (I did not want to have multiple variant names for Sysman …
> [Collectd 6] gpu_sysman: improve metric variants handling

- src/mysql.c
Fixes: #4137
ChangeLog: MySQL plugin: Incorrect WSREP/Galera metric types have been fixed.
> MySQL plugin: Fix incorrect WSREP/Galera metric types.

- src/cpu.c
- src/df.c
- src/disk.c
- src/memory.c
[OpenTelemetry Enhancement Proposal \#119](https://github.com/open-telemetry/oteps/blob/main/text/0119-standard-system-metrics.md) outlines names for a few commonly tracked system metrics, such as CPU, disk, and memory usage. This change intends to change the emitted metrics of the appropriate plugins to match this naming schema.
This includes merging metric families in the disk and df plugins, which have previously used separate metric families for the read and write "direction".
ChangeLog: CPU, DF, Disk, and Memory plugins: Metric names have been updates to conform to OTEP 119.
> Update standard system metric names in accordance with OpenTelemetry.

- configure.ac
This fixes the build on FreeBSD.
> configure: Disable the write_http plugin if libyajl2 is not found.

- src/write_http.c
- src/write_riemann.c
- src/write_stackdriver.c
- src/write_syslog.c
- src/write_tsdb.c
This outlines an alternative fix to the problem described in #4117.
The idea is to fix the plugins rather than make the plugin's memory management a problem of the shutdown code in `src/daemon/plugin.c`. By adding a reference count, it doesn't matter in which order the various callbacks are shut down in the daemon code.
I hope that the same approach can be used to fix other affected plugins (write_riemann, write_stackdriver, write_syslog, write_tsdb), but I have not verified that yet.
> [collectd 6] add reference counting to plugins that register multiple callbacks with the same `user_data_t`.

- Makefile.am
- src/daemon/metric.c
- src/daemon/metric.h
- src/daemon/metric_test.c
- src/daemon/plugin.c
- src/daemon/resource.c
- src/daemon/resource.h
- src/utils/format_graphite/format_graphite.c
The internal data structure in collectd 6 is closely modeled after [OpenMetrics](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md). This is, for example, where the term "metric family" originates.
In the mean time, [OpenTelemetry](https://opentelemetry.io/) has emerged as the de-facto industry standard for metrics, in particular in "cloud native" environments. I think it is prudent to ensure collectd 6 is compatible with OpenTelemetry and integrates well into this ecosystem.
Most concepts translate well and don't require changes to our internal data structures. However, there is one important differentiation:
OpenTelemetry specifies two sets of "attributes" (aka. labels): "metric attributes" and "resource attributes". For former is equivalent to the …
> [collectd 6] RFC: Add resource attributes.

- Makefile.am
- src/daemon/metric.c
- src/daemon/metric.h
- src/utils/resource_metrics/resource_metrics.c
- src/utils/resource_metrics/resource_metrics.h
- src/utils/resource_metrics/resource_metrics_test.c
OpenTelemetry groups metric families by their `resource` field. This is going to be used by two upcoming changes:
* #4180 
* #4188
> [collectd 6] New utility: `resource_metrics` to group metrics by resource.

- src/utils/common/common.c
- src/utils/common/common.h
- src/utils/common/common_test.c
- src/utils/value_list/value_list.c
Legacy metrics, i.e. metrics reported with the `value_list_t` data structure, need to be upgraded to `metric_family_t`.
The new code puts all metrics into the `collectd.v5` namespace. The metric family name is:
* `collectd.v5.${plugin}.utilization` for metrics with `type` "percent".
* `collectd.v5.${plugin}.io` for *directional metrics* ending in `_octets`.
* `collectd.v5.${type}.${data_source}` for metrics with more than one data source (except *directional metrics*).
* `collectd.v5.${type}` for metrics with one data source.
If the `hostname` field is set, it is translated into the `host.name` resource attribute. Otherwise resource attributes are omitted to trigger the default behavior (like an empty `hostname` field does).
The labels depend on whether plugin instance, type instance, or …
> [collectd 6] Generate better names and labels for legacy metrics.

- src/gpu_sysman.c
This metric is already added to the metric family in line 1553. Adding it twice leads to `uc_update` errors.
Fixes: #4200
> [collectd 6] gpu_sysman plugin: Fix double reporting of metric.

- .github/workflows/build.yml
It is too old to work with `actions/checkout@v4`.
This is a prerequisite for #4180
> [collectd 6] .github/workflows/build.yml: Remove Ubuntu Bionic.

- Makefile.am
With this change `libplugin_mock` contains more of the symbols provided by the collectd daemon, making it easier to link unit tests, especially for plugins.
> [collectd 6] Link more things into `libplugin_mock.la`.

- Makefile.am
- src/utils/cmds/putval.c
- src/utils/cmds/putval_test.c
- src/utils/common/common.c
- src/utils/common/common.h
- src/utils/common/common_test.c
While looking into #4119, I wanted to ensure that the provided timestamp is parsed correctly.
> cmds: Add a unittest for `cmd_parse_putval`.

- Makefile.am
- configure.ac
- src/utils/strbuf/strbuf.c
- src/utils/strbuf/strbuf.h
- src/utils/strbuf/strbuf_test.c
- src/write_prometheus.c
- src/write_prometheus_test.c
ChangeLog: Write Prometheus plugin: Escaping for metric and label names has been added. Test coverage has been improved.
Fixes: #4204
> [collectd 6] Write Prometheus plugin: Ensure metric and label names are properly formatted.

- contrib/collection3/lib/Collectd/Graph/Common.pm
ChangeLog: When using collection3 as a CGI, the following error is sent to logs
repeatedly.
FastCGI sent in stderr: "CGI::param called in list context from
/usr/share/doc/collectd-core/examples/collection3/lib/Collectd/Graph/Common.pm
line 529, this can lead to vulnerabilities. See the warning in
"Fetching the value or values of a single named parameter" at
/usr/share/perl5/CGI.pm line 412"
This is caused inappropriate usage of param(), it should be handled as
a scalar or should be treated by multi_param() explicitly.
Signed-off-by: Kentaro Hayashi <kenhys@gmail.com>
> collection3: fix inappropriate usage of CGI:param

- src/gpu_sysman.c
ChangeLog: gpu_sysman: fix minimum memory usage calculation
Use all the available memory (instead of too small value) as the initial "too large" comparison value (against the sampled free memory amounts array items).
> [collectd 6] gpu_sysman: fix minimum memory usage calculation

- Makefile.am
- src/collectd.conf.in
- src/collectd.conf.pod
- src/daemon/configfile.c
- src/daemon/resource.c
- src/daemon/resource.h
ChangeLog: daemon: The new "Resource" option allows users to configure resource attributes manually if desired.
> [collectd 6] Add an option to configure resource attributes.

- src/daemon/metric.c
- src/daemon/metric.h
- src/daemon/metric_test.c
The size parameter passed to `memmove` was in number of pairs, not bytes.
ChangeLog: Daemon: Memory corruption in the "label_set_delete" function has been fixed.
> [collectd 6] src/daemon/metric.c: Fix memory corruption in `label_set_delete`.

- Makefile.am
- src/daemon/metric.c
- src/daemon/metric.h
- src/utils/resource_metrics/resource_metrics.c
- src/write_prometheus.c
- src/write_prometheus_test.c
This PR aims to implement the "target info" metrics described in the [guidance on push based systems from the OpenMetrics spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#supporting-target-metadata-in-both-push-based-and-pull-based-systems). It also heavily relies on guidance provided in https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/.
* Calculate a set of all resources, called `target_info_t`.
* Emit a `target_info` gauge metric family.
* Emit one `target_info` metric for each "resource" in the set. The resource attributes `service.name` and `service.instance.id` are mapped to the special Prometheus labels `job` and `instance` respectively. Resource attributes are only emitted once, in the special "target …
> [collectd 6] Improve Write Prometheus' handling of resource attributes.

- Makefile.am
- src/daemon/metric.c
- src/daemon/metric_test.c
- src/utils/utf8/utf8.c
- src/utils/utf8/utf8.h
- src/utils/utf8/utf8_test.c
Source: https://opentelemetry.io/docs/specs/semconv/general/attribute-naming/
ChangeLog: Daemon: All valid UTF-8 strings are now accepted as resource attribute name and metric label name.
> [collectd 6] Allow arbitrary UTF-8 strings as label names.

- Makefile.am
- src/daemon/metric.c
- src/daemon/metric.h
- src/daemon/plugin.c
- src/daemon/unit.c
- src/daemon/unit.h
Both, OpenMetrics and OpenTelemetry require that metrics specify their unit, such as "bytes per second". See for example OpenTelemetry's [Metrics Semantic Conventions](https://opentelemetry.io/docs/specs/semconv/general/metrics/#instrument-units).
This adds a `unit` field to the `metric_family_t` field and automatically populates it based on the metric family name, if possible.
ChangeLog: daemon: A unit field has been added to the metric family struct.
> [collectd 6] Add a `unit` field to the `metric_family_t` struct.

- src/write_prometheus.c
- src/write_prometheus_test.c
Reference: https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/#metric-metadata-1
ChangeLog: Write Prometheus plugin: Units are appended to metric family names if available.
> write_prometheus plugin: Use the `unit` field to create metric names.

- configure.ac
ChangeLog: lua: add fallback to detect LuaJIT
Before:
LIBLUA_PKG_CONFIG_NAME=luajit ./configure --enable-lua
After:
./configure --enable-lua
In the previous versions, for enabling LuaJIT,
it needs to specify LIBLUA_PKG_CONFIG_NAME=luajit explicitly.
In this commit, add fallback to detect LuaJIT without specifying
LIBLUA_PKG_CONFIG_NAME=luajit explicitly by default (just use
--enable-lua).
Note that if both of lua and luajit exists, then lua is used.
> lua: support to detect LuaJIT automatically

- src/memory.c
* The "state" label has been renamed to "system.memory.state".
* Metric descriptions and units have been added.
ChangeLog: Memory plugin: The metric schema has been aligned with OpenTelemetry semantic conventions.
> [collectd 6] memory plugin: Align metrics with OpenTelemetry recommendations.

- .cirrus.yml
- .github/workflows/build.yml
- .github/workflows/distcheck.yml
- .gitmodules
- Makefile.am
- build.sh
- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/daemon/metric.c
- src/daemon/metric.h
- src/utils/format_open_telemetry/format_open_telemetry.cc
- src/utils/format_open_telemetry/format_open_telemetry.h
- src/write_open_telemetry.cc
This adds a new plugin that exports metrics to an [OpenTelemetry Collector](https://opentelemetry.io/docs/collector/) using the *OpenTelemetry Protocol* (OTLP) over gRPC.
This is intended as an MVP and comes with many limitations, e.g.:
* Communication is synchronous and blocks the write thread
* TLS is not yet supported
* ~The [Resource field](https://opentelemetry.io/docs/concepts/resources/) is unset (→ see #4187)~
ChangeLog: Write OpenTelemetry: A new plugin for exporting metrics using the OpenTelemetry Protocol over gRPC has been added.
> [collectd 6] Write OpenTelemetry: New plugin to export metrics via OTLP over gRPC.

- src/collectd-lua.pod
- src/lua.c
- src/utils_lua.c
- src/utils_lua.h
ChangeLog:  Add functions to register some missing callbacks
* register_init
* register_shutdown
* register_config
In this version, the configuration for each Script is
supported.
```
Script "foo.lua"
Script "bar.lua"
<Module "foo.lua">
Key Value
</Module>
<Module "bar.lua">
Key Value
</Module>
```
The scope of accessible key-value pair is limited to under <Module>
This feature is similar to collectd-python.
ref. https://collectd.org/documentation/manpages/collectd-python.html
> lua: Add functions to register some missing callbacks

- src/write_riemann.c
`riemann_event_set` is a variadic function, that means it accepts a variable number of arguments. That means it needs some way to determine – at runtime – how many arguments there are. It appears to be doing so by using `RIEMANN_EVENT_FIELD_NONE` to indicate the last element in the argument list. Unfortunately I was unable to find the library's documentation and code and could not verify this.
That means that the argument list passed to `riemann_event_set` was not always terminated, causing it to read past where it was supposed to and adding random crap into the message it crafted.
ChangeLog: Write Riemann plugin: An out of bounds memory read, resulting in garbled messages, was fixed.
Issue: #4050
> write_riemann plugin: Terminate `riemann_event_set` arguments with `RIEMANN_EVENT_FIELD_NONE`.

- src/collectd-lua.pod
- src/lua.c
- src/utils_lua.c
ChangeLog: lua: add missing notification callback
* register_notification
In this version, it support callback function something like:
```
function notification(notif)
print(inspect(notif))
return 0
end
collectd.register_notification(notification)
```
It accepts PUTNOTIF event via plugin_dispatch_notification then you can  handle it.
>  lua: add missing notification callback

- src/utils/common/common.c
- src/utils/common/common.h
- src/utils/common/common_test.c
While `sstrncpy` guarantees a null terminated string, some compilers don't get the memo and complain about the buffer size being equal to the size provided to *strncpy(3)*. This *is* a potential source of error with *strncpy(3)*, because if the source string is longer than the buffer, the buffer is not null terminated. That is the precise reason `sstrncpy` exists in the first place.
Make these compilers happy by decreasing the size passed to *strncpy(3)* by one.
**Update:** After a discussion with @eero-t I decided to improve the overall `sstrncpy` semantics to handle all inputs gracefully.
ChangeLog: collectd: The `sstrncpy` utility function has been improved to handle all inputs gracefully.
> [collectd 6] feat: Improve `sstrncpy` semantic.

- src/interface.c
https://opentelemetry.io/docs/specs/semconv/system/system-metrics/#network-metrics
ChangeLog: Interface plugin: The metric schema has been aligned with OpenTelemetry semantic conventions.
> [collectd 6] interface plugin: Align metrics with OpenTelemetry recommendations.

- src/collectd.conf.in
- src/collectd.conf.pod
- src/memory.c
Another round of improvements for the *memory plugin*:
* Report the `system.memory.utilization` metric as a fraction. Previously, the metric family's unit was `1` but the reported values were `%`. This fixes the discrepancy by changing how values are reported.
Side note: We could report a percentage, but there is no "official" OpenTelemetry guidance for it. If we want to do this (I'm not convinced that we should), we need to add a config option (allowing users to explicitly opt-in to this behavior) and create a new metric family, maybe `system.memory.utilization_percent`.
* Create two new config options, `ReportUsage` and `ReportUtilization`. The previous config options have been kept for compatibility.
* Utilization reporting has been enabled by default, following the OT semantic …
> [collectd 6] Memory plugin: Add "shared", drop "slab" and "available", report utilization as ratio.

- .cirrus.yml
- .github/workflows/build.yml
- configure.ac
By default, plugins that use the "compatibility mode" (i.e. they are still using `value_list_t` / `plugin_dispatch_values()`) are disabled.
ChangeLog: Build system: the `--enable-compatibility-mode` has been added to control whether or not to build plugins using the compatibility mode. Such plugins are considered "unstable" and the metrics reported by these plugins will change in the future.
> [collectd 6] feat: Add the `--enable-compatibility-mode` flag to the `configure` script.

- src/collectd.conf.in
- src/collectd.conf.pod
- src/df.c
* Fixed an error that caused inode utilization (a ratio) to be reported as "usage" (a count).
* Report utilization as "ratio" (i.e. fraction of one) instead of percentage.
* Change label names to match OpenTelemetry semantic conventions. E.g. use `system.filesystem.state` instead of `state`.
* Report the filesystem mode (read-only, read-write).
ChangeLog: DF plugin: The metric schema has been aligned with OpenTelemetry semantic conventions.
> [collectd 6] df plugin: Align metrics with OpenTelemetry recommendations.

- src/cgroups.c
- src/conntrack.c
- src/daemon/utils_cache.c
- src/daemon/utils_cache.h
- src/infiniband.c
- src/libcollectdclient/network_parse.c
- src/logparser.c
- src/redfish.c
- src/statsd.c
- src/table.c
- src/threshold.c
- src/turbostat.c
- src/utils/format_json/format_json.c
- src/utils/format_stackdriver/format_stackdriver.c
- src/write_prometheus.c
- src/write_riemann_threshold.c
- src/write_syslog.c
- src/write_tsdb.c
ChangeLog: Build: Fix some gcc warnings with more strict checks
Fixes are based on "-O3 -Werror -Wall -Wextra -Wformat-security" output:
* Properly initialize complex struct
* Tell compiler which args are expected to be unused with attributes
* Correct write_prometheus comments and use arg more like specified in MHD doc
Somebody may want to do similar thing for rest of collectd code, but I was interested only about core & write_prometheus plugin.
This is collected "main" (v5) branch version of (already merged) v6 PR: https://github.com/collectd/collectd/pull/3970
EDIT: added link to collectd v6 PR + dropped resolved comment about stuff discussed below.
> Fix some gcc warnings with more strict checks

- src/daemon/utils_cache.c
- src/daemon/utils_cache.h
Part of v5 changes in https://github.com/collectd/collectd/pull/3917 for v6.
> [collectd 6] remove unused uc_get_history() from src/daemon/utils_cache.c

- Makefile.am
- configure.ac
ChangeLog: Build system: Automatically enable the *gpu_sysman plugin* when `level-zero` is available.
While GPU plugin uses just Sysman API subset of the Level-Zero API family, name of the used library / loader is `level-zero` => renamed configure variables for the dependency to use level-zero/LEVEL_ZERO names.
Now that Level-Zero packages are in the distributions, I thought Sysman API GPU plugin can be enabled by default when `pkg-config` finds `level-zero`.  I did not think it that useful for user to be able to specify `level-zero` path with a configure option instead of suitable `PKG_CONFIG_PATH` env variable => dropped `--with-sysman` option.
(There was no good example of doing that in addition to using `pkg-config` in reasonable amount of configure.ac code.)
PS. Sysman plugin test …
> gpu_sysman: enable plugin automatically when `pkg-config` finds `level-zero` dependency

- src/disk.c
- src/types.db
Kernel 4.18+ appends four more fields for discard tracking putting the total at 18.
Kernel 5.5+ appends two more fields for flush requests. 
Details see: https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats
This patch makes collectd available for those fields.
Tested on kernel 5.15* (Ubuntu 22.04), e, g, 'write_log' writes things like:
"[{"values":[9993,5746],"dstypes":["derive","derive"],"dsnames":["complete","time"],"time":1705653958.743,"interval":10.000,"host":"7643","plugin":"disk","plugin_instance":"nvme0n1","type":"disk_flush","type_instance":""}]"
ChangeLog: disk plugin: supports /proc/diskstats fields 15 to 20 in Linux
> disk: add /proc/diskstats fields 15 to 20 in KERNEL_LINUX

- src/disk.c
* Rename labels to `system.device` and `disk.io.direction`.
* Rename `system.disk.time` to `system.disk.operation_time`.
* Add descriptions and units to all metric families.
* Add the "utilization" metric to FreeBSD.
ChangeLog: Disk plugin: The metric schema has been aligned with OpenTelemetry semantic conventions.
> [collectd 6] disk plugin: Align metrics with OpenTelemetry recommendations.

- src/collectd.conf.pod
> [collectd 6] docs: Fix the default value of the memory plugin's `ReportLimit` option.

- src/disk.c
Fixes the build on FreeBSD. This is a regression introduced in #4242.
> disk plugin: Build `disk_submit_single` on Linux only.

- .cirrus.yml
Investigating this error:
```
plugin cpu NOT linked against libstatgrab
```
> .cirrus.yml: statgrab: Print `ldd` of failing plugins. Continue on error.

- .cirrus.yml
The "statgrab" job builds collectd with the "statgrab" library and then expects certain plugins to be linked against it. However, since the build runs on Linux, the plugins are actually using the "native" implementation. The linker, noticing that the plugin is not referring to any symbol in the statgrab library, does not actually produce a link, causing the test to fail.
The native implementations provide much richer metrics than the libstatgrab based implementations, so we'll drop the test.
> [collectd 6] ci: Remove the "statgrab" task from CirrusCI.

- src/df.c
The second argument of the `for` loop always evaluated to true, causing the code to read past the end of the array.
ChangeLog: df plugin: An out of bounds read, causing segmentation faults, has been fixed.
> [collectd 6] fix: df plugin: Fix an array out of bounds crash.

- src/collectd.conf.in
- src/collectd.conf.pod
- src/disk.c
According to feedback by
#4242
This PR lets discard and flush metrics to be disabled by default and able to enabled by config options.
ChangeLog: disk plugin: options to control discard and flush metrics
> disk.c: add config options to support diskstats 15-20 in KERNEL_LINUX

- src/collectd.conf.in
- src/collectd.conf.pod
- src/swap.c
This is a replacement for #3815.
ChangeLog: swap plugin: Migration to v6.0.
>  [collectd 6] Swap plugin: Migrate to collectd 6 data structures.

- .gitignore
- src/daemon/plugin.c
- src/daemon/utils_cache.c
- src/redfish.c
- src/utils/format_stackdriver/format_stackdriver.c
- src/utils/lookup/vl_lookup_test.c
- src/utils/resource_metrics/resource_metrics.c
- src/utils/utf8/utf8_test.c
- src/utils/value_list/value_list_test.c
- src/write_prometheus.c
ChangeLog: Fix most `-Wpedantic` warnings in collectd core
I think first commit makes code more readable (and fixes comment typo).
Second commit should probably be dropped, as I do not see any reliable way to detect compilers that do not support C99 (`__func__` is variable in GCC, so one cannot use `#ifdef` check for it). It's included in case C89 compiler support is something that we do not actually care about (then few plugins could have similar change too)?
> [collectd 6] Fix most -Wpedantic warnings in collectd core

- src/chrony.c
- src/daemon/plugin.c
- src/df.c
- src/disk.c
- src/ipc.c
- src/irq.c
- src/ping.c
- src/utils/format_json/format_json_test.c
This allows plugins to call `plugin_dispatch_metric_family()` unconditionally.
ChangeLog: Daemon: The `plugin_dispatch_metric_family()` function has been changed to handle metric families with zero metrics gracefully.
> [collectd 6] fix: Handle metric families with zero metrics gracefully.

- src/write_redis.c
Technically these fields leak. Because they're allocated during start-up only, there is no runtime or user-observable impact, i.e. this is a cleanup.
> write_redis plugin: Clean up allocated fields in `wr_config_free()`.

- src/dcpmm.c
- src/dpdk_telemetry.c
- src/dpdkevents.c
- src/dpdkstat.c
- src/intel_pmu.c
- src/ipmi.c
- src/mcelog.c
- src/mdevents.c
- src/utils/cmds/cmds_test.c
- src/utils/dpdk/dpdk.c
- src/utils/dpdk/dpdk.h
- src/utils/ovs/ovs.c
This continues https://github.com/collectd/collectd/pull/4243:
* Change _all_ `__FUNCTION__` instances to C99 `__func__`, also in plugins
* I decided it's safe to do after all because collectd requires C99, and all these changes are to C-files (not C++)
* Fix `-Wpedantic` array/struct initialization warnings in `mdevents.c` plugin modified by above commit
* This commit is main one needing review
* Fix `-Wpendantic`/`-Wformat` warning in `cmds_test.c`
> [collectd 6, WIP] Fix more GCC "-Wpedantic" warnings

- src/utils/format_stackdriver/format_stackdriver.c
- src/utils/match/match.h
- src/utils/message_parser/message_parser.c
- src/utils/proc_pids/proc_pids.c
For one of the warnings I filed https://github.com/collectd/collectd/issues/4263 ticket. This PR fixes rest of warnings in collectd core files, shown by `-Wextra -Wno-missing-field-initializers` (latter option is needed, otherwise GCC complains also about `{0}` initializers):
```
$ for i in $(find src/ -mindepth 2 -name '*.c' | grep -v -e _test.c -e _mock.c -e _windows.c); do \
echo "*** $i ***"; \
gcc -I. -Isrc -Isrc/daemon -Isrc/libcollectdclient -I/usr/include/dpdk -DHAVE_CONFIG_H \
-O3 -Werror -Wall -Wextra -Wno-missing-field-initializers -c -o /dev/null $i; \
done
```
There was just one signed vs. unsigned warning for `format_stackdriver.c`. Instead of adding cast just for that, I chose to change `start_value` variables type from `int64_t` -> `counter_t` (`uint64_t`), as those …
> [collectd 6, WIP] Fix more GCC "-Wextra" warnings in collectd core

- Makefile.am
- src/daemon/plugin.c
- src/daemon/utils_cache.c
- src/daemon/utils_cache.h
- src/daemon/utils_cache_test.c
- src/utils/format_stackdriver/format_stackdriver.c
- src/write_redis.c
- src/write_redis_test.c
The *write_stackdriver plugin* uses the first observed time to scale counters so they appear to start from zero. OpenTelemetry calls this [inserting true reset points](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#cumulative-streams-inserting-true-reset-points). The new API returns the first metric time and first metric time in one call for consistency and efficiency.
This PR contains a few other, smaller improvements to the cache:
* A unit test for `uc_insert()` and `uc_get_rate()` has been added.
* The public `uc_init()` function has been removed in favor of automatic initialization. This simplifies using the cache from unit tests.
* The behavior of `uc_get_rate()` has been documented.
ChangeLog: Daemon: The first observed metric value has been added to the metrics cache.
> [collectd 6] cache: Provide the first metric value available alongside the first metric time.

- src/utils/format_stackdriver/format_stackdriver.c
- src/utils/format_stackdriver/format_stackdriver.h
- src/write_stackdriver.c
Follow up to  #4268:
> `sd_output_initialize()` can fail and return error without closing map, but its callers do not even check its return value
> [collectd 6] format_stackdriver: Add proper error handling to `sd_output_reset()`.

- src/write_prometheus.c
ChangeLog: Write Prometheus plugin: A possible deadlock due to a leaked mutex has been fixed.
> write_prometheus plugin: Fix a deadlock due to a leaked mutex.

- .cirrus.yml
- .github/workflows/build.yml
- configure.ac
- src/capabilities.c
- src/connectivity.c
- src/daemon/plugin.c
- src/daemon/utils_cache.c
- src/dpdkstat.c
- src/grpc.cc
- src/intel_rdt.c
- src/intel_rdt_test.c
- src/ipmi.c
- src/libcollectdclient/network_parse_test.c
- src/netlink.c
- src/network_test.c
- src/ovs_events.c
- src/ovs_stats.c
- src/procevent.c
- src/redfish_test.c
- src/sysevent.c
- src/utils/ovs/ovs.c
- src/utils/proc_pids/proc_pids_test.c
- src/utils/strbuf/strbuf.c
- src/virt.c
- src/write_influxdb_udp.c
- src/write_kafka.c
- src/write_prometheus.c
In pre-ANSI K&R-style C, functions can use an "initializer list" instead of a "parameter type list". Compilers still support this for backwards compatibility, unfortunately.
One result is that compilers will accept the following prototype:
```c
void foo();
```
Note that this probabaly does not mean what you think it means: this is a function with *an unknown number of arguments* and compilers will happily let you pass anything to it. In other words, the following would be legal:
```c
foo("Hello, World!");
```
This PR changes all (unintentional) uses of empty initializer lists to use `(void)` instead, which expresses what is intended: "this function takes no arguments". It also adds the `-Wstrict-prototypes` CFLAG to prevent backsliding.
> [collectd 6] Enable `-Wstrict-prototypes`.

- Makefile.am
- configure.ac
- src/collectd.conf.in
- src/collectd.conf.pod
- src/daemon/utils_cache.c
- src/open_telemetry.cc
- src/open_telemetry.h
- src/open_telemetry_collector.cc
- src/open_telemetry_exporter.cc
- src/open_telemetry_receiver.cc
This PR adds an gRPC server to collectd, implementing the OpenTelemetry `MetricsService`. This allows collectd to receive metrics via OTLP, for example from the OpenTelemetry Collector.
This new code and the *write_open_telemetry* plugin have been merged into one plugin, called "open_telemetry". Users can enable the exporter, the receiver, or both using the config file, just like they could in the *network plugin* in collectd 5.
**Known limitations:**
* Non-monotonic sums are rejected. We could either convert them to "gauge" or re-introduce "derive" metrics to get them to work.
* Counter resets are not yet detected. Mostly because this needs additional code in the "cache" and this PR is already quite large.
* Histograms, exponential histograms, and summary metrics are rejected.
ChangeLog: …
> [collectd 6] New plugin (sort of): OpenTelemetry receiver

- Makefile.am
- src/gpu_sysman_test.c
ChangeLog: Use real collectd metric functions in "gpu_sysman" plugin tests
There have been lot of changes in metric handling code, so it's better to use real metric functions rather than mocked ones.
This allows removing the mock functions, but makes it much easier for unrelated changes to break `gpu_sysman_test.c` compilation (e.g .utf-8 support already broke earlier version of this).
> [collectd 6] Use real collectd metric functions in gpu_sysman plugin tests

- Makefile.am
- src/lua_test.c
ChangeLog: lua: add missing test case for #3779, #4235
* luaC_pushoconfigitem
* luaC_pushnotification
In the previous versions, there was no test code for Lua plugin. Thus this is first step to improve such a situation.
> lua: add missing test case for #3779, #4235

- src/collectd.conf.pod
- src/gpu_sysman.c
- src/gpu_sysman_test.c
ChangeLog: gpu_sysman: add "LogMetrics" option
Adds "LogMetrics" option for real-time monitoring of the GPU metrics:
* Causes each metric value to be written also to collectd log, i.e. by default to console
* Avoids need to setup write plugins and delay caused by their use when investigating GPU behavior
* _Output is much more readable than write plugins' output_ [1]
[1] output looks like this (when only memory metric with just base output variant is enabled):
```
[1058954.410] b3:00.0: memory_used_bytes / device [0]: 26763264.000
[1058957.527] 3c:00.0: memory_used_bytes / device [0]: 26763264.000
[1058957.527] b3:00.0: memory_used_bytes / device [0]: 26763264.000
[1058961.528] 3c:00.0: memory_used_bytes / device [0]: 26763264.000
```
How it differs from the current write plugins' output: …
> [Collectd 6] gpu_sysman: add "LogMetrics" option

- configure.ac
- src/gpu_sysman.c
- src/gpu_sysman_test.c
ChangeLog: gpu_sysman: switch from zeInit() to zesInit() for Xe KMD support
LevelZero spec v1.5 introduced `zesInit()`, and deprecated `zeInit()`, for initializing Sysman part of L0: https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#initialization
Another motivation for introducing this, is L0 Intel backend supporting the new Xe KMD (for the future GPUs [1]), in addition to earlier i915 KMD (for current Intel GPUs), only when Sysman is initialized with `zesInit()`.
Changing to `zesInit()` requires also dropping use of L0 core API functions, and using only L0 Sysman API ones, which is not an exact match.  Therefore:
* Some of the information logged at plugin init (when GpuInfo option is used) needed to be dropped
* `pci_dev` (PCI device ID) label value needs to be digged from sysfs …
> [collectd 6] gpu_sysman: switch from zeInit() to zesInit()

- src/bind.c
ChangeLog: bind: fix warning for variable used only in DEBUG() calls
Fixes: https://github.com/collectd/collectd/issues/4305
> bind: fix warning for variable used only in DEBUG() calls

- src/collectd.conf.in
- src/collectd.conf.pod
- src/intel_rdt.c
Added llc_miss metric
ChangeLog: intel_rdt: Added support for LLC misses monitoring event
> feat: [intel_rdt] Added support for LLC misses monitoring event

- src/perl.c
ChangeLog: perl plugin: fix Clang compilation by ignoring a warning
Fixes: #4308
> perl plugin: fix Clang compilation by ignoring a warning

- README.md
As per discussion in https://github.com/collectd/collectd/issues/4323 . 
I doubt there are any problems with MariaDB. It is the default running in most distros - in Debian since 2017 and on Fedora since 2015 (if I remember correctly). If you are not getting bug reports from Debian/Fedora users, then collectd probably does not have any particular issues with MariaDB. 
ChangeLog: Update the README to include MariaDB.
> add MariaDB to README

- src/libcollectdclient/client.c
ChangeLog: collectd: The unit has been substracted to pass gcc stringop-truncation warning in lcc_receive function
The warning has been observed with gcc v14.2.1
> Fix lcc_receive

- src/smart.c
ChangeLog: smart plugin:  When UseSerial is enabled, allow configured ignored disk names to be copied to the serial ignore list for devices without serials.
When UseSerial is enabled, the existing code in create_ignorelist_by_serial has a condition that requires the device serial to be non-null to allow the ignore value from the config disk ignore list to carry over to the serial ignore list.
This change allows the config disk ignored value to carry over to the serial ignore list.
Note that without this change, it is not presently possible to ignore loop and raid devices such as /dev/loop1 and /dev/md127, as described in issue 3314.
Fixes #3314 
Fixes #3856
> Fix: for issue 3314 and 3856

- src/collectd.conf.in
- src/collectd.conf.pod
- src/processes.c
ChangeLog: processes plugin: do not post metrics from processes that are not running.
Currently, processes plugin will emit metrics even if the a process listed in ProcessMatch is not running. This is unnecessary and causes wasteful network/disk activity. 
For process not running all the metrics are 0 but they still submit data. This will lead to a waste of resources.
If a process listed on ProcessMatch runs after collectd is started, those process will start sending metrics.
Please help review. Thanks a lot!
> processes: do not post metrics from processes that are not running.

- src/logparser.c
Static analyzer detected
After having been assigned to a NULL value at logparser.c:248, pointer 'severity' is dereferenced at logparser.c:288 by calling function 'strcasecmp'.
- Added return value check for cf_util_get_string()
- Prevents potential NULL dereference in strcasecmp()
- Improves error handling consistency
Triggers found by static analyzer Svace.
Signed-off-by: Anton Moryakov [ant.v.moryakov@gmail.com](mailto:ant.v.moryakov@gmail.com)
ChangeLog: src: add NULL check for severity in logparser_config_message
> src: add NULL check for severity in logparser_config_message

- Makefile.am
- configure.ac
ChangeLog: configure: use pkg-config rather than libgcrypt-config when searching for libgcrypt
Rebase of #4355 for the `collectd-6.0` branch as requested.
> configure.ac: use pkg-config to find libgcrypt (collectd-6.0)

- src/curl.c
- src/curl_json.c
- src/curl_xml.c
The builds are failing due to error like:
src/curl.c:349:3: error: call to '_curl_easy_setopt_err_long' declared with attribute warning: curl_easy_setopt expects a long argument [-Werror=attribute-warning]
349 |   curl_easy_setopt(wp->curl, CURLOPT_IPRESOLVE, wp->address_family);
src/curl_xml.c:740:3: error: call to '_curl_easy_setopt_err_long' declared with attribute warning: curl_easy_setopt expects a long argument [-Werror=attribute-warning]
740 |   curl_easy_setopt(db->curl, CURLOPT_IPRESOLVE, db->address_family);
src/curl_json.c:586:3: error: call to '_curl_easy_setopt_err_long' declared with attribute warning: curl_easy_setopt expects a long argument [-Werror=attribute-warning]
586 |   curl_easy_setopt(db->curl, CURLOPT_IPRESOLVE, db->address_family);
The error were seen during a …
> Fix build due to error in curl_easy_setopt

- .cirrus.yml
ChangeLog: Use freebsd-13-5 image for Cirrus CI
> Fix FreeBSD image for Cirrus CI

- .cirrus.yml
ChangeLog: Fix FreeBSD image for Cirrus CI
> [collectd-6.0] Fix FreeBSD image for Cirrus CI
